-- This file was initially generated by Cursor using the Claude 3 Opus LLM model.
-- It contains the initial schema migration for PostgreSQL.

CREATE TABLE IF NOT EXISTS index (
    name TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    max_bulk_operations INTEGER NOT NULL,
    max_key_length INTEGER NOT NULL,
    max_value_length INTEGER NOT NULL,
    max_kv_pairs_per_context INTEGER NOT NULL,
    hash_algorithm TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    updated_by TEXT
);

CREATE TABLE IF NOT EXISTS context (
    hash TEXT PRIMARY KEY,
    pairs JSONB NOT NULL,
    dek TEXT,
    kek_id TEXT
);

CREATE TABLE IF NOT EXISTS entry (
    key UUID PRIMARY KEY,
    context_hash TEXT NOT NULL REFERENCES context(hash),
    index_name TEXT NOT NULL REFERENCES index(name)
); 