-- Initial indexes for performance optimization
-- This file was initially generated by Claude Code

-- Index for context hash lookups on entry table
-- Used by get_entries_by_context queries
CREATE INDEX idx_entry_context_hash ON entry (context_hash);

-- Index for index name lookups on entry table
-- Useful for filtering entries by index in operational queries
CREATE INDEX idx_entry_index_name ON entry (index_name);

-- Composite index for multi-tenant context lookups
-- Optimizes queries that filter by both index and context
CREATE INDEX idx_entry_index_context ON entry (index_name, context_hash);