// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the build script for generating Rust code from protobuf definitions.

use std::path::{Path, PathBuf};

/// Fix doc test code blocks in google.protobuf.rs by adding language tags
/// to prevent them from being compiled as Rust code
fn fix_google_protobuf_doctests(out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let google_protobuf = out_dir.join("google.protobuf.rs");

    if !google_protobuf.exists() {
        return Ok(());
    }

    let content = std::fs::read_to_string(&google_protobuf)?;

    // Fix each example by wrapping code blocks with appropriate language tags
    let fixed = content
        // Example 1: C code (POSIX time)
        .replace(
            "/// Example 1: Compute Timestamp from POSIX `time()`.\n///\n///      Timestamp timestamp;\n///      timestamp.set_seconds(time(NULL));\n///      timestamp.set_nanos(0);",
            "/// Example 1: Compute Timestamp from POSIX `time()`.\n///\n/// ```c\n///      Timestamp timestamp;\n///      timestamp.set_seconds(time(NULL));\n///      timestamp.set_nanos(0);\n/// ```"
        )
        // Example 2: C code (gettimeofday)
        .replace(
            "/// Example 2: Compute Timestamp from POSIX `gettimeofday()`.\n///\n///      struct timeval tv;\n///      gettimeofday(&tv, NULL);\n///\n///      Timestamp timestamp;\n///      timestamp.set_seconds(tv.tv_sec);\n///      timestamp.set_nanos(tv.tv_usec * 1000);",
            "/// Example 2: Compute Timestamp from POSIX `gettimeofday()`.\n///\n/// ```c\n///      struct timeval tv;\n///      gettimeofday(&tv, NULL);\n///\n///      Timestamp timestamp;\n///      timestamp.set_seconds(tv.tv_sec);\n///      timestamp.set_nanos(tv.tv_usec * 1000);\n/// ```"
        )
        // Example 3: C code (Win32 FILETIME)
        .replace(
            "/// Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.\n///\n///      FILETIME ft;\n///      GetSystemTimeAsFileTime(&ft);\n///      UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;\n///\n///      // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z\n///      // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.\n///      Timestamp timestamp;\n///      timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));\n///      timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));",
            "/// Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.\n///\n/// ```c\n///      FILETIME ft;\n///      GetSystemTimeAsFileTime(&ft);\n///      UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;\n///\n///      // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z\n///      // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.\n///      Timestamp timestamp;\n///      timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));\n///      timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));\n/// ```"
        )
        // Example 4: Java code (System.currentTimeMillis)
        .replace(
            "/// Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.\n///\n///      long millis = System.currentTimeMillis();\n///\n///      Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)\n///          .setNanos((int) ((millis % 1000) * 1000000)).build();",
            "/// Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.\n///\n/// ```java\n///      long millis = System.currentTimeMillis();\n///\n///      Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)\n///          .setNanos((int) ((millis % 1000) * 1000000)).build();\n/// ```"
        )
        // Example 5: Java code (Instant.now)
        .replace(
            "/// Example 5: Compute Timestamp from Java `Instant.now()`.\n///\n///      Instant now = Instant.now();\n///\n///      Timestamp timestamp =\n///          Timestamp.newBuilder().setSeconds(now.getEpochSecond())\n///              .setNanos(now.getNano()).build();",
            "/// Example 5: Compute Timestamp from Java `Instant.now()`.\n///\n/// ```java\n///      Instant now = Instant.now();\n///\n///      Timestamp timestamp =\n///          Timestamp.newBuilder().setSeconds(now.getEpochSecond())\n///              .setNanos(now.getNano()).build();\n/// ```"
        )
        // Example 6: Python code
        .replace(
            "/// Example 6: Compute Timestamp from current time in Python.\n///\n///      timestamp = Timestamp()\n///      timestamp.GetCurrentTime()",
            "/// Example 6: Compute Timestamp from current time in Python.\n///\n/// ```python\n///      timestamp = Timestamp()\n///      timestamp.GetCurrentTime()\n/// ```"
        );

    std::fs::write(&google_protobuf, fixed)?;
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Get the workspace root directory
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();

    // Define the protobuf source directory
    let proto_dir = workspace_root.join("protobuf");

    // Define the output directory for generated code
    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/generated");

    // Create the output directory if it doesn't exist
    std::fs::create_dir_all(&out_dir)?;

    // Configure the tonic builder
    let builder = tonic_build::configure()
        .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]")
        .out_dir(&out_dir)
        .compile_well_known_types(true)
        .build_server(true);

    // Compile the protobuf files
    builder.compile_protos(
        &[
            proto_dir.join("udex.index.v1.proto"),
            proto_dir.join("udex.entry.v1.proto"),
            proto_dir.join("udex.healthz.v1.proto"),
        ],
        &[proto_dir],
    )?;

    // Post-process google.protobuf.rs to fix doc test code blocks
    fix_google_protobuf_doctests(&out_dir)?;

    // Generate a mod.rs file to export the generated modules
    let mod_rs = out_dir.join("mod.rs");
    std::fs::write(
        mod_rs,
        r#"
// This file is automatically generated by the build script.
// Do not edit it manually.

pub mod udex {
    pub mod index {
        pub mod v1 {
            include!("udex.index.v1.rs");
        }
    }
    pub mod entry {
        pub mod v1 {
            include!("udex.entry.v1.rs");
        }
    }
    pub mod healthz {
        pub mod v1 {
            include!("udex.healthz.v1.rs");
        }
    }
}
// export the google.protobuf module so the generated code can use it
pub mod google {
    pub mod protobuf {
        include!("google.protobuf.rs");
    }
}
"#,
    )?;

    // Re-run the build script if any of the protobuf files change
    println!("cargo:rerun-if-changed=../protobuf/udex.index.v1.proto");
    println!("cargo:rerun-if-changed=../protobuf/udex.entry.v1.proto");

    Ok(())
}
