use anyhow::{Context, Result};

use crate::cli::{ConfigInitArgs, ConfigValidateArgs};
use crate::config::UdexConfig;

/// Default configuration template written by `udex config init`.
///
/// Uses bare URN strings for secrets so the file is loadable by `UdexConfig::load`.
/// Serialising `UdexConfig::default()` is not used here because `Secret<String>`
/// serialises as a masked value that cannot be round-tripped through the loader.
const CONFIG_TEMPLATE: &str = r#"# Udex server configuration
# Generated by `udex config init`
#
# Secrets are referenced by URN and resolved from environment variables at startup.
# Never put secret values directly in this file.
# Run `udex config validate` to check a config (requires env vars to be set).

[server]
bind_address = "127.0.0.1:50051"
request_timeout_secs = 30
max_connections = 1000
max_message_size_bytes = 4194304

[server.tls]
cert_path = "certs/server.crt"
key_path = "certs/server.key"

[server.authz]
# Exactly one of jwks_url or jwt_public_key_path is required.
# jwks_url = "https://auth.example.com/.well-known/jwks.json"
jwt_public_key_path = "certs/jwt_public_key.pem"
jwt_issuer = "https://auth.example.com"
jwt_audience = "udex"
# Allow plain HTTP for jwks_url — never set to true in production.
danger_allow_non_tls = false

[datastore]
# Secret values are referenced by URN using the secrets-rs crate
# (https://crates.io/crates/secrets-rs). The URN format is:
#
#   urn:secrets-rs:<source>:<name>
#
# where <source> is the secret source (currently only "env" is supported) and
# <name> is the environment variable to read at startup. The server will refuse
# to start if the named variable is absent or empty.
connection_url = "urn:secrets-rs:env:DATABASE_URL"
max_connections = 10
min_connections = 1
connection_timeout_secs = 10
query_timeout_secs = 30
# Allow non-TLS connections — never set to true in production.
dangerous_allow_non_tls = false
"#;

/// Generate a default configuration file.
///
/// Writes a commented TOML template to the specified path. Fails if the file
/// already exists to avoid accidentally overwriting a working config.
pub fn init(args: ConfigInitArgs) -> Result<()> {
    if args.path.exists() {
        anyhow::bail!(
            "config file already exists: {} (delete it first or choose a different path)",
            args.path.display()
        );
    }

    std::fs::write(&args.path, CONFIG_TEMPLATE)
        .with_context(|| format!("failed to write config file: {}", args.path.display()))?;

    println!("config written to {}", args.path.display());
    Ok(())
}

/// Validate an existing configuration file.
///
/// Loads the TOML file, binds secrets from environment variables, and runs
/// validation rules. Requires all secret env vars (e.g. `DATABASE_URL`) to be
/// set. Exits non-zero and prints all errors if the config is invalid.
pub fn validate(args: ConfigValidateArgs) -> Result<()> {
    let cfg = UdexConfig::load(&args.config)?;
    cfg.validate()
        .with_context(|| format!("config file is invalid: {}", args.config.display()))?;
    println!("config is valid: {}", args.config.display());
    Ok(())
}
