// Generated by Claude Code (claude-sonnet-4-6)

//! Handlers for `udex config` subcommands.

use anyhow::{Context, Result};

use crate::cli::{ConfigInitArgs, ConfigValidateArgs};
use crate::config::UdexConfig;

/// Generate a default configuration file.
///
/// Writes a well-commented TOML config to the specified path. Fails if the
/// file already exists to avoid accidentally overwriting a working config.
pub fn init(args: ConfigInitArgs) -> Result<()> {
    if args.path.exists() {
        anyhow::bail!(
            "config file already exists: {} (delete it first or choose a different path)",
            args.path.display()
        );
    }

    let content = toml::to_string_pretty(&UdexConfig::default())
        .context("failed to serialise default config")?;

    // Prepend a short header comment — toml::to_string_pretty doesn't support comments.
    let header = "# Udex server configuration\n# Generated by `udex config init`\n#\n# Secrets should be injected via environment variables, not stored in this file.\n# The datastore connection_url supports ${VAR} placeholders resolved from env.\n\n";

    std::fs::write(&args.path, format!("{}{}", header, content))
        .with_context(|| format!("failed to write config file: {}", args.path.display()))?;

    println!("config written to {}", args.path.display());
    Ok(())
}

/// Validate an existing configuration file.
///
/// Loads the TOML file, parses it, and runs validation rules. Exits non-zero
/// and prints all errors if the config is invalid.
pub fn validate(args: ConfigValidateArgs) -> Result<()> {
    let cfg = UdexConfig::load(&args.config)?;
    cfg.validate()
        .with_context(|| format!("config file is invalid: {}", args.config.display()))?;
    println!("config is valid: {}", args.config.display());
    Ok(())
}
