// Generated by Claude Code (claude-sonnet-4-6)

//! Handler for `udex context` subcommands.

use anyhow::Result;

use crate::cli::ContextHashArgs;

/// Compute the hash of a context (offline).
pub fn hash(_args: ContextHashArgs) -> Result<()> {
    anyhow::bail!("not implemented")
}
