// Generated by Claude Code (claude-sonnet-4-6)

//! Handler for `udex context` subcommands.

use anyhow::{Context, Result};
use udex_api::entry::{value, ContextInput, KeyValuePair, Value};
use udex_api::hash::xxh3_context_hash;

use crate::cli::ContextHashArgs;

/// Compute the xxh3 hash of a context (offline — no server needed).
///
/// Parses KEY=VALUE pairs into a context and prints the hash that the server
/// would assign. Useful for pre-computing context hashes before calling
/// `udex entry lookup`.
pub fn hash(args: ContextHashArgs) -> Result<()> {
    let pairs: Vec<KeyValuePair> = args
        .context
        .iter()
        .map(|s| {
            let (k, v) = s
                .split_once('=')
                .with_context(|| format!("context item must be KEY=VALUE, got: {s:?}"))?;
            Ok(KeyValuePair {
                key: k.to_string(),
                value: Some(Value {
                    value: Some(value::Value::StringValue(v.to_string())),
                }),
                kek_id: None,
                dek: None,
            })
        })
        .collect::<Result<_>>()?;

    let context = ContextInput { pairs };

    let h = xxh3_context_hash(&context).context("failed to compute context hash")?;
    println!("{h}");
    Ok(())
}
