// Generated by Claude Code (claude-sonnet-4-6)

//! Handlers for `udex entry` subcommands.

use anyhow::Result;

use crate::cli::{EntryCreateArgs, EntryDeleteArgs, EntryGetArgs, EntryLookupArgs, OutputFormat};

/// Create a new entry.
pub async fn create(_args: EntryCreateArgs) -> Result<()> {
    anyhow::bail!("not implemented")
}

/// Get an entry by key.
pub async fn get(_args: EntryGetArgs, _output: &OutputFormat) -> Result<()> {
    anyhow::bail!("not implemented")
}

/// Reverse-lookup entries by context.
pub async fn lookup(_args: EntryLookupArgs, _output: &OutputFormat) -> Result<()> {
    anyhow::bail!("not implemented")
}

/// Delete an entry by key.
pub async fn delete(_args: EntryDeleteArgs) -> Result<()> {
    anyhow::bail!("not implemented")
}
