// Generated by Claude Code (claude-sonnet-4-6)

//! Handlers for `udex entry` subcommands.

use anyhow::{Context, Result};
use tabled::{Table, Tabled};
use udex_api::entry::entry_service_client::EntryServiceClient;
use udex_api::entry::{
    value, ContextInput, CreateEntryRequest, DeleteEntryRequest, KeyValuePair,
    LookupContextByKeyRequest, LookupKeysByContextRequest, Value,
};
use udex_api::hash::sha1_context_hash;

use crate::cli::{EntryCreateArgs, EntryDeleteArgs, EntryGetArgs, EntryLookupArgs, OutputFormat};
use crate::client::ClientConfig;

// ---------------------------------------------------------------------------
// Context K=V parsing
// ---------------------------------------------------------------------------

/// Parse `KEY=VALUE` strings into `KeyValuePair`s. Values are treated as strings.
fn parse_context_pairs(args: &[String]) -> Result<Vec<KeyValuePair>> {
    args.iter()
        .map(|s| {
            let (k, v) = s
                .split_once('=')
                .with_context(|| format!("context item must be KEY=VALUE, got: {s:?}"))?;
            Ok(KeyValuePair {
                key: k.to_string(),
                value: Some(Value {
                    value: Some(value::Value::StringValue(v.to_string())),
                }),
                kek_id: None,
            })
        })
        .collect()
}

fn build_context_input(args: &[String]) -> Result<ContextInput> {
    Ok(ContextInput {
        pairs: parse_context_pairs(args)?,
        dek: None,
        kek_id: None,
    })
}

// ---------------------------------------------------------------------------
// Table display helpers
// ---------------------------------------------------------------------------

#[derive(Tabled)]
struct KvRow {
    #[tabled(rename = "Key")]
    key: String,
    #[tabled(rename = "Value")]
    value: String,
}

#[derive(Tabled)]
struct EntryKeyRow {
    #[tabled(rename = "Key")]
    key: String,
}

fn value_to_string(v: Option<Value>) -> String {
    match v.and_then(|v| v.value) {
        Some(value::Value::StringValue(s)) => s,
        Some(value::Value::IntValue(i)) => i.to_string(),
        Some(value::Value::FloatValue(f)) => f.to_string(),
        Some(value::Value::BoolValue(b)) => b.to_string(),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// Command handlers
// ---------------------------------------------------------------------------

/// Create a new entry.
pub async fn create(
    client: ClientConfig,
    args: EntryCreateArgs,
    output: &OutputFormat,
) -> Result<()> {
    let context = build_context_input(&args.context)?;

    let channel = client.channel().await?;
    let mut grpc = EntryServiceClient::with_interceptor(channel, client.interceptor());

    let resp = grpc
        .create_entry(CreateEntryRequest {
            index_name: args.index,
            context: Some(context),
        })
        .await
        .context("create_entry RPC failed")?
        .into_inner();

    match output {
        OutputFormat::Table => {
            let rows = vec![
                KvRow {
                    key: "key".to_string(),
                    value: resp.key,
                },
                KvRow {
                    key: "context_hash".to_string(),
                    value: resp.context_hash,
                },
            ];
            println!("{}", Table::new(rows));
        }
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&resp)?);
        }
        OutputFormat::Yaml => {
            print!("{}", serde_yaml::to_string(&resp)?);
        }
    }
    Ok(())
}

/// Get an entry's context by key.
pub async fn get(client: ClientConfig, args: EntryGetArgs, output: &OutputFormat) -> Result<()> {
    let channel = client.channel().await?;
    let mut grpc = EntryServiceClient::with_interceptor(channel, client.interceptor());

    let resp = grpc
        .lookup_context_by_key(LookupContextByKeyRequest {
            index_name: args.index,
            key: args.key,
        })
        .await
        .context("lookup_context_by_key RPC failed")?
        .into_inner();

    let ctx = resp.context.context("server returned empty context")?;

    match output {
        OutputFormat::Table => {
            let rows: Vec<KvRow> = ctx
                .pairs
                .into_iter()
                .map(|p| KvRow {
                    key: p.key,
                    value: value_to_string(p.value),
                })
                .collect();
            println!("{}", Table::new(rows));
        }
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&ctx)?);
        }
        OutputFormat::Yaml => {
            print!("{}", serde_yaml::to_string(&ctx)?);
        }
    }
    Ok(())
}

/// Reverse-lookup entries by context — finds all keys matching the given context.
pub async fn lookup(
    client: ClientConfig,
    args: EntryLookupArgs,
    output: &OutputFormat,
) -> Result<()> {
    let context = build_context_input(&args.context)?;
    let context_hash = sha1_context_hash(&context).context("failed to compute context hash")?;

    let channel = client.channel().await?;
    let mut grpc = EntryServiceClient::with_interceptor(channel, client.interceptor());

    let resp = grpc
        .lookup_keys_by_context(LookupKeysByContextRequest {
            index_name: args.index,
            context_hash,
        })
        .await
        .context("lookup_keys_by_context RPC failed")?
        .into_inner();

    match output {
        OutputFormat::Table => {
            let rows: Vec<EntryKeyRow> = resp
                .keys
                .into_iter()
                .map(|k| EntryKeyRow { key: k })
                .collect();
            println!("{}", Table::new(rows));
        }
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&resp.keys)?);
        }
        OutputFormat::Yaml => {
            print!("{}", serde_yaml::to_string(&resp.keys)?);
        }
    }
    Ok(())
}

/// Delete an entry by key.
pub async fn delete(client: ClientConfig, args: EntryDeleteArgs) -> Result<()> {
    let channel = client.channel().await?;
    let mut grpc = EntryServiceClient::with_interceptor(channel, client.interceptor());

    grpc.delete_entry(DeleteEntryRequest {
        index_name: args.index,
        key: args.key,
    })
    .await
    .context("delete_entry RPC failed")?;

    println!("deleted");
    Ok(())
}
