// Generated by Claude Code (claude-sonnet-4-6)

//! Command handlers for the `udex` CLI.
//!
//! Each submodule owns one top-level subcommand group. Handlers receive the
//! parsed args and the global [`crate::cli::Cli`] context, and return
//! `anyhow::Result<()>`. Errors are printed to stderr by `main`.

pub mod config;
pub mod context;
pub mod entry;
pub mod index;
pub mod migrate;
pub mod serve;
pub mod token;
