// Generated by Claude Code (claude-sonnet-4-6)

//! Handler for `udex serve`.

use anyhow::Result;

use crate::cli::ServeArgs;

/// Start the Udex gRPC server in the foreground.
pub async fn run(_args: ServeArgs) -> Result<()> {
    anyhow::bail!("not implemented")
}
