// Generated by Claude Code (claude-sonnet-4-6)

//! Handler for `udex serve`.

use anyhow::{Context, Result};

use crate::cli::ServeArgs;
use crate::config::UdexConfig;

/// Start the Udex gRPC server in the foreground.
///
/// Loads configuration from the resolved path, validates it, initialises the
/// PostgreSQL datastore (running migrations), and starts the gRPC server.
/// Runs until interrupted (Ctrl+C / SIGTERM).
pub async fn run(args: ServeArgs) -> Result<()> {
    let cfg = UdexConfig::load(&args.config)?;
    cfg.validate()?;
    let (server_config, datastore_config) = cfg
        .into_configs()
        .with_context(|| format!("failed to build configs from {}", args.config.display()))?;

    udex_server::start(server_config, datastore_config)
        .await
        .context("server exited with an error")
}
