// Generated by Claude Code (claude-sonnet-4-6)

//! Handler for `udex token` subcommands.

use anyhow::Result;

use crate::cli::TokenInspectArgs;

/// Decode and display a JWT without signature verification.
pub fn inspect(_args: TokenInspectArgs) -> Result<()> {
    anyhow::bail!("not implemented")
}
