// Generated by Claude Code (claude-sonnet-4-6)

//! Handler for `udex token` subcommands.

use anyhow::{Context, Result};
use jsonwebtoken::{DecodingKey, Validation};
use std::collections::HashSet;

use crate::cli::TokenInspectArgs;

/// Decode and display a JWT without signature verification.
///
/// Prints the header and claims as pretty-printed JSON. Does not verify the
/// signature — useful for inspecting tokens during development/debugging.
pub fn inspect(args: TokenInspectArgs) -> Result<()> {
    let header = jsonwebtoken::decode_header(&args.token).context("invalid JWT header")?;

    // Decode claims without verifying signature or checking standard claims.
    let mut validation = Validation::default();
    validation.insecure_disable_signature_validation();
    validation.required_spec_claims = HashSet::new();
    // Accept any algorithm since we're not verifying.
    validation.algorithms = vec![
        jsonwebtoken::Algorithm::HS256,
        jsonwebtoken::Algorithm::HS384,
        jsonwebtoken::Algorithm::HS512,
        jsonwebtoken::Algorithm::RS256,
        jsonwebtoken::Algorithm::RS384,
        jsonwebtoken::Algorithm::RS512,
        jsonwebtoken::Algorithm::ES256,
        jsonwebtoken::Algorithm::ES384,
        jsonwebtoken::Algorithm::PS256,
        jsonwebtoken::Algorithm::PS384,
        jsonwebtoken::Algorithm::PS512,
        jsonwebtoken::Algorithm::EdDSA,
    ];

    let token_data = jsonwebtoken::decode::<serde_json::Value>(
        &args.token,
        &DecodingKey::from_secret(&[]),
        &validation,
    )
    .context("invalid JWT claims")?;

    println!("=== Header ===");
    println!("{}", serde_json::to_string_pretty(&header)?);
    println!();
    println!("=== Claims ===");
    println!("{}", serde_json::to_string_pretty(&token_data.claims)?);

    // Print human-readable expiry if present.
    if let Some(exp) = token_data.claims.get("exp").and_then(|v| v.as_i64()) {
        use time::OffsetDateTime;
        match OffsetDateTime::from_unix_timestamp(exp) {
            Ok(dt) => {
                let now = OffsetDateTime::now_utc();
                if dt < now {
                    let secs = (now - dt).whole_seconds();
                    println!();
                    println!("exp: EXPIRED {} seconds ago ({})", secs, dt);
                } else {
                    let secs = (dt - now).whole_seconds();
                    println!();
                    println!("exp: valid for {} more seconds ({})", secs, dt);
                }
            }
            Err(_) => {
                println!();
                println!("exp: {} (unreadable timestamp)", exp);
            }
        }
    }

    Ok(())
}
