// Generated by Claude Code (claude-sonnet-4-6)

//! Integration tests for the `udex` CLI binary.
//!
//! These tests invoke the compiled binary via `assert_cmd` and assert on exit
//! codes and output. No server or database is required for the tests in this
//! file — they cover argument parsing, help text, and error paths only.

use assert_cmd::Command;
use predicates::prelude::*;

fn udex() -> Command {
    Command::cargo_bin("udex").expect("udex binary not found")
}

// --- help ---

#[test]
fn test_help_exits_zero() {
    udex().arg("--help").assert().success();
}

#[test]
fn test_help_mentions_subcommands() {
    udex()
        .arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains("serve"))
        .stdout(predicate::str::contains("config"))
        .stdout(predicate::str::contains("index"))
        .stdout(predicate::str::contains("entry"))
        .stdout(predicate::str::contains("token"))
        .stdout(predicate::str::contains("context"));
}

#[test]
fn test_serve_help_exits_zero() {
    udex().args(["serve", "--help"]).assert().success();
}

#[test]
fn test_config_help_exits_zero() {
    udex().args(["config", "--help"]).assert().success();
}

#[test]
fn test_index_help_exits_zero() {
    udex().args(["index", "--help"]).assert().success();
}

#[test]
fn test_entry_help_exits_zero() {
    udex().args(["entry", "--help"]).assert().success();
}

#[test]
fn test_token_help_exits_zero() {
    udex().args(["token", "--help"]).assert().success();
}

#[test]
fn test_context_help_exits_zero() {
    udex().args(["context", "--help"]).assert().success();
}

// --- unknown subcommands ---

#[test]
fn test_unknown_subcommand_exits_nonzero() {
    udex().arg("unknown").assert().failure();
}

#[test]
fn test_no_subcommand_exits_nonzero() {
    udex().assert().failure();
}

// --- commands exit non-zero without a server ---

#[test]
fn test_index_list_fails_without_server() {
    // Transport-level failure (connection refused) → exit code 8.
    udex()
        .args(["index", "list"])
        .assert()
        .code(8)
        .stderr(predicate::str::contains("transport error"));
}

#[test]
fn test_token_inspect_rejects_invalid_token() {
    udex()
        .args(["token", "inspect", "not.a.jwt"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("invalid JWT"));
}

#[test]
fn test_token_inspect_decodes_valid_token() {
    // Standard jwt.io example token (HS256, no expiry)
    let token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\
        .eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ\
        .SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
    udex()
        .args(["token", "inspect", token])
        .assert()
        .success()
        .stdout(predicate::str::contains("Header"))
        .stdout(predicate::str::contains("Claims"))
        .stdout(predicate::str::contains("HS256"));
}

#[test]
fn test_context_hash_prints_hex_string() {
    udex()
        .args(["context", "hash", "--context", "key=value"])
        .assert()
        .success()
        .stdout(predicate::str::is_match("^[0-9a-f]{16}\n$").unwrap());
}

#[test]
fn test_context_hash_is_deterministic() {
    let out1 = udex()
        .args(["context", "hash", "--context", "a=1", "--context", "b=2"])
        .output()
        .unwrap();
    let out2 = udex()
        .args(["context", "hash", "--context", "b=2", "--context", "a=1"])
        .output()
        .unwrap();
    assert!(
        out1.status.success(),
        "first invocation failed\nstderr: {}",
        String::from_utf8_lossy(&out1.stderr)
    );
    assert!(
        out2.status.success(),
        "second invocation failed\nstderr: {}",
        String::from_utf8_lossy(&out2.stderr)
    );
    assert_eq!(out1.stdout, out2.stdout, "hash must be order-independent");
}

#[test]
fn test_context_hash_rejects_invalid_pair() {
    udex()
        .args(["context", "hash", "--context", "no-equals-sign"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("KEY=VALUE"));
}
