// Generated by Claude Code (claude-sonnet-4-6)

//! Integration tests for the `udex` CLI binary.
//!
//! These tests invoke the compiled binary via `assert_cmd` and assert on exit
//! codes and output. No server or database is required for the tests in this
//! file — they cover argument parsing, help text, and error paths only.

use assert_cmd::Command;
use predicates::prelude::*;

fn udex() -> Command {
    Command::cargo_bin("udex").expect("udex binary not found")
}

// --- help ---

#[test]
fn test_help_exits_zero() {
    udex().arg("--help").assert().success();
}

#[test]
fn test_help_mentions_subcommands() {
    udex()
        .arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains("serve"))
        .stdout(predicate::str::contains("config"))
        .stdout(predicate::str::contains("index"))
        .stdout(predicate::str::contains("entry"))
        .stdout(predicate::str::contains("token"))
        .stdout(predicate::str::contains("context"));
}

#[test]
fn test_serve_help_exits_zero() {
    udex().args(["serve", "--help"]).assert().success();
}

#[test]
fn test_config_help_exits_zero() {
    udex().args(["config", "--help"]).assert().success();
}

#[test]
fn test_index_help_exits_zero() {
    udex().args(["index", "--help"]).assert().success();
}

#[test]
fn test_entry_help_exits_zero() {
    udex().args(["entry", "--help"]).assert().success();
}

#[test]
fn test_token_help_exits_zero() {
    udex().args(["token", "--help"]).assert().success();
}

#[test]
fn test_context_help_exits_zero() {
    udex().args(["context", "--help"]).assert().success();
}

// --- unknown subcommands ---

#[test]
fn test_unknown_subcommand_exits_nonzero() {
    udex().arg("unknown").assert().failure();
}

#[test]
fn test_no_subcommand_exits_nonzero() {
    udex().assert().failure();
}

// --- commands exit non-zero without a server ---

#[test]
fn test_index_list_fails_without_server() {
    // index list is implemented; with no server running it fails with a connection error.
    udex()
        .args(["index", "list"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("failed to connect"));
}

#[test]
fn test_token_inspect_stub_exits_nonzero() {
    udex()
        .args(["token", "inspect", "some.jwt.token"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("not implemented"));
}

#[test]
fn test_context_hash_stub_exits_nonzero() {
    udex()
        .args(["context", "hash", "--context", "key=value"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("not implemented"));
}
