// Generated by Claude Code (claude-sonnet-4-6)

//! Integration tests for `udex config` subcommands.
//!
//! All tests are offline — no server or database required.

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

fn udex() -> Command {
    Command::cargo_bin("udex").expect("udex binary not found")
}

// --- config init ---

#[test]
fn test_config_init_creates_file() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");

    udex()
        .args(["config", "init", "--path", config_path.to_str().unwrap()])
        .assert()
        .success()
        .stdout(predicate::str::contains("config written to"));

    assert!(config_path.exists(), "config file should have been created");
    let content = std::fs::read_to_string(&config_path).unwrap();
    assert!(
        content.contains("bind_address"),
        "config should contain server fields"
    );
    assert!(
        content.contains("connection_url"),
        "config should contain datastore fields"
    );
    assert!(
        content.contains("jwt_public_key_path"),
        "config should contain authnz fields"
    );
}

#[test]
fn test_config_init_fails_if_file_exists() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");
    std::fs::write(&config_path, "# existing").unwrap();

    udex()
        .args(["config", "init", "--path", config_path.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("already exists"));
}

#[test]
fn test_config_init_default_path_is_udex_toml() {
    // Verify --help shows the default path
    udex()
        .args(["config", "init", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::contains("udex.toml"));
}

// --- config validate ---

#[test]
fn test_config_validate_accepts_valid_config() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");

    // Generate a valid config first
    udex()
        .args(["config", "init", "--path", config_path.to_str().unwrap()])
        .assert()
        .success();

    udex()
        .args([
            "config",
            "validate",
            "--config",
            config_path.to_str().unwrap(),
        ])
        .assert()
        .success()
        .stdout(predicate::str::contains("config is valid"));
}

#[test]
fn test_config_validate_fails_for_missing_file() {
    udex()
        .args(["config", "validate", "--config", "/nonexistent/udex.toml"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("failed to read config file"));
}

#[test]
fn test_config_validate_fails_for_invalid_toml() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");
    std::fs::write(&config_path, "this is not [ valid toml").unwrap();

    udex()
        .args([
            "config",
            "validate",
            "--config",
            config_path.to_str().unwrap(),
        ])
        .assert()
        .failure()
        .stderr(predicate::str::contains("failed to parse config file"));
}

#[test]
fn test_config_validate_fails_for_missing_jwt_key() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");

    // Write a config without jwt_public_key_path
    let content = r#"
[server]
bind_address = "127.0.0.1:50051"
request_timeout_secs = 30
max_connections = 1000
max_message_size_bytes = 4194304

[server.tls]
cert_path = "certs/server.crt"
key_path = "certs/server.key"

[server.authnz]
jwt_issuer = "https://auth.example.com"
jwt_audience = "udex"

[datastore]
connection_url = "postgres://localhost/udex"
max_connections = 10
min_connections = 1
connection_timeout_secs = 10
query_timeout_secs = 30
"#;
    std::fs::write(&config_path, content).unwrap();

    udex()
        .args([
            "config",
            "validate",
            "--config",
            config_path.to_str().unwrap(),
        ])
        .assert()
        .failure()
        .stderr(predicate::str::contains("jwt_public_key_path is required"));
}
