// Generated by Claude Code (claude-sonnet-4-6)

//! Tests for `udex serve`.
//!
//! Full server-up tests (TLS, live Postgres, health check) are covered in the
//! integration test suite. These tests cover config loading and early error paths
//! that don't require a running server or database.

use assert_cmd::Command;
use predicates::prelude::*;
use tempfile::TempDir;

fn udex() -> Command {
    Command::cargo_bin("udex").expect("udex binary not found")
}

#[test]
fn test_serve_fails_with_missing_config() {
    udex()
        .args(["serve", "--config", "/nonexistent/udex.toml"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("failed to read config file"));
}

#[test]
fn test_serve_fails_with_invalid_config() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");
    std::fs::write(&config_path, "not valid toml [[[").unwrap();

    udex()
        .args(["serve", "--config", config_path.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("failed to parse config file"));
}

#[test]
fn test_serve_fails_with_invalid_bind_address() {
    let dir = TempDir::new().unwrap();
    let config_path = dir.path().join("udex.toml");

    // Generate a valid config then patch the bind address
    Command::cargo_bin("udex")
        .unwrap()
        .args(["config", "init", "--path", config_path.to_str().unwrap()])
        .assert()
        .success();

    let content = std::fs::read_to_string(&config_path).unwrap();
    let patched = content.replace(
        r#"bind_address = "127.0.0.1:50051""#,
        r#"bind_address = "not-an-address""#,
    );
    std::fs::write(&config_path, patched).unwrap();

    udex()
        .args(["serve", "--config", config_path.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("invalid bind_address"));
}
