apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udex.fullname" . }}
  labels:
    {{- include "udex.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc }}
  tls.crt: {{ .Values.secrets.tlsCrt | b64enc }}
  tls.key: {{ .Values.secrets.tlsKey | b64enc }}
