// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains configuration structures for the Udex datastore.

use serde::{Deserialize, Serialize};
use std::time::Duration;

/// Datastore configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatastoreConfig {
    /// Database connection URL
    pub connection_url: String,
    /// Maximum number of connections in the pool
    pub max_connections: u32,
    /// Minimum number of connections in the pool
    pub min_connections: u32,
    /// Connection timeout duration
    pub connection_timeout: Duration,
    /// Query timeout duration
    pub query_timeout: Duration,
}

impl DatastoreConfig {
    /// Validate the datastore configuration.
    pub fn validate(&self) -> Result<(), DatastoreConfigError> {
        if self.connection_url.is_empty() {
            return Err(DatastoreConfigError::Validation("connection_url cannot be empty".to_string()));
        }
        
        if self.max_connections == 0 {
            return Err(DatastoreConfigError::Validation("max_connections must be greater than 0".to_string()));
        }
        
        if self.min_connections > self.max_connections {
            return Err(DatastoreConfigError::Validation("min_connections cannot be greater than max_connections".to_string()));
        }
        
        Ok(())
    }

    /// Get the datastore configuration URL with environment variable substitution.
    pub fn resolved_connection_url(&self) -> String {
        // Simple environment variable substitution
        let mut url = self.connection_url.clone();
        
        // Replace common environment variables
        if let Ok(db_host) = std::env::var("DB_HOST") {
            url = url.replace("${DB_HOST}", &db_host);
        }
        if let Ok(db_port) = std::env::var("DB_PORT") {
            url = url.replace("${DB_PORT}", &db_port);
        }
        if let Ok(db_user) = std::env::var("DB_USER") {
            url = url.replace("${DB_USER}", &db_user);
        }
        if let Ok(db_password) = std::env::var("DB_PASSWORD") {
            url = url.replace("${DB_PASSWORD}", &db_password);
        }
        if let Ok(db_name) = std::env::var("DB_NAME") {
            url = url.replace("${DB_NAME}", &db_name);
        }
        
        url
    }
}

/// Datastore configuration error types.
#[derive(Debug, thiserror::Error)]
pub enum DatastoreConfigError {
    /// Validation error
    #[error("Datastore config validation failed: {0}")]
    Validation(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_datastore_config_validation() {
        let mut config = DatastoreConfig {
            connection_url: "postgres://localhost:5432/udex".to_string(),
            max_connections: 10,
            min_connections: 1,
            connection_timeout: Duration::from_secs(10),
            query_timeout: Duration::from_secs(30),
        };
        
        // Test empty connection URL
        config.connection_url = String::new();
        assert!(config.validate().is_err());
        
        // Test invalid max_connections
        config.connection_url = "postgres://localhost:5432/udex".to_string();
        config.max_connections = 0;
        assert!(config.validate().is_err());
        
        // Test min_connections > max_connections
        config.max_connections = 5;
        config.min_connections = 10;
        assert!(config.validate().is_err());
        
        // Test valid config
        config.min_connections = 2;
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_connection_url_substitution() {
        let mut config = DatastoreConfig {
            connection_url: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}".to_string(),
            max_connections: 10,
            min_connections: 1,
            connection_timeout: Duration::from_secs(10),
            query_timeout: Duration::from_secs(30),
        };
        
        std::env::set_var("DB_HOST", "localhost");
        std::env::set_var("DB_PORT", "5432");
        std::env::set_var("DB_USER", "test_user");
        std::env::set_var("DB_PASSWORD", "test_pass");
        std::env::set_var("DB_NAME", "test_db");
        
        let url = config.resolved_connection_url();
        assert_eq!(url, "postgres://test_user:test_pass@localhost:5432/test_db");
        
        // Clean up environment variables
        std::env::remove_var("DB_HOST");
        std::env::remove_var("DB_PORT");
        std::env::remove_var("DB_USER");
        std::env::remove_var("DB_PASSWORD");
        std::env::remove_var("DB_NAME");
    }
}