// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains configuration structures for the Udex datastore.

use serde::{Deserialize, Serialize};
use std::time::Duration;

/// Datastore configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatastoreConfig {
    /// Database connection URL
    pub connection_url: String,
    /// Maximum number of connections in the pool
    pub max_connections: u32,
    /// Minimum number of connections in the pool
    pub min_connections: u32,
    /// Connection timeout duration
    pub connection_timeout: Duration,
    /// Query timeout duration
    pub query_timeout: Duration,
    /// Disable the TLS enforcement check on the connection URL.
    ///
    /// **DANGER**: Setting this to `true` allows plaintext database connections.
    /// Only use this in local development or test environments. Production
    /// deployments MUST leave this `false` and include `sslmode=require` (or
    /// stronger) in the connection URL.
    #[serde(default)]
    pub dangerous_allow_non_tls: bool,
}

/// Returns `true` if the URL contains a TLS-enforcing `sslmode` value
/// (`require`, `verify-ca`, or `verify-full`).
fn url_enforces_tls(url: &str) -> bool {
    let query = url.split_once('?').map(|(_, q)| q).unwrap_or("");
    for param in query.split('&') {
        if let Some(value) = param.strip_prefix("sslmode=") {
            return matches!(value, "require" | "verify-ca" | "verify-full");
        }
    }
    false
}

/// Substitutes `${VAR}` placeholders in `url` using the provided lookup function.
/// Returns an error if any placeholder remains unresolved after substitution.
fn resolve_placeholders(
    url: &str,
    lookup: impl Fn(&str) -> Option<String>,
) -> Result<String, DatastoreConfigError> {
    let mut url = url.to_string();

    for (var, placeholder) in [
        ("DB_HOST", "${DB_HOST}"),
        ("DB_PORT", "${DB_PORT}"),
        ("DB_USER", "${DB_USER}"),
        ("DB_PASSWORD", "${DB_PASSWORD}"),
        ("DB_NAME", "${DB_NAME}"),
    ] {
        if let Some(value) = lookup(var) {
            url = url.replace(placeholder, &value);
        }
    }

    if url.contains("${") {
        return Err(DatastoreConfigError::Validation(format!(
            "connection_url contains unresolved placeholder(s): {}",
            url
        )));
    }

    Ok(url)
}

impl DatastoreConfig {
    /// Validate the datastore configuration.
    pub fn validate(&self) -> Result<(), DatastoreConfigError> {
        if self.connection_url.is_empty() {
            return Err(DatastoreConfigError::Validation(
                "connection_url cannot be empty".to_string(),
            ));
        }

        if self.max_connections == 0 {
            return Err(DatastoreConfigError::Validation(
                "max_connections must be greater than 0".to_string(),
            ));
        }

        if self.min_connections > self.max_connections {
            return Err(DatastoreConfigError::Validation(
                "min_connections cannot be greater than max_connections".to_string(),
            ));
        }

        if !self.dangerous_allow_non_tls && !url_enforces_tls(&self.connection_url) {
            return Err(DatastoreConfigError::NonTlsConnection);
        }

        Ok(())
    }

    /// Get the datastore configuration URL with environment variable substitution.
    ///
    /// Returns an error if any `${VAR}` placeholder remains unresolved after substitution.
    pub fn resolved_connection_url(&self) -> Result<String, DatastoreConfigError> {
        resolve_placeholders(&self.connection_url, |k| std::env::var(k).ok())
    }
}

/// Datastore configuration error types.
#[derive(Debug, thiserror::Error)]
pub enum DatastoreConfigError {
    /// Validation error
    #[error("Datastore config validation failed: {0}")]
    Validation(String),
    /// Non-TLS connection URL without the override flag set
    #[error(
        "connection_url does not enforce TLS (sslmode=require/verify-ca/verify-full required); \
         set dangerous_allow_non_tls=true to override in non-production environments"
    )]
    NonTlsConnection,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_datastore_config_validation() {
        let mut config = DatastoreConfig {
            connection_url: "postgres://localhost:5432/udex?sslmode=require".to_string(),
            max_connections: 10,
            min_connections: 1,
            connection_timeout: Duration::from_secs(10),
            query_timeout: Duration::from_secs(30),
            dangerous_allow_non_tls: false,
        };

        // Test empty connection URL
        config.connection_url = String::new();
        assert!(config.validate().is_err());

        // Test invalid max_connections
        config.connection_url = "postgres://localhost:5432/udex?sslmode=require".to_string();
        config.max_connections = 0;
        assert!(config.validate().is_err());

        // Test min_connections > max_connections
        config.max_connections = 5;
        config.min_connections = 10;
        assert!(config.validate().is_err());

        // Test valid config (TLS enforced via sslmode=require)
        config.min_connections = 2;
        assert!(config.validate().is_ok());
    }

    #[test]
    fn test_tls_enforcement() {
        let base = DatastoreConfig {
            max_connections: 10,
            min_connections: 1,
            connection_timeout: Duration::from_secs(10),
            query_timeout: Duration::from_secs(30),
            dangerous_allow_non_tls: false,
            connection_url: String::new(),
        };

        // No sslmode at all — rejected
        let mut cfg = base.clone();
        cfg.connection_url = "postgres://host:5432/db".to_string();
        assert!(cfg.validate().is_err());

        // sslmode=disable — rejected
        cfg.connection_url = "postgres://host:5432/db?sslmode=disable".to_string();
        assert!(cfg.validate().is_err());

        // sslmode=prefer — rejected (can fall back to plaintext)
        cfg.connection_url = "postgres://host:5432/db?sslmode=prefer".to_string();
        assert!(cfg.validate().is_err());

        // sslmode=require — accepted
        cfg.connection_url = "postgres://host:5432/db?sslmode=require".to_string();
        assert!(cfg.validate().is_ok());

        // sslmode=verify-ca — accepted
        cfg.connection_url = "postgres://host:5432/db?sslmode=verify-ca".to_string();
        assert!(cfg.validate().is_ok());

        // sslmode=verify-full — accepted
        cfg.connection_url = "postgres://host:5432/db?sslmode=verify-full".to_string();
        assert!(cfg.validate().is_ok());

        // No sslmode, but dangerous_allow_non_tls=true — accepted
        cfg.connection_url = "postgres://host:5432/db".to_string();
        cfg.dangerous_allow_non_tls = true;
        assert!(cfg.validate().is_ok());
    }

    #[test]
    fn test_connection_url_substitution() {
        let lookup = |k: &str| -> Option<String> {
            match k {
                "DB_HOST" => Some("localhost".to_string()),
                "DB_PORT" => Some("5432".to_string()),
                "DB_USER" => Some("test_user".to_string()),
                "DB_PASSWORD" => Some("test_pass".to_string()),
                "DB_NAME" => Some("test_db".to_string()),
                _ => None,
            }
        };

        let url = resolve_placeholders(
            "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}",
            lookup,
        )
        .expect("all placeholders should be resolved");
        assert_eq!(url, "postgres://test_user:test_pass@localhost:5432/test_db");

        // Unresolved placeholder should return an error
        let result = resolve_placeholders("postgres://user:pass@${DB_HOST}:5432/db", |_| None);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("unresolved placeholder"));
    }
}
