// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the core datastore interface and types for Udex.

use serde::{Deserialize, Serialize};
use sqlx::{postgres::PgArgumentBuffer, Database, Encode, Type};
use thiserror::Error;
use udex_api::entry::Context;
use udex_api::index::{Index, IndexUpdate};
use uuid::Uuid;

use crate::config::DatastoreConfig;

pub mod config;
pub mod postgres;

#[cfg(feature = "integration_test")]
pub mod integration_test;

/// Trait for SQL type conversion
pub trait SqlType: Send + Sync {
    type Database: Database;
    fn type_info() -> <Self::Database as Database>::TypeInfo;
}

#[derive(Debug, Error)]
pub enum Error {
    #[error("Database error: {0}")]
    Database(#[from] sqlx::Error),
    #[error("Context not found: {0}")]
    EntryForKeyNotFound(String),
    #[error("Key not found: {0}")]
    EntryForContextNotFound(Uuid),
    #[error("Invalid context: {0}")]
    InvalidContext(String),
    #[error("Transaction error: {0}")]
    Transaction(String),
    #[error("Serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
    #[error("Invalid index: {0}")]
    InvalidIndex(String),
    #[error("Data conversion error: {0}")]
    DataConversion(String),
    /// Type of error that occurs when trying to create an entry for a context that already exists
    #[error("Duplicate key: {0}")]
    DuplicateKey(String),
    /// Type of error that occurs when database is not properly initialized
    #[error("Database not initialized: {0}")]
    DatabaseNotInitialized(String),
    /// Type of error that occurs when a requested operation is not implemented
    #[error("Not implemented: {0}")]
    NotImplemented(String),
    /// Type of error that occurs when
    #[error("Invalid index update: {0}")]
    InvalidIndexUpdate(String),
    // Type of error related to migrations
    #[error("Migration error: {0}")]
    Migration(String),
    /// A context with the same hash already exists but has different encryption metadata
    /// (dek / kek_id). Callers are responsible for message-level encryption; silently
    /// substituting their dek would be data loss.
    #[error(
        "Context conflict: hash {0} already exists with different encryption metadata (dek/kek_id)"
    )]
    ContextEncryptionConflict(String),
}

/// Type of error that occurs when a bulk operation fails
/// derived as a separate type so it can reference the Error enum without causing a circular dependency
#[derive(Debug, Error)]
#[error("Bulk operation failed: {0}", msg)]
pub struct BulkOperationError {
    msg: String,
    #[source]
    source: crate::Error,
}

/// Wrapper type for Uuid to implement SQL traits
#[derive(Debug, Clone, Copy)]
pub struct UuidWrapper(pub Uuid);

impl SqlType for UuidWrapper {
    type Database = sqlx::Postgres;
    fn type_info() -> sqlx::postgres::PgTypeInfo {
        sqlx::postgres::PgTypeInfo::with_name("uuid")
    }
}

impl<'q> Encode<'q, sqlx::Postgres> for UuidWrapper {
    fn encode_by_ref(
        &self,
        buf: &mut PgArgumentBuffer,
    ) -> std::result::Result<sqlx::encode::IsNull, Box<dyn std::error::Error + Send + Sync + 'static>>
    {
        buf.extend_from_slice(self.0.as_bytes());
        Ok(sqlx::encode::IsNull::No)
    }
}

impl Type<sqlx::Postgres> for UuidWrapper {
    fn type_info() -> sqlx::postgres::PgTypeInfo {
        sqlx::postgres::PgTypeInfo::with_name("uuid")
    }
}

/// Represents an Entry in the index: a mapping between a key and a context
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    pub key: Uuid,
    pub context: Context,
    pub index_name: String,
}

pub enum EntryWriteOperation {
    Create(Entry),
    Delete(Uuid),
}

pub enum EntryReadOperation {
    GetByKey(Uuid),
    GetByContext(String),
}

pub enum EntryReadResult {
    Entry(Entry),
    Entries(Vec<Entry>),
}

/// Trait for datastore operations
#[async_trait::async_trait]
pub trait Datastore: Send + Sync {
    /// Initialize a datastore with the config and return a new instance.
    async fn init(config: DatastoreConfig) -> Result<Box<Self>, Error>
    where
        Self: Sized;

    /// Checks the server is healthy
    async fn is_healthy(&self) -> Result<bool, Error>;

    /// Create a new index
    async fn create_index(&self, index: Index) -> Result<(), Error>;

    /// Get an index by name
    async fn get_index(&self, name: &str) -> Result<Index, Error>;

    /// Update an existing index (only mutable fields)
    /// i.e. all but the name
    async fn update_index(
        &self,
        name: &str,
        update: IndexUpdate,
        updated_by: &str,
    ) -> Result<Index, Error>;

    /// List all indices
    async fn list_indices(&self) -> Result<Vec<Index>, Error>;

    /// Create a new entry.
    ///
    /// If the context already exists (same hash) and the key is new, a new entry is created
    /// against the existing context. Returns `DuplicateKey` if the key already exists.
    ///
    /// Returns `ContextEncryptionConflict` if a context with the same hash already exists
    /// but has different `dek` or `kek_id`: callers own message-level encryption and silently
    /// substituting their DEK would be undetectable data loss.
    async fn create_entry(&self, entry: Entry) -> Result<(), Error>;

    /// Get an entry by key
    async fn get_entry_by_key(&self, key: Uuid) -> Result<Entry, Error>;

    /// Get an entry by context hash
    async fn get_entries_by_context(&self, context_hash: &str) -> Result<Vec<Entry>, Error>;

    /// Delete an entry - if there are other keys mapped to the same context then these entries will remain. If this is the last key for the context then the context will also be deleted.
    async fn delete_entry(&self, key: Uuid) -> Result<(), Error>;

    /// Perform multiple entry write operations in a single transaction.
    /// Any failure will rollback all operations.
    async fn bulk_entry_write(
        &self,
        operations: Vec<EntryWriteOperation>,
    ) -> Result<(), BulkOperationError>;

    /// Perform multiple entry read operations in a single transaction.
    /// All reads will be executed in a single transaction and will have the same isolation level.
    async fn bulk_entry_read(
        &self,
        operations: Vec<EntryReadOperation>,
    ) -> Result<Vec<EntryReadResult>, BulkOperationError>;

    /// The database type for this datastore
    type Database: Database;
}

/// Trait for datastore migrations
#[async_trait::async_trait]
pub trait Migrator: Send + Sync {
    /// Migrate the datastore to the latest version.
    async fn migrate(&self) -> Result<(), Error>;

    /// Get the current version of the datastore.
    async fn current_version(&self) -> Result<i64, Error>;

    /// Get the latest version of the datastore.
    async fn latest_version(&self) -> Result<i64, Error>;

    /// check the migration version matches available migrations
    async fn check_migration_version(&self) -> Result<(), Error> {
        let current_version = self.current_version().await?;
        let latest_version = self.latest_version().await?;
        if current_version != latest_version {
            return Err(Error::DatabaseNotInitialized(format!(
                "Current version {} does not match latest version {}",
                current_version, latest_version
            )));
        }
        Ok(())
    }
}
