// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the PostgreSQL implementation of the Datastore trait.

use crate::config::DatastoreConfig;
use crate::{
    BulkOperationError, Datastore, Entry, EntryReadOperation, EntryReadResult, EntryWriteOperation,
    Error, Migrator, UuidWrapper,
};
use serde_json::{self};
use sqlx::postgres::PgPool;
use sqlx::Row;
use std::fs;
use std::path::Path;
use std::sync::Arc;
use time::OffsetDateTime;
use udex_api::entry::{Context, KeyValuePair};
use udex_api::index::{HashAlgorithm, Index, IndexUpdate};
use udex_api::{google_timestamp_to_offset_datetime, offset_datetime_to_google_timestamp};
use uuid::Uuid;

pub struct PostgresDatastore {
    #[allow(dead_code)]
    config: DatastoreConfig,
    pool: Arc<PgPool>,
}

impl PostgresDatastore {
    fn new(config: DatastoreConfig, pool: PgPool) -> Self {
        Self {
            config,
            pool: Arc::new(pool),
        }
    }
}

impl PostgresDatastore {
    // Private helper methods for transaction-based operations

    /// Private method to create an entry within an existing transaction
    async fn create_entry_tx(
        &self,
        entry: Entry,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    ) -> Result<(), Error> {
        // Fetch only the hash_algorithm from the index within the transaction to avoid
        // a pool read outside the transaction boundary.
        let hash_algorithm_str = sqlx::query_scalar::<_, String>(
            "SELECT hash_algorithm FROM index WHERE name = $1",
        )
        .bind(&entry.index_name)
        .fetch_optional(&mut **tx)
        .await
        .map_err(Error::Database)?
        .ok_or_else(|| Error::InvalidIndex(format!("Index '{}' not found", entry.index_name)))?;
        // Check if an entry with this key already exists
        let existing_entry = sqlx::query("SELECT key FROM entry WHERE key = $1")
            .bind(UuidWrapper(entry.key))
            .fetch_optional(&mut **tx)
            .await
            .map_err(Error::Database)?;

        if existing_entry.is_some() {
            return Err(Error::DuplicateKey(format!(
                "Entry with key {} already exists",
                entry.key
            )));
        }

        // First insert the context (using ON CONFLICT DO NOTHING to handle duplicates)
        sqlx::query(
            r#"
            INSERT INTO context (
                hash,
                pairs,
                dek,
                kek_id,
                hash_algorithm
            )
            VALUES (
                $1,
                $2,
                $3,
                $4,
                $5
            )
            ON CONFLICT (hash) DO NOTHING -- This allows us to skip inserting if it already exists.
            "#,
        )
        .bind(&entry.context.hash)
        .bind(serde_json::to_value(&entry.context.pairs).map_err(Error::Serialization)?)
        .bind(&entry.context.dek)
        .bind(&entry.context.kek_id)
        .bind(hash_algorithm_str)
        .execute(&mut **tx)
        .await
        .map_err(Error::Database)?;

        // Then insert the entry
        sqlx::query(
            r#"
            INSERT INTO entry (
                key,
                context_hash,
                index_name
            )
            VALUES (
                $1,
                $2,
                $3
            )
            "#,
        )
        .bind(UuidWrapper(entry.key))
        .bind(&entry.context.hash)
        .bind(&entry.index_name)
        .execute(&mut **tx)
        .await
        .map_err(Error::Database)?;

        Ok(())
    }

    /// Private method to delete an entry within an existing transaction
    async fn delete_entry_tx(
        &self,
        key: Uuid,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    ) -> Result<(), Error> {
        // First delete the entry
        let result = sqlx::query(
            r#"
            DELETE FROM entry
            WHERE key = $1
            "#,
        )
        .bind(UuidWrapper(key))
        .execute(&mut **tx)
        .await
        .map_err(Error::Database)?;

        if result.rows_affected() == 0 {
            return Err(Error::EntryForKeyNotFound(key.to_string()));
        }

        // Then delete any orphaned contexts (contexts with no remaining entries)
        sqlx::query(
            r#"
            DELETE FROM 
                context 
            AS c
            WHERE NOT EXISTS (
                SELECT 1
                FROM entry
                WHERE
                    context_hash = c.hash
            )
            "#,
        )
        .execute(&mut **tx)
        .await
        .map_err(Error::Database)?;

        Ok(())
    }

    /// Get an entry by key within an existing executor, which might be a transaction
    async fn get_entry_by_key_ex<'e, E>(&self, key: Uuid, executor: E) -> Result<Entry, Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let row = sqlx::query(
            r#"
            SELECT
                e.key,
                e.context_hash,
                e.index_name,
                c.pairs,
                c.dek,
                c.kek_id,
                c.hash_algorithm
            FROM
                entry e
                JOIN context c ON e.context_hash = c.hash
            WHERE
                e.key = $1
            "#,
        )
        .bind(key)
        .fetch_one(executor)
        .await
        .map_err(Error::Database)?;

        let pairs_value: serde_json::Value = row.try_get("pairs").map_err(Error::Database)?;
        let pairs: Vec<KeyValuePair> =
            serde_json::from_value(pairs_value).map_err(Error::Serialization)?;

        // Read hash_algorithm from database but don't use it yet since Context struct doesn't have this field
        let _hash_algorithm: String = row.try_get("hash_algorithm").map_err(Error::Database)?;

        let context = Context {
            hash: row.try_get("context_hash").map_err(Error::Database)?,
            pairs,
            dek: row.try_get("dek").map_err(Error::Database)?,
            kek_id: row.try_get("kek_id").map_err(Error::Database)?,
        };

        let entry = Entry {
            key: row.try_get("key").map_err(Error::Database)?,
            context,
            index_name: row.try_get("index_name").map_err(Error::Database)?,
        };

        Ok(entry)
    }

    /// Get entries by context hash within an existing executor, which might be a transaction
    async fn get_entries_by_context_ex<'e, E>(
        &self,
        context_hash: &str,
        executor: E,
    ) -> Result<Vec<Entry>, Error>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let rows = sqlx::query(
            r#"
            SELECT
                e.key,
                e.context_hash,
                e.index_name,
                c.pairs,
                c.dek,
                c.kek_id,
                c.hash_algorithm
            FROM
                entry e
                JOIN context c ON e.context_hash = c.hash
            WHERE
                e.context_hash = $1
            "#,
        )
        .bind(context_hash)
        .fetch_all(executor)
        .await
        .map_err(Error::Database)?;

        let entries = rows
            .into_iter()
            .map(|row| {
                let pairs_value: serde_json::Value =
                    row.try_get("pairs").map_err(Error::Database)?;
                let pairs: Vec<KeyValuePair> =
                    serde_json::from_value(pairs_value).map_err(Error::Serialization)?;

                // Read hash_algorithm from database but don't use it yet since Context struct doesn't have this field
                let _hash_algorithm: String = row.try_get("hash_algorithm").map_err(Error::Database)?;

                let context = Context {
                    hash: row.try_get("context_hash").map_err(Error::Database)?,
                    pairs,
                    dek: row.try_get("dek").map_err(Error::Database)?,
                    kek_id: row.try_get("kek_id").map_err(Error::Database)?,
                };

                Ok(Entry {
                    key: row.try_get("key").map_err(Error::Database)?,
                    context,
                    index_name: row.try_get("index_name").map_err(Error::Database)?,
                })
            })
            .collect::<Result<Vec<Entry>, Error>>()?;

        Ok(entries)
    }
}

#[async_trait::async_trait]
impl Datastore for PostgresDatastore {
    type Database = sqlx::Postgres;

    async fn init(config: DatastoreConfig) -> Result<Box<Self>, Error> {
        // Configure the pool with settings from config
        let pool = sqlx::postgres::PgPoolOptions::new()
            .max_connections(config.max_connections)
            .min_connections(config.min_connections)
            .acquire_timeout(config.connection_timeout)
            .idle_timeout(config.query_timeout)
            .connect(&config.resolved_connection_url().map_err(|e| Error::DatabaseNotInitialized(e.to_string()))?)
            .await
            .map_err(Error::Database)?;

        // Verify database connection
        sqlx::query("SELECT 1")
            .execute(&pool)
            .await
            .map_err(Error::Database)?;

        // Check the transaction isolation level is READ COMMITTED.
        // This is the only level currently supported.
        let row = sqlx::query("SHOW TRANSACTION ISOLATION LEVEL")
            .fetch_one(&pool)
            .await
            .map_err(Error::Database)?;

        // Extract the isolation level from the first column
        let isolation_level: String = row.try_get(0).map_err(|e| {
            Error::DataConversion(format!("Failed to extract isolation level: {}", e))
        })?;

        // Map the isolation to read COMMITTED or DatabaseNotInitialized.
        match isolation_level.as_str() {
            "read committed" => (),
            _ => {
                return Err(Error::DatabaseNotInitialized(format!(
                    "Unsupported isolation level: {}",
                    isolation_level
                )))
            }
        }

        Ok(Box::new(PostgresDatastore::new(config, pool)))
    }

    async fn is_healthy(&self) -> Result<bool, Error> {
        // check we can select from the database
        sqlx::query("SELECT 1")
            .execute(&*self.pool)
            .await
            .map_err(Error::Database)?;

        Ok(true)
    }

    async fn create_index(&self, index: Index) -> Result<(), Error> {
        let created_at = {
            match google_timestamp_to_offset_datetime(index.created_at) {
                Err(_) => {
                    return Err(Error::InvalidIndex(
                        "Index created_at failed to convert".to_string(),
                    ))
                }
                Ok(None) => {
                    return Err(Error::InvalidIndex(
                        "Index must have a created_at timestamp".to_string(),
                    ))
                }
                Ok(Some(dt)) => dt,
            }
        };

        let hash_algorithm_str = HashAlgorithm::try_from(index.hash_algorithm)
            .map_err(|_| {
                Error::InvalidIndex(format!(
                    "Invalid hash_algorithm value: {}",
                    index.hash_algorithm
                ))
            })?
            .as_str_name();

        sqlx::query(
            r#"
            INSERT INTO index (
                name,
                description,
                max_bulk_operations,
                max_key_length,
                max_value_length,
                max_kv_pairs_per_context,
                hash_algorithm,
                created_at,
                created_by
            )
            VALUES (
                $1,
                $2,
                $3,
                $4,
                $5,
                $6,
                $7,
                $8,
                $9
            )
            "#,
        )
        .bind(&index.name)
        .bind(&index.description)
        .bind(index.max_bulk_operations)
        .bind(index.max_key_length)
        .bind(index.max_value_length)
        .bind(index.max_kv_pairs_per_context)
        .bind(hash_algorithm_str)
        .bind(created_at)
        .bind(&index.created_by)
        .execute(&*self.pool)
        .await
        .map_err(Error::Database)?;

        Ok(())
    }

    async fn get_index(&self, name: &str) -> Result<Index, Error> {
        let row = sqlx::query(
            r#"
            SELECT
                name,
                description,
                max_bulk_operations,
                max_key_length,
                max_value_length,
                max_kv_pairs_per_context,
                hash_algorithm,
                created_at,
                created_by,
                updated_at,
                updated_by
            FROM
                index
            WHERE
                name = $1
            "#,
        )
        .bind(name)
        .fetch_one(&*self.pool)
        .await
        .map_err(Error::Database)?;

        // Convert chrono DateTime back to prost Timestamp
        let created_at = offset_datetime_to_google_timestamp(
            row.try_get::<Option<OffsetDateTime>, _>("created_at")
                .map_err(Error::Database)?
                .map(|dt| dt.into()),
        )
        .map_err(|e| Error::DataConversion(format!("created_at conversion failed: {:?}", e)))?;

        let updated_at = offset_datetime_to_google_timestamp(
            row.try_get::<Option<OffsetDateTime>, _>("updated_at")
                .map_err(Error::Database)?
                .map(|dt| dt.into()),
        )
        .map_err(|e| Error::DataConversion(format!("updated_at conversion failed: {:?}", e)))?;

        let index = Index {
            name: row.try_get("name").map_err(Error::Database)?,
            description: row.try_get("description").map_err(Error::Database)?,
            max_bulk_operations: row
                .try_get("max_bulk_operations")
                .map_err(Error::Database)?,
            max_key_length: row.try_get("max_key_length").map_err(Error::Database)?,
            max_value_length: row.try_get("max_value_length").map_err(Error::Database)?,
            max_kv_pairs_per_context: row
                .try_get("max_kv_pairs_per_context")
                .map_err(Error::Database)?,
            hash_algorithm: match row.try_get::<&str, _>("hash_algorithm") {
                Ok(h) => match HashAlgorithm::from_str_name(h) {
                    Some(alg) => alg as i32,
                    None => {
                        return Err(Error::InvalidIndex(format!(
                            "Invalid hash_algorithm value: {}",
                            h
                        )))
                    }
                },
                Err(e) => return Err(Error::Database(e)),
            },
            created_at,
            created_by: row.try_get("created_by").map_err(Error::Database)?,
            updated_at,
            updated_by: row.try_get("updated_by").map_err(Error::Database)?,
        };

        Ok(index)
    }

    async fn update_index(
        &self,
        name: &str,
        update: IndexUpdate,
        updated_by: &str,
    ) -> Result<Index, Error> {
        // valdiate there are fields to update otherwise throw InvalidIndexUpdate error
        if update.description.is_none()
            && update.max_bulk_operations.is_none()
            && update.max_key_length.is_none()
            && update.max_value_length.is_none()
            && update.max_kv_pairs_per_context.is_none()
            && update.hash_algorithm.is_none()
        {
            return Err(Error::InvalidIndexUpdate("No fields to update".to_string()));
        }

        use time::OffsetDateTime;

        let now = OffsetDateTime::now_utc();

        // Implement full update support for all optional fields
        sqlx::query(
            r#"
            UPDATE index 
            SET 
                description = COALESCE($1, description),
                max_bulk_operations = COALESCE($2, max_bulk_operations),
                max_key_length = COALESCE($3, max_key_length),
                max_value_length = COALESCE($4, max_value_length),
                max_kv_pairs_per_context = COALESCE($5, max_kv_pairs_per_context),
                hash_algorithm = COALESCE($6, hash_algorithm),
                updated_at = $7,
                updated_by = $8
            WHERE name = $9
            "#,
        )
        .bind(&update.description)
        .bind(update.max_bulk_operations)
        .bind(update.max_key_length)
        .bind(update.max_value_length)
        .bind(update.max_kv_pairs_per_context)
        .bind(match update.hash_algorithm {
            Some(h) => match HashAlgorithm::try_from(h) {
                Ok(alg) => Some(alg.as_str_name()),
                Err(_) => {
                    return Err(Error::InvalidIndex(format!(
                        "Invalid hash_algorithm value: {}",
                        h
                    )))
                }
            },
            None => None,
        })
        .bind(now)
        .bind(updated_by)
        .bind(name)
        .execute(&*self.pool)
        .await
        .map_err(Error::Database)?;

        // Return the updated index
        self.get_index(name).await
    }

    async fn list_indices(&self) -> Result<Vec<Index>, Error> {
        let rows = sqlx::query(
            r#"
            SELECT
                name,
                description,
                max_bulk_operations,
                max_key_length,
                max_value_length,
                max_kv_pairs_per_context,
                hash_algorithm,
                created_at,
                created_by,
                updated_at,
                updated_by
            FROM
                index
            ORDER BY
                name
            "#,
        )
        .fetch_all(&*self.pool)
        .await
        .map_err(Error::Database)?;

        let indices = rows
            .into_iter()
            .map(|row| {
                // Convert chrono NaiveDateTime back to prost Timestamp.
                let created_at = offset_datetime_to_google_timestamp(
                    row.try_get::<Option<OffsetDateTime>, _>("created_at")
                        .map_err(Error::Database)?
                        .map(|dt| dt.into()),
                )
                .map_err(|e| {
                    Error::InvalidIndex(format!("created_at conversion failed: {:?}", e))
                })?;

                let updated_at = offset_datetime_to_google_timestamp(
                    row.try_get::<Option<OffsetDateTime>, _>("updated_at")
                        .map_err(Error::Database)?
                        .map(|dt| dt.into()),
                )
                .map_err(|e| {
                    Error::InvalidIndex(format!("updated_at conversion failed: {:?}", e))
                })?;

                Ok(Index {
                    name: row.try_get("name").map_err(Error::Database)?,
                    description: row.try_get("description").map_err(Error::Database)?,
                    max_bulk_operations: row
                        .try_get("max_bulk_operations")
                        .map_err(Error::Database)?,
                    max_key_length: row.try_get("max_key_length").map_err(Error::Database)?,
                    max_value_length: row.try_get("max_value_length").map_err(Error::Database)?,
                    max_kv_pairs_per_context: row
                        .try_get("max_kv_pairs_per_context")
                        .map_err(Error::Database)?,
                    hash_algorithm: match row.try_get::<&str, _>("hash_algorithm") {
                        Ok(h) => match HashAlgorithm::from_str_name(h) {
                            Some(alg) => alg as i32,
                            None => {
                                return Err(Error::InvalidIndex(format!(
                                    "Invalid hash_algorithm value: {}",
                                    h
                                )))
                            }
                        },
                        Err(e) => return Err(Error::Database(e)),
                    },
                    created_at,
                    created_by: row.try_get("created_by").map_err(Error::Database)?,
                    updated_at,
                    updated_by: row.try_get("updated_by").map_err(Error::Database)?,
                })
            })
            .collect::<Result<Vec<Index>, Error>>()?;

        Ok(indices)
    }

    async fn create_entry(&self, entry: Entry) -> Result<(), Error> {
        let mut tx = self.pool.begin().await.map_err(Error::Database)?;
        self.create_entry_tx(entry, &mut tx).await?;
        tx.commit().await.map_err(Error::Database)?;
        Ok(())
    }

    async fn get_entry_by_key(&self, key: Uuid) -> Result<Entry, Error> {
        self.get_entry_by_key_ex(key, &*self.pool).await
    }

    async fn get_entries_by_context(&self, context_hash: &str) -> Result<Vec<Entry>, Error> {
        self.get_entries_by_context_ex(context_hash, &*self.pool)
            .await
    }

    async fn delete_entry(&self, key: Uuid) -> Result<(), Error> {
        let mut tx = self.pool.begin().await.map_err(Error::Database)?;
        self.delete_entry_tx(key, &mut tx).await?;
        tx.commit().await.map_err(Error::Database)?;
        Ok(())
    }

    async fn bulk_entry_read(
        &self,
        operations: Vec<EntryReadOperation>,
    ) -> Result<Vec<EntryReadResult>, BulkOperationError> {
        let mut results = Vec::new();

        for operation in operations {
            let result: Result<EntryReadResult, Error> = match operation {
                EntryReadOperation::GetByKey(key) => {
                    self.get_entry_by_key_ex(key, &*self.pool)
                        .await
                        .map(EntryReadResult::Entry)
                }
                EntryReadOperation::GetByContext(context_hash) => {
                    self.get_entries_by_context_ex(&context_hash, &*self.pool)
                        .await
                        .map(EntryReadResult::Entries)
                }
            };
            match result {
                Ok(res) => results.push(res),
                Err(e) => {
                    return Err(BulkOperationError {
                        msg: "Bulk read operation failed".to_string(),
                        source: e,
                    });
                }
            }
        }

        Ok(results)
    }

    async fn bulk_entry_write(
        &self,
        operations: Vec<EntryWriteOperation>,
    ) -> Result<(), BulkOperationError> {
        let mut tx = self.pool.begin().await.map_err(|e| BulkOperationError {
            msg: "Failed to begin transaction".to_string(),
            source: Error::Database(e),
        })?;

        for operation in operations {
            let result: Result<(), Error> = match operation {
                EntryWriteOperation::Create(entry) => self.create_entry_tx(entry, &mut tx).await,
                EntryWriteOperation::Delete(key) => self.delete_entry_tx(key, &mut tx).await,
            };
            if let Err(e) = result {
                tx.rollback().await.map_err(|err| BulkOperationError {
                    msg: "Failed to rollback transaction".to_string(),
                    source: Error::Database(err),
                })?;
                return Err(BulkOperationError {
                    msg: "Bulk operation failed".to_string(),
                    source: e,
                });
            }
        }

        tx.commit().await.map_err(|e| BulkOperationError {
            msg: "Failed to commit transaction".to_string(),
            source: Error::Database(e),
        })?;

        Ok(())
    }
}

#[async_trait::async_trait]
impl Migrator for PostgresDatastore {
    async fn migrate(&self) -> Result<(), Error> {
        tracing::info!("Running migrations");

        // note that the macro embeds the migrations into the binary
        // see https://docs.rs/sqlx/latest/sqlx/macro.migrate.html
        sqlx::migrate!("migrations/postgres")
            .run(&*self.pool)
            .await
            .map_err(|e| Error::Migration(format!("Migration failed: {}", e)))?;
        tracing::info!("Migrations completed successfully");

        Ok(())
    }

    async fn current_version(&self) -> Result<i64, Error> {
        // Get current database migration version from _sqlx_migrations table
        let current_version: Option<i64> =
            sqlx::query_scalar("SELECT MAX(version) FROM _sqlx_migrations")
                .fetch_one(&*self.pool)
                .await
                .map_err(|err| {
                    Error::DatabaseNotInitialized(format!(
                        "Failed to check migration version: {}",
                        err
                    ))
                })?;

        current_version.ok_or_else(|| {
            Error::DatabaseNotInitialized("No migrations have been applied".to_string())
        })
    }

    async fn latest_version(&self) -> Result<i64, Error> {
        // Check migration version matches available migrations
        let migration_dir = Path::new("migrations/postgres");

        // Read migration files and find the highest numbered migration
        let migration_files = fs::read_dir(migration_dir).map_err(|err| {
            Error::DatabaseNotInitialized(format!("Failed to read migrations directory: {}", err))
        })?;

        let mut max_migration_version: Option<i64> = None;

        for entry in migration_files {
            let entry = entry.map_err(|err| {
                Error::DatabaseNotInitialized(format!("Failed to read migration file: {}", err))
            })?;
            let file_name = entry.file_name();
            let file_name_str = file_name.to_string_lossy();

            // Check if file matches pattern: <digits>_<snake_case_name>.sql
            if file_name_str.ends_with(".sql") {
                let name_without_ext = &file_name_str[..file_name_str.len() - 4];
                if let Some(underscore_pos) = name_without_ext.find('_') {
                    let version_str = &name_without_ext[..underscore_pos];
                    let name_part = &name_without_ext[underscore_pos + 1..];

                    // Check if version is all digits and name is snake_case
                    if version_str.chars().all(|c| c.is_ascii_digit())
                        && name_part
                            .chars()
                            .all(|c| c.is_ascii_lowercase() || c == '_')
                    {
                        if let Ok(version) = version_str.parse::<i64>() {
                            max_migration_version =
                                Some(max_migration_version.unwrap_or(0).max(version));
                        }
                    }
                }
            }
        }
        max_migration_version
            .ok_or_else(|| Error::DatabaseNotInitialized("No migrations found".to_string()))
    }
}
