[package]
name = "udex-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
exclude = ["benches/", "tests/"]

[features]
integration_test = []

[dependencies]
udex-api = { path = "../api" }
udex-datastore = { path = "../datastore"}
tokio = { workspace = true }
tonic = { workspace = true }
tonic-middleware = "0.3.0"
prost = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
uuid = { workspace = true }
jsonwebtoken = { workspace = true }
validator = { version = "0.20", features = ["derive"] }
tokio-rustls = "0.26.2"
time = { workspace = true }
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"], default-features = false }
secrets-rs = "1.0.0"

[[bench]]
name = "entry_service"
harness = false

[dev-dependencies]
udex-datastore = { path = "../datastore", features = ["integration_test"]}
tokio = { workspace = true }
tracing-test = { workspace = true }
tokio-shared-rt = { workspace = true }
tonic = { workspace = true }
maybe-once = { workspace = true }
rstest = { workspace = true }
sqlx = { workspace = true }
mockall = { workspace = true }
rustls = { workspace = true }
criterion = { workspace = true }
tempfile = { workspace = true }
oauth2 = { version = "5", features = ["reqwest"] }
ory-hydra-client = { version = "26.2", default-features = false, features = ["rustls-tls"] }

 