[package]
name = "udex-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[features]
integration_test = []

[dependencies]
udex-api = { path = "../api" }
udex-datastore = { path = "../datastore"}
tokio = { workspace = true }
tonic = { workspace = true }
tonic-middleware = "0.3.0"
prost = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
uuid = { workspace = true }
jsonwebtoken = { workspace = true }
validator = { version = "0.20", features = ["derive"] }
opentelemetry = "0.29.1"
opentelemetry-otlp = "0.29.0"
opentelemetry_sdk = "0.29.0"
tokio-rustls = "0.26.2"
testcontainers = { workspace = true }
testcontainers-modules ={ workspace = true }
tokio-shared-rt = { workspace = true }
time = { workspace = true }

[dev-dependencies]
udex-datastore = { path = "../datastore", features = ["integration_test"]}
tokio = { workspace = true }
tonic = { workspace = true }
maybe-once = { workspace = true } 
rstest = { workspace = true }
sqlx = { workspace = true }
mockall = { workspace = true }
rustls = { workspace = true }

 