#!/bin/bash
RUST_VERSION="${RUST_VERSION:-stable}"
set -e
rustup upgrade "${RUST_VERSION}"
rustup default "${RUST_VERSION}"
rustup component add clippy
rustup component add rustfmt
rustup show

# intent setup
# Verify installation
intent --version
cd /workspace

# moved to last as it seems flakey?
# # Install Claude Code subagent 
# intent claude subagents install intent
# # Install CLaude Code skills
# intent claude skills install in-essentials

# install hydra CLI (pinned release, checksum-verified)
HYDRA_VERSION="v26.2.0"
HYDRA_TARBALL="hydra_26.2.0-linux_64bit.tar.gz"
HYDRA_RELEASE_URL="https://github.com/ory/hydra/releases/download/${HYDRA_VERSION}"

hydra_tmp="$(mktemp -d)"
trap 'rm -rf "${hydra_tmp}"' EXIT

curl -fsSL "${HYDRA_RELEASE_URL}/${HYDRA_TARBALL}" -o "${hydra_tmp}/${HYDRA_TARBALL}"
curl -fsSL "${HYDRA_RELEASE_URL}/checksums.txt"    -o "${hydra_tmp}/checksums.txt"

# Verify SHA-256 against the publisher's pinned release checksums
(cd "${hydra_tmp}" && grep "${HYDRA_TARBALL}" checksums.txt | sha256sum --check --strict --quiet)

tar -xzf "${hydra_tmp}/${HYDRA_TARBALL}" -C "${hydra_tmp}" hydra
sudo mv "${hydra_tmp}/hydra" /usr/local/bin/
hydra help

# ── Developer secret & key setup ──────────────────────────────────────────────
# gen-env.sh prompts when .env exists, so guard it externally and pass --force.
# gen-keys-and-certs.sh skips silently when key material exists; --force rotates.

cd /workspace

# In the devcontainer, Hydra is reachable via the Docker service name rather
# than localhost. Export these so gen-env.sh writes the correct URLs into .env.
export HYDRA_PUBLIC_URL=http://hydra:4444
export HYDRA_ADMIN_URL=http://hydra:4445

if [[ ! -f .env ]]; then
  echo "No .env found — generating dev secrets..."
  bash scripts/gen-env.sh --force
else
  echo ".env already exists — skipping secret generation."
fi

# docker-compose.devcontainer.yml declares env_file: ../.env, which is the
# workspace root. The compose file lives in .devcontainer/, so we symlink
# .devcontainer/.env → ../.env to keep the relative path working without
# duplicating the file. rm -f handles both the missing-link and dangling-link
# cases (dangling link: .env was deleted after a previous post-create run).
rm -f .devcontainer/.env
ln -s ../.env .devcontainer/.env

bash scripts/gen-keys-and-certs.sh

# install claude code — major-version pin; npm verifies package integrity via
# the registry's SHA-512 hash, so no separate checksum step is needed.
npm install -g @anthropic-ai/claude-code@2
claude --version

# see comment above
# Install Claude Code subagent 
intent claude subagents install intent
# Install CLaude Code skills
intent claude skills install in-session
intent claude skills install in-standards
intent claude skills install in-essentials


# kubectl
curl -LO "https://dl.k8s.io/v1.36.1/bin/linux/amd64/kubectl"
chmod +x kubectl
sudo mv kubectl /usr/local/bin/kubectl

# k3d
curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.8.3 bash

# helm
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
chmod 700 get_helm.sh
./get_helm.sh -v v4.0.0
rm get_helm.sh


# ── Observability stack ───────────────────────────────────────────────────────
# Bring up the local observability stack (OTel Collector, Tempo, Prometheus,
# Loki, Grafana, Vector) so it is available by default in the devcontainer. It
# runs as its own compose project attached to this devcontainer's network
# (see projects/observability/scripts/up.sh; certs were generated by
# gen-keys-and-certs.sh above). Grafana: http://localhost:3000.
#
# Application/SDK telemetry export stays opt-in (server config / UDEX_OTLP_ENDPOINT)
# so test runs are unaffected — this only starts the backend components.
#
# Non-fatal: a transient failure (e.g. an image pull hiccup) must not break
# devcontainer creation; re-run the script manually if it does.
bash projects/observability/scripts/up.sh \
  || echo "WARNING: observability stack failed to start; run 'bash projects/observability/scripts/up.sh' manually"


