// Generated by Claude Code (claude-sonnet-4-6)

//! Clap command-line interface types for the `udex` binary.

use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

/// Universal lookup directory CLI.
#[derive(Parser)]
#[command(name = "udex", about = "Universal lookup directory for entities")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,

    /// Udex server URL [env: UDEX_SERVER]
    #[arg(
        long,
        env = "UDEX_SERVER",
        global = true,
        default_value = "https://localhost:50051"
    )]
    pub server: String,

    /// Bearer token for authentication [env: UDEX_TOKEN]
    #[arg(long, env = "UDEX_TOKEN", global = true)]
    pub token: Option<String>,

    /// Path to CA certificate for TLS verification [env: UDEX_CA_CERT]
    #[arg(long, env = "UDEX_CA_CERT", global = true)]
    pub ca_cert: Option<PathBuf>,

    /// Output format
    #[arg(long, global = true, default_value = "table", value_enum)]
    pub output: OutputFormat,

    /// Enable verbose tracing output
    #[arg(long, global = true)]
    pub verbose: bool,
}

/// Output format for commands that return data.
#[derive(ValueEnum, Clone, Default, Debug)]
pub enum OutputFormat {
    #[default]
    Table,
    Json,
    Yaml,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Start the Udex gRPC server in the foreground
    Serve(ServeArgs),
    /// Manage server configuration
    Config {
        #[command(subcommand)]
        command: ConfigCommands,
    },
    /// Manage indices
    Index {
        #[command(subcommand)]
        command: IndexCommands,
    },
    /// Manage entries
    Entry {
        #[command(subcommand)]
        command: EntryCommands,
    },
    /// Token utilities (offline)
    Token {
        #[command(subcommand)]
        command: TokenCommands,
    },
    /// Context utilities (offline)
    Context {
        #[command(subcommand)]
        command: ContextCommands,
    },
}

// --- serve ---

/// Arguments for `udex serve`.
#[derive(Parser)]
pub struct ServeArgs {
    /// Path to configuration file [env: UDEX_CONFIG]
    #[arg(long, env = "UDEX_CONFIG", default_value = "udex.toml")]
    pub config: PathBuf,
}

// --- config ---

#[derive(Subcommand)]
pub enum ConfigCommands {
    /// Generate a default configuration file
    Init(ConfigInitArgs),
    /// Validate an existing configuration file
    Validate(ConfigValidateArgs),
}

/// Arguments for `udex config init`.
#[derive(Parser)]
pub struct ConfigInitArgs {
    /// Path to write the configuration file
    #[arg(long, default_value = "udex.toml")]
    pub output: PathBuf,
}

/// Arguments for `udex config validate`.
#[derive(Parser)]
pub struct ConfigValidateArgs {
    /// Path to configuration file [env: UDEX_CONFIG]
    #[arg(long, env = "UDEX_CONFIG", default_value = "udex.toml")]
    pub config: PathBuf,
}

// --- index ---

#[derive(Subcommand)]
pub enum IndexCommands {
    /// List all indices
    List,
    /// Create a new index
    Create(IndexCreateArgs),
    /// Get an index by name
    Get(IndexGetArgs),
    /// Update an existing index
    Update(IndexUpdateArgs),
    /// Delete an index
    Delete(IndexDeleteArgs),
}

/// Arguments for `udex index create`.
#[derive(Parser)]
pub struct IndexCreateArgs {
    /// Index name
    pub name: String,
    /// Human-readable description
    #[arg(long)]
    pub description: Option<String>,
    /// Maximum number of bulk operations per request
    #[arg(long)]
    pub bulk_limit: Option<u32>,
}

/// Arguments for `udex index get`.
#[derive(Parser)]
pub struct IndexGetArgs {
    /// Index name
    pub name: String,
}

/// Arguments for `udex index update`.
#[derive(Parser)]
pub struct IndexUpdateArgs {
    /// Index name
    pub name: String,
    /// Human-readable description
    #[arg(long)]
    pub description: Option<String>,
    /// Maximum number of bulk operations per request
    #[arg(long)]
    pub bulk_limit: Option<u32>,
}

/// Arguments for `udex index delete`.
#[derive(Parser)]
pub struct IndexDeleteArgs {
    /// Index name
    pub name: String,
}

// --- entry ---

#[derive(Subcommand)]
pub enum EntryCommands {
    /// Create a new entry
    Create(EntryCreateArgs),
    /// Get an entry by key
    Get(EntryGetArgs),
    /// Reverse-lookup entries by context
    Lookup(EntryLookupArgs),
    /// Delete an entry by key
    Delete(EntryDeleteArgs),
}

/// Arguments for `udex entry create`.
#[derive(Parser)]
pub struct EntryCreateArgs {
    /// Index name
    pub index: String,
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}

/// Arguments for `udex entry get`.
#[derive(Parser)]
pub struct EntryGetArgs {
    /// Index name
    pub index: String,
    /// Entry key (UUID)
    #[arg(long)]
    pub key: String,
}

/// Arguments for `udex entry lookup`.
#[derive(Parser)]
pub struct EntryLookupArgs {
    /// Index name
    pub index: String,
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}

/// Arguments for `udex entry delete`.
#[derive(Parser)]
pub struct EntryDeleteArgs {
    /// Index name
    pub index: String,
    /// Entry key (UUID)
    #[arg(long)]
    pub key: String,
}

// --- token ---

#[derive(Subcommand)]
pub enum TokenCommands {
    /// Decode and display a JWT without signature verification
    Inspect(TokenInspectArgs),
}

/// Arguments for `udex token inspect`.
#[derive(Parser)]
pub struct TokenInspectArgs {
    /// JWT to inspect
    pub token: String,
}

// --- context ---

#[derive(Subcommand)]
pub enum ContextCommands {
    /// Compute the hash of a context
    Hash(ContextHashArgs),
}

/// Arguments for `udex context hash`.
#[derive(Parser)]
pub struct ContextHashArgs {
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}
