// Generated by Claude Code (claude-sonnet-4-6)

//! Clap command-line interface types for the `udex` binary.

use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

/// Universal lookup directory CLI.
#[derive(Parser)]
#[command(
    name = "udex",
    about = "Universal lookup directory for entities",
    after_help = "EXIT CODES\n  0  success\n  1  internal error\n  2  not found\n  3  already exists\n  4  invalid input\n  5  unauthenticated\n  6  permission denied\n  7  server unavailable / timeout\n  8  transport failure (connection refused, TLS, DNS)"
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,

    /// Udex server URL [env: UDEX_SERVER]
    #[arg(
        long,
        env = "UDEX_SERVER",
        global = true,
        default_value = "https://localhost:50051"
    )]
    pub server: String,

    /// Path to CA certificate for TLS verification [env: UDEX_CA_CERT]
    #[arg(long, env = "UDEX_CA_CERT", global = true)]
    pub ca_cert: Option<PathBuf>,

    /// Output format
    #[arg(long, global = true, default_value = "table", value_enum)]
    pub output: OutputFormat,

    /// Enable verbose tracing output
    #[arg(long, global = true)]
    pub verbose: bool,
}

/// Output format for commands that return data.
#[derive(ValueEnum, Clone, Default, Debug)]
pub enum OutputFormat {
    #[default]
    Table,
    Json,
    Yaml,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Start the Udex gRPC server in the foreground
    Serve(ServeArgs),
    /// Manage server configuration
    Config {
        #[command(subcommand)]
        command: ConfigCommands,
    },
    /// Manage indices
    Index {
        #[command(subcommand)]
        command: IndexCommands,
    },
    /// Manage entries
    Entry {
        #[command(subcommand)]
        command: EntryCommands,
    },
    /// Token utilities (offline)
    Token {
        #[command(subcommand)]
        command: TokenCommands,
    },
    /// Context utilities (offline)
    Context {
        #[command(subcommand)]
        command: ContextCommands,
    },
    /// Manage database migrations
    Migrate {
        #[command(subcommand)]
        command: MigrateCommands,
    },
}

// --- serve ---

/// Arguments for `udex serve`.
#[derive(Parser)]
pub struct ServeArgs {
    /// Path to configuration file [env: UDEX_CONFIG]
    #[arg(long, env = "UDEX_CONFIG", default_value = "udex.toml")]
    pub config: PathBuf,
}

// --- config ---

#[derive(Subcommand)]
pub enum ConfigCommands {
    /// Generate a default configuration file
    Init(ConfigInitArgs),
    /// Validate an existing configuration file
    Validate(ConfigValidateArgs),
}

/// Arguments for `udex config init`.
#[derive(Parser)]
pub struct ConfigInitArgs {
    /// Path to write the configuration file
    #[arg(long, default_value = "udex.toml")]
    pub path: PathBuf,
}

/// Arguments for `udex config validate`.
#[derive(Parser)]
pub struct ConfigValidateArgs {
    /// Path to configuration file [env: UDEX_CONFIG]
    #[arg(long, env = "UDEX_CONFIG", default_value = "udex.toml")]
    pub config: PathBuf,
}

// --- index ---

#[derive(Subcommand)]
pub enum IndexCommands {
    /// List all indices
    List,
    /// Create a new index
    Create(IndexCreateArgs),
    /// Get an index by name
    Get(IndexGetArgs),
    /// Update an existing index
    Update(IndexUpdateArgs),
    /// Delete an index (requires the index to have no entries)
    Delete(IndexDeleteArgs),
}

/// Arguments for `udex index create`.
#[derive(Parser)]
pub struct IndexCreateArgs {
    /// Index name
    pub name: String,
    /// Short human-readable label for UI use
    #[arg(long)]
    pub display_name: Option<String>,
    /// Human-readable description
    #[arg(long)]
    pub description: Option<String>,
    /// Maximum number of bulk operations per request [default: 100]
    #[arg(long, default_value = "100")]
    pub bulk_limit: u32,
    /// Maximum key length in bytes [default: 256]
    #[arg(long, default_value = "256")]
    pub max_key_length: u32,
    /// Maximum value length in bytes [default: 1024]
    #[arg(long, default_value = "1024")]
    pub max_value_length: u32,
    /// Maximum number of key-value pairs per context [default: 32]
    #[arg(long, default_value = "32")]
    pub max_context_pairs: u32,
}

/// Arguments for `udex index get`.
#[derive(Parser)]
pub struct IndexGetArgs {
    /// Index name
    pub name: String,
}

/// Arguments for `udex index update`.
#[derive(Parser)]
pub struct IndexUpdateArgs {
    /// Index name
    pub name: String,
    /// Human-readable description
    #[arg(long)]
    pub description: Option<String>,
    /// Maximum number of bulk operations per request
    #[arg(long)]
    pub bulk_limit: Option<u32>,
}

/// Arguments for `udex index delete`.
#[derive(Parser)]
pub struct IndexDeleteArgs {
    /// Index name
    pub name: String,
}

// --- entry ---

#[derive(Subcommand)]
pub enum EntryCommands {
    /// Create a new entry
    Create(EntryCreateArgs),
    /// Get an entry by key
    Get(EntryGetArgs),
    /// Reverse-lookup entries by context
    Lookup(EntryLookupArgs),
    /// Look up the key for a context, creating the entry if it does not exist
    LookupOrCreate(EntryLookupOrCreateArgs),
    /// Delete an entry by key
    Delete(EntryDeleteArgs),
}

/// Arguments for `udex entry create`.
#[derive(Parser)]
pub struct EntryCreateArgs {
    /// Index name
    pub index: String,
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}

/// Arguments for `udex entry get`.
#[derive(Parser)]
pub struct EntryGetArgs {
    /// Index name
    pub index: String,
    /// Entry key (UUID)
    #[arg(long)]
    pub key: String,
}

/// Arguments for `udex entry lookup`.
#[derive(Parser)]
pub struct EntryLookupArgs {
    /// Index name
    pub index: String,
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}

/// Arguments for `udex entry lookup-or-create`.
#[derive(Parser)]
pub struct EntryLookupOrCreateArgs {
    /// Index name
    pub index: String,
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}

/// Arguments for `udex entry delete`.
#[derive(Parser)]
pub struct EntryDeleteArgs {
    /// Index name
    pub index: String,
    /// Entry key (UUID)
    #[arg(long)]
    pub key: String,
}

// --- token ---

#[derive(Subcommand)]
pub enum TokenCommands {
    /// Decode and display a JWT without signature verification
    Inspect(TokenInspectArgs),
    /// Fetch a token from an OAuth2 server using client credentials
    Fetch(TokenFetchArgs),
}

/// Arguments for `udex token inspect`.
#[derive(Parser)]
pub struct TokenInspectArgs {
    /// JWT to inspect
    pub token: String,
}

/// Arguments for `udex token fetch`.
///
/// `UDEX_CLIENT_ID` and `UDEX_CLIENT_SECRET` are read exclusively from the
/// environment to avoid leaking credentials via process listings.
#[derive(Parser)]
pub struct TokenFetchArgs {
    /// Full token endpoint URL (e.g. http://localhost:4444/oauth2/token) [env: UDEX_TOKEN_URL]
    #[arg(long, env = "UDEX_TOKEN_URL")]
    pub url: String,
    /// Scopes to request (may be repeated)
    #[arg(long = "scope", value_name = "SCOPE")]
    pub scopes: Vec<String>,
    /// Audience to request in the token (e.g. the server's configured jwt_audience) [env: UDEX_TOKEN_AUDIENCE]
    #[arg(long, env = "UDEX_TOKEN_AUDIENCE")]
    pub audience: Option<String>,
}

// --- context ---

#[derive(Subcommand)]
pub enum ContextCommands {
    /// Compute the hash of a context
    Hash(ContextHashArgs),
}

/// Arguments for `udex context hash`.
#[derive(Parser)]
pub struct ContextHashArgs {
    /// Context key=value pairs (may be repeated)
    #[arg(long = "context", value_name = "KEY=VALUE")]
    pub context: Vec<String>,
}

// --- migrate ---

#[derive(Subcommand)]
pub enum MigrateCommands {
    /// Check whether the database schema is at the expected version
    Check(MigrateArgs),
    /// Apply all outstanding database migrations
    Apply(MigrateArgs),
}

/// Shared arguments for `udex migrate` subcommands.
#[derive(Parser)]
pub struct MigrateArgs {
    /// Path to configuration file [env: UDEX_CONFIG]
    #[arg(long, env = "UDEX_CONFIG", default_value = "udex.toml")]
    pub config: PathBuf,
}
