// Generated by Claude Code (claude-sonnet-4-6)

//! gRPC channel and interceptor helpers shared by all client commands.
//!
//! Usage:
//! ```ignore
//! let client_cfg = ClientConfig::from_cli(&cli);
//! let channel = client_cfg.channel().await?;
//! let client = IndexServiceClient::with_interceptor(channel, client_cfg.interceptor());
//! ```

use std::path::PathBuf;

use anyhow::{Context, Result};
use tonic::metadata::MetadataValue;
use tonic::transport::{Certificate, Channel, ClientTlsConfig};
use tonic::{Request, Status};

use crate::cli::Cli;

/// Connection parameters extracted from the global CLI flags.
#[derive(Clone)]
pub struct ClientConfig {
    /// gRPC server URL (e.g. `https://localhost:50051`)
    pub server: String,
    /// Bearer token for `Authorization` header, if any.
    pub token: Option<String>,
    /// Path to a custom CA certificate PEM file for TLS verification, if any.
    pub ca_cert: Option<PathBuf>,
}

impl ClientConfig {
    pub fn from_cli(cli: &Cli) -> Self {
        ClientConfig {
            server: cli.server.clone(),
            token: std::env::var("UDEX_TOKEN").ok(),
            ca_cert: cli.ca_cert.clone(),
        }
    }

    /// Build a `tonic::Channel` to `self.server`.
    ///
    /// If `ca_cert` is set, the given PEM is used as the trust anchor.
    /// Otherwise the system trust store is used.
    pub async fn channel(&self) -> Result<Channel> {
        let tls = match &self.ca_cert {
            Some(path) => {
                let pem = tokio::fs::read_to_string(path).await.with_context(|| {
                    format!("failed to read CA certificate: {}", path.display())
                })?;
                ClientTlsConfig::new().ca_certificate(Certificate::from_pem(pem))
            }
            None => ClientTlsConfig::new(),
        };

        Channel::from_shared(self.server.clone())
            .context("invalid server URL")?
            .tls_config(tls)
            .context("TLS configuration error")?
            .connect()
            .await
            .with_context(|| format!("failed to connect to {}", self.server))
    }

    #[allow(clippy::result_large_err)] // tonic::Status is large; interceptor signature is fixed by tonic
    /// Returns an interceptor that injects `Authorization: Bearer <token>` when a token is set.
    pub fn interceptor(
        &self,
    ) -> impl Fn(Request<()>) -> Result<Request<()>, Status> + Clone + use<> {
        let token = self.token.clone();
        move |mut req: Request<()>| {
            if let Some(t) = &token {
                let val: MetadataValue<_> = format!("Bearer {t}")
                    .parse()
                    .map_err(|_| Status::internal("invalid bearer token"))?;
                req.metadata_mut().insert("authorization", val);
            }
            Ok(req)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tonic::Request;

    fn config_with_token(token: &str) -> ClientConfig {
        ClientConfig {
            server: "https://localhost:50051".to_string(),
            token: Some(token.to_string()),
            ca_cert: None,
        }
    }

    fn config_no_token() -> ClientConfig {
        ClientConfig {
            server: "https://localhost:50051".to_string(),
            token: None,
            ca_cert: None,
        }
    }

    #[test]
    fn interceptor_injects_bearer_header() {
        let cfg = config_with_token("my-secret-token");
        let interceptor = cfg.interceptor();
        let req = interceptor(Request::new(())).unwrap();
        let auth = req.metadata().get("authorization").unwrap();
        assert_eq!(auth, "Bearer my-secret-token");
    }

    #[test]
    fn interceptor_no_token_leaves_headers_empty() {
        let cfg = config_no_token();
        let interceptor = cfg.interceptor();
        let req = interceptor(Request::new(())).unwrap();
        assert!(req.metadata().get("authorization").is_none());
    }

    #[tokio::test]
    async fn channel_fails_on_invalid_url() {
        let cfg = ClientConfig {
            server: "not a url !!!".to_string(),
            token: None,
            ca_cert: None,
        };
        let err = cfg.channel().await.unwrap_err();
        assert!(
            err.to_string().contains("invalid server URL"),
            "unexpected error: {err}"
        );
    }

    #[tokio::test]
    async fn channel_fails_on_missing_ca_cert() {
        let cfg = ClientConfig {
            server: "https://localhost:50051".to_string(),
            token: None,
            ca_cert: Some(PathBuf::from("/nonexistent/ca.pem")),
        };
        let err = cfg.channel().await.unwrap_err();
        assert!(
            err.to_string().contains("failed to read CA certificate"),
            "unexpected error: {err}"
        );
    }
}
