// Generated by Claude Code (claude-sonnet-4-6)

//! TOML configuration types for the `udex` CLI.
//!
//! Defines a TOML-friendly representation of the Udex server configuration.
//! `std::time::Duration` and proto-generated types are replaced with primitive
//! equivalents (durations as seconds) to produce readable TOML output.
//!
//! Use [`UdexConfig::default`] as the basis for `udex config init`, and
//! [`UdexConfig::validate`] to check a loaded config before starting the server.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Top-level Udex configuration, covering the server and datastore.
#[derive(Debug, Serialize, Deserialize)]
pub struct UdexConfig {
    pub server: ServerConfig,
    pub datastore: DatastoreConfig,
}

/// gRPC server configuration.
#[derive(Debug, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Address and port to bind the gRPC server (e.g. "0.0.0.0:50051")
    pub bind_address: String,
    /// Request timeout in seconds
    pub request_timeout_secs: u64,
    /// Maximum number of concurrent connections
    pub max_connections: u32,
    /// Maximum message size in bytes
    pub max_message_size_bytes: usize,
    pub tls: TlsConfig,
    pub authnz: AuthNzConfig,
}

/// TLS certificate configuration.
#[derive(Debug, Serialize, Deserialize)]
pub struct TlsConfig {
    /// Path to the server TLS certificate (PEM)
    pub cert_path: String,
    /// Path to the server TLS private key (PEM)
    pub key_path: String,
}

/// Authentication and authorisation configuration.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct AuthNzConfig {
    /// JWKS endpoint for token validation — either this or jwt_public_key_path must be set
    pub jwks_url: Option<String>,
    /// Path to the JWT public key for token validation (ECDSA PEM)
    pub jwt_public_key_path: Option<String>,
    /// Expected JWT issuer claim
    pub jwt_issuer: Option<String>,
    /// Expected JWT audience claim
    pub jwt_audience: Option<String>,
}

/// PostgreSQL datastore configuration.
#[derive(Debug, Serialize, Deserialize)]
pub struct DatastoreConfig {
    /// PostgreSQL connection URL; supports `${VAR}` placeholders resolved from env
    pub connection_url: String,
    /// Maximum number of connections in the pool
    pub max_connections: u32,
    /// Minimum number of connections in the pool
    pub min_connections: u32,
    /// Connection timeout in seconds
    pub connection_timeout_secs: u64,
    /// Query timeout in seconds
    pub query_timeout_secs: u64,
    /// Disable TLS enforcement on the connection URL. MUST NOT be set in production.
    #[serde(default)]
    pub dangerous_allow_non_tls: bool,
}

impl Default for UdexConfig {
    fn default() -> Self {
        Self {
            server: ServerConfig {
                bind_address: "127.0.0.1:50051".to_string(),
                request_timeout_secs: 30,
                max_connections: 1000,
                max_message_size_bytes: 4 * 1024 * 1024,
                tls: TlsConfig {
                    cert_path: "certs/server.crt".to_string(),
                    key_path: "certs/server.key".to_string(),
                },
                authnz: AuthNzConfig {
                    jwks_url: None,
                    jwt_public_key_path: Some("certs/jwt_public_key.pem".to_string()),
                    jwt_issuer: Some("https://auth.example.com".to_string()),
                    jwt_audience: Some("udex".to_string()),
                },
            },
            datastore: DatastoreConfig {
                connection_url:
                    "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
                        .to_string(),
                max_connections: 10,
                min_connections: 1,
                connection_timeout_secs: 10,
                query_timeout_secs: 30,
                dangerous_allow_non_tls: false,
            },
        }
    }
}

impl UdexConfig {
    /// Load a [`UdexConfig`] from a TOML file.
    pub fn load(path: &std::path::Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read config file: {}", path.display()))?;
        toml::from_str(&content)
            .with_context(|| format!("failed to parse config file: {}", path.display()))
    }

    /// Validate the configuration, returning a list of human-readable errors.
    ///
    /// Returns `Ok(())` if the configuration is valid, or an error describing
    /// all validation failures.
    pub fn validate(&self) -> Result<()> {
        let mut errors: Vec<String> = Vec::new();

        // server
        if self
            .server
            .bind_address
            .parse::<std::net::SocketAddr>()
            .is_err()
        {
            errors.push(format!(
                "invalid bind_address {:?}: must be a valid socket address (e.g. \"0.0.0.0:50051\")",
                self.server.bind_address
            ));
        }

        // datastore
        if self.datastore.connection_url.trim().is_empty() {
            errors.push("datastore.connection_url must not be empty".to_string());
        }
        if self.datastore.max_connections == 0 {
            errors.push("datastore.max_connections must be greater than 0".to_string());
        }
        if self.datastore.min_connections > self.datastore.max_connections {
            errors.push(
                "datastore.min_connections must not exceed datastore.max_connections".to_string(),
            );
        }

        // authnz
        let jwt_key = self
            .server
            .authnz
            .jwt_public_key_path
            .as_deref()
            .unwrap_or("")
            .trim();
        let jwt_issuer = self
            .server
            .authnz
            .jwt_issuer
            .as_deref()
            .unwrap_or("")
            .trim();
        let jwt_audience = self
            .server
            .authnz
            .jwt_audience
            .as_deref()
            .unwrap_or("")
            .trim();

        if jwt_key.is_empty() {
            errors.push("server.authnz.jwt_public_key_path is required".to_string());
        }
        if jwt_issuer.is_empty() {
            errors.push("server.authnz.jwt_issuer is required".to_string());
        } else if jwt_issuer.len() > 255 {
            errors.push("server.authnz.jwt_issuer must be 255 characters or fewer".to_string());
        }
        if jwt_audience.is_empty() {
            errors.push("server.authnz.jwt_audience is required".to_string());
        } else if jwt_audience.len() > 255 {
            errors.push("server.authnz.jwt_audience must be 255 characters or fewer".to_string());
        }
        if !jwt_issuer.is_empty() && !jwt_audience.is_empty() && jwt_issuer == jwt_audience {
            errors.push(
                "server.authnz.jwt_issuer and server.authnz.jwt_audience must be different"
                    .to_string(),
            );
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(anyhow::anyhow!(
                "configuration is invalid:\n  - {}",
                errors.join("\n  - ")
            ))
        }
    }

    /// Convert to the server's [`udex_server::config::ServerConfig`].
    ///
    /// `init_indexes` is always empty — indices are created at runtime via
    /// `udex index create` rather than being statically configured.
    pub fn to_server_config(&self) -> Result<udex_server::config::ServerConfig> {
        let bind_address = self
            .server
            .bind_address
            .parse()
            .with_context(|| format!("invalid bind_address: {}", self.server.bind_address))?;

        Ok(udex_server::config::ServerConfig {
            bind_address,
            request_timeout: std::time::Duration::from_secs(self.server.request_timeout_secs),
            max_connections: self.server.max_connections,
            max_message_size: self.server.max_message_size_bytes,
            tls: udex_server::config::TlsConfig {
                cert_path: self.server.tls.cert_path.clone(),
                key_path: self.server.tls.key_path.clone(),
            },
            authnz: udex_server::config::AuthNzConfig {
                jwks_url: self.server.authnz.jwks_url.clone(),
                jwt_public_key_path: self.server.authnz.jwt_public_key_path.clone(),
                jwt_issuer: self.server.authnz.jwt_issuer.clone(),
                jwt_audience: self.server.authnz.jwt_audience.clone(),
            },
            init_indexes: vec![],
        })
    }

    /// Convert to the datastore's [`udex_datastore::config::DatastoreConfig`].
    pub fn to_datastore_config(&self) -> udex_datastore::config::DatastoreConfig {
        udex_datastore::config::DatastoreConfig {
            connection_url: self.datastore.connection_url.clone(),
            max_connections: self.datastore.max_connections,
            min_connections: self.datastore.min_connections,
            connection_timeout: std::time::Duration::from_secs(
                self.datastore.connection_timeout_secs,
            ),
            query_timeout: std::time::Duration::from_secs(self.datastore.query_timeout_secs),
            dangerous_allow_non_tls: self.datastore.dangerous_allow_non_tls,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config_is_valid() {
        UdexConfig::default()
            .validate()
            .expect("default config should be valid");
    }

    #[test]
    fn test_invalid_bind_address_is_invalid() {
        let mut cfg = UdexConfig::default();
        cfg.server.bind_address = "not-an-address".to_string();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn test_empty_connection_url_is_invalid() {
        let mut cfg = UdexConfig::default();
        cfg.datastore.connection_url = String::new();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn test_min_connections_exceeds_max_is_invalid() {
        let mut cfg = UdexConfig::default();
        cfg.datastore.min_connections = 20;
        cfg.datastore.max_connections = 5;
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn test_missing_jwt_key_is_invalid() {
        let mut cfg = UdexConfig::default();
        cfg.server.authnz.jwt_public_key_path = None;
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn test_identical_issuer_and_audience_is_invalid() {
        let mut cfg = UdexConfig::default();
        cfg.server.authnz.jwt_issuer = Some("same".to_string());
        cfg.server.authnz.jwt_audience = Some("same".to_string());
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn test_roundtrip_toml_serialization() {
        let cfg = UdexConfig::default();
        let toml_str = toml::to_string_pretty(&cfg).expect("serialization should succeed");
        let restored: UdexConfig =
            toml::from_str(&toml_str).expect("deserialization should succeed");
        assert_eq!(cfg.server.bind_address, restored.server.bind_address);
        assert_eq!(
            cfg.datastore.connection_url,
            restored.datastore.connection_url
        );
    }
}
