// Generated by Claude Code (claude-sonnet-4-6)

//! Udex CLI — `udex` binary entry point.

mod cli;
mod client;
mod commands;
mod config;

use clap::Parser;

use cli::{
    Cli, Commands, ConfigCommands, ContextCommands, EntryCommands, IndexCommands, TokenCommands,
};
use client::ClientConfig;

#[tokio::main]
async fn main() {
    // Install the rustls crypto provider before any TLS connections are made.
    rustls::crypto::aws_lc_rs::default_provider()
        .install_default()
        .expect("failed to install rustls CryptoProvider");

    let cli = Cli::parse();

    // If --verbose is set and RUST_LOG is not already configured, default to debug.
    if cli.verbose && std::env::var("RUST_LOG").is_err() {
        unsafe { std::env::set_var("RUST_LOG", "debug") };
    }

    let result = run(cli).await;

    if let Err(e) = result {
        eprintln!("error: {e:#}");
        std::process::exit(1);
    }
}

async fn run(cli: Cli) -> anyhow::Result<()> {
    let client_cfg = ClientConfig::from_cli(&cli);

    match cli.command {
        Commands::Serve(args) => commands::serve::run(args).await,

        Commands::Config { command } => match command {
            ConfigCommands::Init(args) => commands::config::init(args),
            ConfigCommands::Validate(args) => commands::config::validate(args),
        },

        Commands::Index { command } => match command {
            IndexCommands::List => commands::index::list(client_cfg, &cli.output).await,
            IndexCommands::Create(args) => {
                commands::index::create(client_cfg, args, &cli.output).await
            }
            IndexCommands::Get(args) => commands::index::get(client_cfg, args, &cli.output).await,
            IndexCommands::Update(args) => {
                commands::index::update(client_cfg, args, &cli.output).await
            }
            IndexCommands::Delete(args) => commands::index::delete(client_cfg, args).await,
        },

        Commands::Entry { command } => match command {
            EntryCommands::Create(args) => {
                commands::entry::create(client_cfg, args, &cli.output).await
            }
            EntryCommands::Get(args) => commands::entry::get(client_cfg, args, &cli.output).await,
            EntryCommands::Lookup(args) => {
                commands::entry::lookup(client_cfg, args, &cli.output).await
            }
            EntryCommands::Delete(args) => commands::entry::delete(client_cfg, args).await,
        },

        Commands::Token { command } => match command {
            TokenCommands::Inspect(args) => commands::token::inspect(args),
        },

        Commands::Context { command } => match command {
            ContextCommands::Hash(args) => commands::context::hash(args),
        },
    }
}
