// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains configuration structures for the Udex server.

use serde::{Deserialize, Serialize};
use std::net::SocketAddr;
use std::time::Duration;

/// Server-related configuration for gRPC.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Address to bind the gRPC server
    pub bind_address: SocketAddr,
    /// Request timeout duration
    pub request_timeout: Duration,
    /// Maximum concurrent connections
    pub max_connections: u32,
    /// Maximum message size in bytes
    pub max_message_size: usize,
    /// TLS configuration
    pub tls: TlsConfig,
    /// AuthNZ configuration
    pub authnz: AuthNzConfig,
    /// statically defined indexes
    pub init_indexes: Vec<udex_api::index::UpdateIndexRequest>,
}

/// TLS configuration for the gRPC server.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TlsConfig {
    /// Path to the server certificate
    pub cert_path: String,
    /// Path to the server private key
    pub key_path: String,
    /// Path to the CA certificate
    pub ca_cert_path: String,
}

// Authentication and Authorization configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthNzConfig {
    /// JWT public key path for token validation (ECDSA public key in PEM format)
    pub jwt_public_key_path: Option<String>,
    /// JWT issuer for token validation
    pub jwt_issuer: Option<String>,
    /// JWT audience for token validation
    pub jwt_audience: Option<String>,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            bind_address: "127.0.0.1:50051".parse().unwrap(),
            request_timeout: Duration::from_secs(30),
            max_connections: 1000,
            max_message_size: 4 * 1024 * 1024, // 4MB
            tls: TlsConfig::default(),
            init_indexes: Vec::new(),
            authnz: AuthNzConfig::default(),
        }
    }
}

impl ServerConfig {
    /// Validate the server configuration.
    pub fn validate(&self) -> Result<(), crate::Error> {
        // if self.bind_address.ip().is_unspecified() {
        //     return Err(ConfigError::Validation("bind_address cannot be unspecified".to_string()));
        // }
        //validate the authnz configuration
        // Validate the AuthNZ configuration
        self.authnz.validate()?;

        Ok(())
    }
}

impl Default for TlsConfig {
    fn default() -> Self {
        Self {
            cert_path: "certs/server.crt".to_string(),
            key_path: "certs/server.key".to_string(),
            ca_cert_path: "certs/ca.crt".to_string(),
        }
    }
}

impl Default for AuthNzConfig {
    fn default() -> Self {
        Self {
            jwt_public_key_path: None,
            jwt_issuer: None,
            jwt_audience: None,
        }
    }
}

impl AuthNzConfig {
    // Validate the AuthNZ configuration.
    pub fn validate(&self) -> Result<(), crate::Error> {
        // Validate JWT configuration if any JWT field is
        // If any JWT field is provided, all must be provided
        let jwt_public_key_path = self.jwt_public_key_path.as_ref().ok_or_else(|| {
            crate::Error::ConfigValidation(
                "jwt_public_key_path is required when using JWT authentication".to_string(),
            )
        })?;
        let jwt_issuer = self.jwt_issuer.as_ref().ok_or_else(|| {
            crate::Error::ConfigValidation(
                "jwt_issuer is required when using JWT authentication".to_string(),
            )
        })?;
        let jwt_audience = self.jwt_audience.as_ref().ok_or_else(|| {
            crate::Error::ConfigValidation(
                "jwt_audience is required when using JWT authentication".to_string(),
            )
        })?;

        // Validate JWT public key path
        if jwt_public_key_path.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "jwt_public_key_path cannot be empty".to_string(),
            ));
        }


        // Validate JWT issuer
        if jwt_issuer.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "jwt_issuer cannot be empty".to_string(),
            ));
        }
        if jwt_issuer.len() > 255 {
            return Err(crate::Error::ConfigValidation(
                "jwt_issuer must be no more than 255 characters long".to_string(),
            ));
        }

        // Validate JWT audience
        if jwt_audience.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "jwt_audience cannot be empty".to_string(),
            ));
        }
        if jwt_audience.len() > 255 {
            return Err(crate::Error::ConfigValidation(
                "jwt_audience must be no more than 255 characters long".to_string(),
            ));
        }

        // Validate issuer and audience are different (best practice)
        if jwt_issuer == jwt_audience {
            return Err(crate::Error::ConfigValidation(
                "jwt_issuer and jwt_audience should be different values".to_string(),
            ));
        }

        Ok(())
    }
}
