// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains configuration structures for the Udex server.

use serde::{Deserialize, Serialize};
use std::net::SocketAddr;
use std::time::Duration;
use url::{Url, ParseError};

/// Server-related configuration for gRPC.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Address to bind the gRPC server
    pub bind_address: SocketAddr,
    /// Request timeout duration
    pub request_timeout: Duration,
    /// Maximum concurrent connections
    pub max_connections: u32,
    /// Maximum message size in bytes
    pub max_message_size: usize,
    /// TLS configuration
    pub tls: TlsConfig,
    /// AuthNZ configuration
    pub authnz: AuthNzConfig,
    /// statically defined indexes
    pub init_indexes: Vec<udex_api::index::UpdateIndexRequest>,
}

/// TLS configuration for the gRPC server.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TlsConfig {
    /// Path to the server certificate
    pub cert_path: String,
    /// Path to the server private key
    pub key_path: String,
}

// Authentication and Authorization configuration.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AuthNzConfig {
    /// JWT public key path for token validation (ECDSA public key in PEM format) - either this or jwks url must be provided
    pub jwt_public_key_path: Option<String>,
    /// JWKS endpoint for public key for token validation - - either this or jwt public key path must be provided
    pub jwks_url: Option<String>,
    /// JWT issuer for token validation
    pub jwt_issuer: Option<String>,
    /// JWT audience for token validation
    pub jwt_audience: Option<String>,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            bind_address: "127.0.0.1:50051"
                .parse()
                .expect("hardcoded default bind address is always valid"),
            request_timeout: Duration::from_secs(30),
            max_connections: 1000,
            max_message_size: 4 * 1024 * 1024, // 4MB
            tls: TlsConfig::default(),
            init_indexes: Vec::new(),
            authnz: AuthNzConfig::default(),
        }
    }
}

impl ServerConfig {
    /// Validate the server configuration.
    pub fn validate(&self) -> Result<(), crate::Error> {
        self.tls.validate()?;
        self.authnz.validate()?;
        Ok(())
    }
}

impl TlsConfig {
    pub fn validate(&self) -> Result<(), crate::Error> {
        if self.cert_path.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "tls.cert_path must not be empty".to_string(),
            ));
        }
        if self.key_path.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "tls.key_path must not be empty".to_string(),
            ));
        }
        validate_tls_file("tls.cert_path", &self.cert_path)?;
        validate_tls_file("tls.key_path", &self.key_path)?;
        Ok(())
    }
}

fn validate_tls_file(label: &str, path: &str) -> Result<(), crate::Error> {
    let meta = std::fs::metadata(path)
        .map_err(|e| crate::Error::ConfigValidation(format!("{label} {path:?}: {e}")))?;
    if !meta.is_file() {
        return Err(crate::Error::ConfigValidation(format!(
            "{label} {path:?} is not a regular file"
        )));
    }
    std::fs::File::open(path).map_err(|e| {
        crate::Error::ConfigValidation(format!("{label} {path:?} is not readable: {e}"))
    })?;
    Ok(())
}

impl Default for TlsConfig {
    fn default() -> Self {
        Self {
            cert_path: "certs/server.crt".to_string(),
            key_path: "certs/server.key".to_string(),
        }
    }
}

impl AuthNzConfig {
    // Validate the AuthNZ configuration.
    pub fn validate(&self) -> Result<(), crate::Error> {
        // Validate JWT configuration if any JWT field is
        // If any JWT field is provided, all must be provided
        let jwt_public_key_path = self.jwt_public_key_path.as_ref().ok_or_else(|| {
            crate::Error::ConfigValidation(
                "jwt_public_key_path is required when using JWT authentication".to_string(),
            )
        })?;
        let jwt_issuer = self.jwt_issuer.as_ref().ok_or_else(|| {
            crate::Error::ConfigValidation(
                "jwt_issuer is required when using JWT authentication".to_string(),
            )
        })?;
        let jwt_audience = self.jwt_audience.as_ref().ok_or_else(|| {
            crate::Error::ConfigValidation(
                "jwt_audience is required when using JWT authentication".to_string(),
            )
        })?;

        // Validate JWT public key path
        if jwt_public_key_path.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "jwt_public_key_path cannot be empty".to_string(),
            ));
        }

        // Validate JWT issuer
        if jwt_issuer.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "jwt_issuer cannot be empty".to_string(),
            ));
        }
        if jwt_issuer.len() > 255 {
            return Err(crate::Error::ConfigValidation(
                "jwt_issuer must be no more than 255 characters long".to_string(),
            ));
        }

        // Validate JWT audience
        if jwt_audience.trim().is_empty() {
            return Err(crate::Error::ConfigValidation(
                "jwt_audience cannot be empty".to_string(),
            ));
        }
        if jwt_audience.len() > 255 {
            return Err(crate::Error::ConfigValidation(
                "jwt_audience must be no more than 255 characters long".to_string(),
            ));
        }

        // Validate issuer and audience are different (best practice)
        if jwt_issuer == jwt_audience {
            return Err(crate::Error::ConfigValidation(
                "jwt_issuer and jwt_audience should be different values".to_string(),
            ));
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::TempDir;

    fn valid_authnz() -> AuthNzConfig {
        AuthNzConfig {
            jwt_public_key_path: Some("some/key.pem".to_string()),
            jwt_issuer: Some("https://issuer.example.com".to_string()),
            jwt_audience: Some("udex".to_string()),
        }
    }

    fn write_temp_file(dir: &std::path::Path, name: &str) -> String {
        let path = dir.join(name);
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(b"placeholder").unwrap();
        path.to_string_lossy().into_owned()
    }

    #[test]
    fn tls_validate_ok() {
        let dir = TempDir::new().unwrap();
        let cert = write_temp_file(dir.path(), "server.crt");
        let key = write_temp_file(dir.path(), "server.key");
        let cfg = TlsConfig {
            cert_path: cert,
            key_path: key,
        };
        assert!(cfg.validate().is_ok());
    }

    #[test]
    fn tls_validate_empty_cert_path() {
        let dir = TempDir::new().unwrap();
        let key = write_temp_file(dir.path(), "server.key");
        let cfg = TlsConfig {
            cert_path: String::new(),
            key_path: key,
        };
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("cert_path"),
            "expected cert_path in error: {err}"
        );
    }

    #[test]
    fn tls_validate_empty_key_path() {
        let dir = TempDir::new().unwrap();
        let cert = write_temp_file(dir.path(), "server.crt");
        let cfg = TlsConfig {
            cert_path: cert,
            key_path: String::new(),
        };
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("key_path"),
            "expected key_path in error: {err}"
        );
    }

    #[test]
    fn tls_validate_missing_cert_file() {
        let dir = TempDir::new().unwrap();
        let key = write_temp_file(dir.path(), "server.key");
        let cfg = TlsConfig {
            cert_path: "/nonexistent/path/server.crt".to_string(),
            key_path: key,
        };
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("cert_path"),
            "expected cert_path in error: {err}"
        );
    }

    #[test]
    fn tls_validate_missing_key_file() {
        let dir = TempDir::new().unwrap();
        let cert = write_temp_file(dir.path(), "server.crt");
        let cfg = TlsConfig {
            cert_path: cert,
            key_path: "/nonexistent/path/server.key".to_string(),
        };
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("key_path"),
            "expected key_path in error: {err}"
        );
    }

    #[test]
    fn tls_validate_cert_path_is_directory() {
        let dir = TempDir::new().unwrap();
        let key = write_temp_file(dir.path(), "server.key");
        let cfg = TlsConfig {
            cert_path: dir.path().to_string_lossy().into_owned(),
            key_path: key,
        };
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("cert_path") && err.contains("not a regular file"),
            "expected 'not a regular file' for cert_path, got: {err}"
        );
    }

    #[test]
    fn tls_validate_key_path_is_directory() {
        let dir = TempDir::new().unwrap();
        let cert = write_temp_file(dir.path(), "server.crt");
        let cfg = TlsConfig {
            cert_path: cert,
            key_path: dir.path().to_string_lossy().into_owned(),
        };
        let err = cfg.validate().unwrap_err().to_string();
        assert!(
            err.contains("key_path") && err.contains("not a regular file"),
            "expected 'not a regular file' for key_path, got: {err}"
        );
    }

    #[test]
    fn server_config_validate_calls_tls_validate() {
        let cfg = ServerConfig {
            tls: TlsConfig {
                cert_path: "/nonexistent/server.crt".to_string(),
                key_path: "/nonexistent/server.key".to_string(),
            },
            authnz: valid_authnz(),
            ..ServerConfig::default()
        };
        assert!(cfg.validate().is_err());
    }
}
