// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the server implementation for the Udex Entry service.

use std::{collections::HashMap, sync::Arc};
use tonic::{Request, Response, Status};
use udex_api::{entry::{
    entry_service_server::EntryService as EntryServiceTrait, BulkReadEntryOperationRequest, BulkReadEntryOperationResponse, BulkReadEntryOperationResult, BulkWriteEntryOperationRequest, BulkWriteEntryOperationResponse, BulkWriteEntryOperationResult, Context, ContextInput, CreateEntryRequest, CreateEntryResponse, DeleteEntryRequest, DeleteEntryResponse, LookupContextByKeyRequest, LookupContextByKeyResponse, LookupKeysByContextRequest, LookupKeysByContextResponse
}, index::{index_service_server::IndexService, ListIndicesRequest},
    hash::{ContextHasher, sha1_context_hash}
};
use udex_datastore::{
    Datastore, Entry, EntryReadOperation, EntryReadResult, EntryWriteOperation,
    Error as DatastoreError,
};
use uuid::Uuid;

use crate::{Error, HealthCheck};

/// Server implementation for the Entry service.
/// Handles all entry-related operations including CRUD operations and bulk operations.
pub struct EntryService<D> {
    datastore: Arc<D>,
    index_hasher_fns: HashMap<String, ContextHasher>, // Maps index names to ContextHasher functions
}

#[tonic::async_trait]
impl<D> HealthCheck for EntryService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Checks if the server is healthy.
    async fn is_healthy(&self) -> Result<bool, Error> {
        // Check if the datastore is healthy
        self.datastore
            .is_healthy()
            .await
            .map_err(|e| Error::ServerError(format!("Datastore health check failed: {}", e)))
    }
}

impl<D> EntryService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Creates a new EntryServer instance.
    pub fn new(datastore: Arc<D>) -> Self {

        let index_hasher_fns: HashMap<String, ContextHasher> = HashMap::new();

        Self {
            datastore,
            index_hasher_fns,
        }
    }

    /// Initializes the EntryService.
    pub async fn init(&mut self, index_service: Arc<dyn IndexService>) -> Result<(), Error> {
        
        // Initialize the index map from the index service
        let indexes = index_service
            .list_indices(tonic::Request::new(ListIndicesRequest {}))
            .await
            .map_err(|e| Error::ServerError(format!("Failed to list indices: {}", e)))?
            .into_inner()
            .indices;

        for index in &indexes {
            match index.hash_algorithm {
                h if h == udex_api::index::HashAlgorithm::Sha1 as i32 => {
                   self.index_hasher_fns.insert(index.name.clone(), sha1_context_hash);
                }
                // Add more hash algorithms as needed
                _ => {
                    return Err(Error::ConfigValidation(format!(
                        "Unsupported hash algorithm for index {}",
                        index.name
                    )));
                }
            }
        }

        Ok(())
    }
    
    /// Converts a ContextInput to a Context by generating a hash.
    /// Uses the default hash algorithm (SHA-1) for context identification.
    fn context_input_to_context(&self, index_name: String, input: ContextInput) -> Result<Context, Status> {
        let hasher_fn = self
            .index_hasher_fns
            .get(&index_name)
            .ok_or_else(|| Status::internal(format!(
                "Hash function for index {} not found - have the indexes and this entry service been initialised?",
                index_name
            )))?;

        let hash = hasher_fn(&input)
            .map_err(|e| Status::internal(format!("Failed to generate context hash: {}", e)))?;

        Ok(Context {
            hash,
            pairs: input.pairs,
            dek: input.dek,
            kek_id: input.kek_id,
        })
    }

    /// Converts a datastore Entry to an API Context.
    fn datastore_entry_to_context(&self, entry: &Entry) -> Context {
        entry.context.clone()
    }

    /// Converts a datastore error to a tonic Status.
    ///
    /// Internal errors (Database, Transaction, Serialization, etc.) are logged at error level here,
    /// at the network boundary, before being converted to an opaque Status::internal response.
    fn datastore_error_to_status(&self, error: DatastoreError) -> Status {
        match error {
            DatastoreError::EntryForKeyNotFound(key) => {
                Status::not_found(format!("Entry not found for key: {}", key))
            }
            DatastoreError::EntryForContextNotFound(context) => {
                Status::not_found(format!("Entry not found for context: {}", context))
            }
            DatastoreError::DuplicateKey(key) => {
                Status::already_exists(format!("Entry already exists for key: {}", key))
            }
            DatastoreError::InvalidContext(msg) => {
                Status::invalid_argument(format!("Invalid context: {}", msg))
            }
            DatastoreError::InvalidIndex(msg) => {
                Status::invalid_argument(format!("Invalid index: {}", msg))
            }
            DatastoreError::InvalidIndexUpdate(_) => {
                Status::invalid_argument("Invalid index update")
            }
            DatastoreError::DatabaseNotInitialized(msg) => {
                tracing::error!(error = %msg, "Database not initialized");
                Status::failed_precondition(format!("Database not initialized: {}", msg))
            }
            DatastoreError::NotImplemented(msg) => {
                tracing::error!(error = %msg, "Unimplemented datastore operation called");
                Status::unimplemented(format!("Not implemented: {}", msg))
            }
            DatastoreError::Database(e) => {
                tracing::error!(error = %e, "Database error");
                Status::internal(format!("Database error: {}", e))
            }
            DatastoreError::Transaction(msg) => {
                tracing::error!(error = %msg, "Transaction error");
                Status::internal(format!("Transaction error: {}", msg))
            }
            DatastoreError::Serialization(e) => {
                tracing::error!(error = %e, "Serialization error");
                Status::internal(format!("Serialization error: {}", e))
            }
            DatastoreError::DataConversion(msg) => {
                tracing::error!(error = %msg, "Data conversion error");
                Status::internal(format!("Data conversion error: {}", msg))
            }
            DatastoreError::Migration(msg) => {
                tracing::error!(error = %msg, "Migration error");
                Status::internal(format!("Migration error: {}", msg))
            }
        }
    }
}

#[tonic::async_trait]
impl<D> EntryServiceTrait for EntryService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Creates a new entry with a server-generated UUIDv4 key.
    /// The context hash is generated from the provided context input.
    async fn create_entry(
        &self,
        request: Request<CreateEntryRequest>,
    ) -> Result<Response<CreateEntryResponse>, Status> {
        let req = request.into_inner();

        // Validate request
        let context_input = req
            .context
            .ok_or_else(|| Status::invalid_argument("context is required"))?;

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }
        let index_name = req.index_name;

        // Generate UUIDv4 key
        let key = Uuid::new_v4();

        // Convert context input to context with hash
        let context = self.context_input_to_context(index_name.clone(), context_input)?;

        // save this for the response before moving the context below
        let context_hash = context.hash.clone();

        // Create entry
        let entry = Entry {
            key,
            context,
            index_name,
        };

        // Store in datastore
        self.datastore
            .create_entry(entry)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let response = CreateEntryResponse {
            key: key.to_string(),
            context_hash: context_hash,
        };

        Ok(Response::new(response))
    }

    /// Deletes an entry by key.
    /// If this is the last entry for the context, the context is also deleted.
    async fn delete_entry(
        &self,
        request: Request<DeleteEntryRequest>,
    ) -> Result<Response<DeleteEntryResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        // Parse and validate key
        let key = Uuid::parse_str(&req.key)
            .map_err(|_| Status::invalid_argument("Invalid key format"))?;

        // Delete entry
        self.datastore
            .delete_entry(key)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let response = DeleteEntryResponse {};
        Ok(Response::new(response))
    }

    /// Looks up context by key.
    /// Returns the context associated with the given key.
    async fn lookup_context_by_key(
        &self,
        request: Request<LookupContextByKeyRequest>,
    ) -> Result<Response<LookupContextByKeyResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        // Parse and validate key
        let key = Uuid::parse_str(&req.key)
            .map_err(|_| Status::invalid_argument("Invalid key format"))?;

        // Get entry by key
        let entry = self
            .datastore
            .get_entry_by_key(key)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let response = LookupContextByKeyResponse {
            index_name: req.index_name,
            context: Some(self.datastore_entry_to_context(&entry)),
        };

        Ok(Response::new(response))
    }

    /// Looks up keys by context hash.
    /// Returns all keys associated with the given context hash.
    async fn lookup_keys_by_context(
        &self,
        request: Request<LookupKeysByContextRequest>,
    ) -> Result<Response<LookupKeysByContextResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        if req.context_hash.is_empty() {
            return Err(Status::invalid_argument("context_hash cannot be empty"));
        }

        // Get entries by context hash
        let entries = self
            .datastore
            .get_entries_by_context(&req.context_hash)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let keys: Vec<String> = entries
            .into_iter()
            .map(|entry| entry.key.to_string())
            .collect();

        let response = LookupKeysByContextResponse { keys };
        Ok(Response::new(response))
    }

    /// Performs bulk write operations in a single transaction.
    /// All operations succeed or all fail together.
    async fn bulk_write_entry_operation(
        &self,
        request: Request<BulkWriteEntryOperationRequest>,
    ) -> Result<Response<BulkWriteEntryOperationResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        if req.operations.is_empty() {
            return Err(Status::invalid_argument("operations cannot be empty"));
        }

        // Convert API operations to datastore operations
        let mut datastore_operations = Vec::new();
        let mut response_results = Vec::new();

        for op in req.operations {
            match op.operation {
                Some(udex_api::entry::bulk_write_entry_operation::Operation::CreateEntry(
                    create_op,
                )) => {
                    let context_input = create_op
                        .context
                        .ok_or_else(|| Status::invalid_argument("context is required"))?;

                    // Generate UUIDv4 key
                    let key = Uuid::new_v4();

                    // Convert context input to context with hash
                    let context = self.context_input_to_context(req.index_name.clone(), context_input)?;

                    // save this for the response before moving the context below
                    let context_hash = context.hash.clone();

                    // Create entry with the specified index name
                    let entry = Entry {
                        key,
                        context,
                        index_name: req.index_name.clone(),
                    };

                    datastore_operations.push(EntryWriteOperation::Create(entry));

                    // Prepare response result
                    let create_response = CreateEntryResponse {
                        key: key.to_string(),
                        context_hash: context_hash,
                    };

                    response_results.push(BulkWriteEntryOperationResult {
                        result: Some(
                            udex_api::entry::bulk_write_entry_operation_result::Result::CreateEntry(
                                create_response,
                            ),
                        ),
                    });
                }
                Some(udex_api::entry::bulk_write_entry_operation::Operation::DeleteEntry(
                    delete_op,
                )) => {
                    let key = Uuid::parse_str(&delete_op.key)
                        .map_err(|_| Status::invalid_argument("Invalid key format"))?;

                    datastore_operations.push(EntryWriteOperation::Delete(key));

                    // Prepare response result
                    let delete_response = DeleteEntryResponse {};

                    response_results.push(BulkWriteEntryOperationResult {
                        result: Some(
                            udex_api::entry::bulk_write_entry_operation_result::Result::DeleteEntry(
                                delete_response,
                            ),
                        ),
                    });
                }
                None => {
                    return Err(Status::invalid_argument("operation is required"));
                }
            }
        }

        // Execute bulk write operations
        self.datastore
            .bulk_entry_write(datastore_operations)
            .await
            .map_err(|e| Status::internal(format!("Bulk write operation failed: {}", e)))?;

        let response = BulkWriteEntryOperationResponse {
            results: response_results,
        };

        Ok(Response::new(response))
    }

    /// Performs bulk read operations in a single transaction.
    /// All reads are executed with the same isolation level.
    async fn bulk_read_entry_operation(
        &self,
        request: Request<BulkReadEntryOperationRequest>,
    ) -> Result<Response<BulkReadEntryOperationResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        if req.operations.is_empty() {
            return Err(Status::invalid_argument("operations cannot be empty"));
        }

        // Convert API operations to datastore operations
        let mut datastore_operations = Vec::new();

        for op in req.operations {
            match op.operation {
                Some(udex_api::entry::bulk_read_entry_operation::Operation::LookupContext(
                    lookup_op,
                )) => {
                    let key = Uuid::parse_str(&lookup_op.key)
                        .map_err(|_| Status::invalid_argument("Invalid key format"))?;

                    datastore_operations.push(EntryReadOperation::GetByKey(key));
                }
                Some(udex_api::entry::bulk_read_entry_operation::Operation::LookupKeys(
                    lookup_op,
                )) => {
                    if lookup_op.context_hash.is_empty() {
                        return Err(Status::invalid_argument("context_hash cannot be empty"));
                    }

                    datastore_operations
                        .push(EntryReadOperation::GetByContext(lookup_op.context_hash));
                }
                None => {
                    return Err(Status::invalid_argument("operation is required"));
                }
            }
        }

        // Execute bulk read operations
        let results = self
            .datastore
            .bulk_entry_read(datastore_operations)
            .await
            .map_err(|e| Status::internal(format!("Bulk read operation failed: {}", e)))?;

        // Convert results to API format
        let mut response_results = Vec::new();

        for result in results {
            match result {
                EntryReadResult::Entry(entry) => {
                    let context_response = LookupContextByKeyResponse {
                        index_name: req.index_name.clone(),
                        context: Some(self.datastore_entry_to_context(&entry)),
                    };

                    response_results.push(BulkReadEntryOperationResult {
                        result: Some(udex_api::entry::bulk_read_entry_operation_result::Result::LookupContext(context_response)),
                    });
                }
                EntryReadResult::Entries(entries) => {
                    let keys: Vec<String> =
                        entries.into_iter().map(|e| e.key.to_string()).collect();
                    let keys_response = LookupKeysByContextResponse { keys };

                    response_results.push(BulkReadEntryOperationResult {
                        result: Some(
                            udex_api::entry::bulk_read_entry_operation_result::Result::LookupKeys(
                                keys_response,
                            ),
                        ),
                    });
                }
            }
        }

        let response = BulkReadEntryOperationResponse {
            results: response_results,
        };

        Ok(Response::new(response))
    }
}
