// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the server implementation for the Udex Entry service.

use std::{collections::HashMap, sync::Arc};
use tonic::{Request, Response, Status};
use udex_api::{
    entry::{
        entry_service_server::EntryService as EntryServiceTrait, BulkReadEntryOperationRequest,
        BulkReadEntryOperationResponse, BulkReadEntryOperationResult,
        BulkWriteEntryOperationRequest, BulkWriteEntryOperationResponse,
        BulkWriteEntryOperationResult, Context, ContextInput, CreateEntryRequest,
        CreateEntryResponse, DeleteEntryRequest, DeleteEntryResponse, LookupContextByKeyRequest,
        LookupContextByKeyResponse, LookupKeyByContextRequest, LookupKeyByContextResponse,
    },
    hash::{xxh3_context_hash, ContextHasher},
    index::{index_service_server::IndexService, ListIndicesRequest},
};
use udex_datastore::{
    Datastore, Entry, EntryReadOperation, EntryReadResult, EntryWriteOperation, EntryWriteResult,
    Error as DatastoreError,
};
use uuid::Uuid;

use crate::{Error, HealthCheck};

/// Server implementation for the Entry service.
/// Handles all entry-related operations including CRUD operations and bulk operations.
pub struct EntryService<D> {
    datastore: Arc<D>,
    index_hasher_fns: HashMap<String, ContextHasher>, // Maps index names to ContextHasher functions
}

#[tonic::async_trait]
impl<D> HealthCheck for EntryService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Checks if the server is healthy.
    async fn is_healthy(&self) -> Result<bool, Error> {
        // Check if the datastore is healthy
        self.datastore
            .is_healthy()
            .await
            .map_err(|e| Error::ServerError(format!("Datastore health check failed: {}", e)))
    }
}

impl<D> EntryService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Creates a new EntryServer instance.
    pub fn new(datastore: Arc<D>) -> Self {
        let index_hasher_fns: HashMap<String, ContextHasher> = HashMap::new();

        Self {
            datastore,
            index_hasher_fns,
        }
    }

    /// Initializes the EntryService.
    pub async fn init(&mut self, index_service: Arc<dyn IndexService>) -> Result<(), Error> {
        // Initialize the index map from the index service
        let indexes = index_service
            .list_indices(tonic::Request::new(ListIndicesRequest {}))
            .await
            .map_err(|e| Error::ServerError(format!("Failed to list indices: {}", e)))?
            .into_inner()
            .indices;

        for index in &indexes {
            match index.hash_algorithm {
                h if h == udex_api::index::HashAlgorithm::Xxh3 as i32 => {
                    self.index_hasher_fns
                        .insert(index.name.clone(), xxh3_context_hash);
                }
                // Add more hash algorithms as needed
                _ => {
                    return Err(Error::ConfigValidation(format!(
                        "Unsupported hash algorithm for index {}",
                        index.name
                    )));
                }
            }
        }

        Ok(())
    }

    /// Converts a ContextInput to a Context by generating a hash.
    /// Uses the configured hash algorithm (xxh3) for context identification.
    #[allow(clippy::result_large_err)]
    fn context_input_to_context(
        &self,
        index_name: String,
        input: ContextInput,
    ) -> Result<Context, Status> {
        let hasher_fn = self
            .index_hasher_fns
            .get(&index_name)
            .ok_or_else(|| Status::internal(format!(
                "Hash function for index {} not found - have the indexes and this entry service been initialised?",
                index_name
            )))?;

        let hash = hasher_fn(&input)
            .map_err(|e| Status::internal(format!("Failed to generate context hash: {}", e)))?;

        Ok(Context {
            hash,
            pairs: input.pairs,
        })
    }

    /// Converts a datastore Entry to an API Context.
    fn datastore_entry_to_context(&self, entry: &Entry) -> Context {
        entry.context.clone()
    }

    /// Converts a datastore error to a tonic Status.
    ///
    /// Internal errors (Database, Transaction, Serialization, etc.) are logged at error level here,
    /// at the network boundary, before being converted to an opaque Status::internal response.
    fn datastore_error_to_status(&self, error: DatastoreError) -> Status {
        match error {
            DatastoreError::EntryForKeyNotFound(key) => {
                Status::not_found(format!("Entry not found for key: {}", key))
            }
            DatastoreError::EntryForContextNotFound(context) => {
                Status::not_found(format!("Entry not found for context: {}", context))
            }
            DatastoreError::InvalidContext(msg) => {
                Status::invalid_argument(format!("Invalid context: {}", msg))
            }
            DatastoreError::InvalidIndex(msg) => {
                Status::invalid_argument(format!("Invalid index: {}", msg))
            }
            DatastoreError::InvalidIndexUpdate(_) => {
                Status::invalid_argument("Invalid index update")
            }
            DatastoreError::DatabaseNotInitialized(msg) => {
                tracing::error!(error = %msg, "Database not initialized");
                Status::failed_precondition("Service unavailable")
            }
            DatastoreError::NotImplemented(msg) => {
                tracing::error!(error = %msg, "Unimplemented datastore operation called");
                Status::unimplemented("Not implemented")
            }
            DatastoreError::Database(e) => {
                tracing::error!(error = %e, "Database error");
                Status::internal("Internal server error")
            }
            DatastoreError::Transaction(msg) => {
                tracing::error!(error = %msg, "Transaction error");
                Status::internal("Internal server error")
            }
            DatastoreError::Serialization(e) => {
                tracing::error!(error = %e, "Serialization error");
                Status::internal("Internal server error")
            }
            DatastoreError::DataConversion(msg) => {
                tracing::error!(error = %msg, "Data conversion error");
                Status::internal("Internal server error")
            }
            DatastoreError::Migration(msg) => {
                tracing::error!(error = %msg, "Migration error");
                Status::internal("Internal server error")
            }
        }
    }
}

#[tonic::async_trait]
impl<D> EntryServiceTrait for EntryService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Creates a new entry with a server-generated UUIDv4 key.
    /// The context hash is generated from the provided context input.
    async fn create_entry(
        &self,
        request: Request<CreateEntryRequest>,
    ) -> Result<Response<CreateEntryResponse>, Status> {
        let req = request.into_inner();

        // Validate request
        let context_input = req
            .context
            .ok_or_else(|| Status::invalid_argument("context is required"))?;

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }
        let index_name = req.index_name;

        // Generate UUIDv4 key
        let key = Uuid::new_v4();

        // Convert context input to context with hash
        let context = self.context_input_to_context(index_name.clone(), context_input)?;

        // save this for the response before moving the context below
        let context_hash = context.hash.clone();

        // Create entry
        let entry = Entry {
            key,
            context,
            index_name,
        };

        // Store in datastore — returns actual key (new or pre-existing on idempotent create)
        let stored_key = self
            .datastore
            .create_entry(entry)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let response = CreateEntryResponse {
            key: stored_key.to_string(),
            context_hash,
        };

        Ok(Response::new(response))
    }

    /// Deletes an entry by key.
    async fn delete_entry(
        &self,
        request: Request<DeleteEntryRequest>,
    ) -> Result<Response<DeleteEntryResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        // Parse and validate key
        let key = Uuid::parse_str(&req.key)
            .map_err(|_| Status::invalid_argument("Invalid key format"))?;

        // Delete entry — index_name is included in the WHERE clause so a caller with
        // scope for index_a cannot delete a key that belongs to index_b.
        self.datastore
            .delete_entry(&req.index_name, key)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let response = DeleteEntryResponse {};
        Ok(Response::new(response))
    }

    /// Looks up context by key.
    /// Returns the context associated with the given key.
    async fn lookup_context_by_key(
        &self,
        request: Request<LookupContextByKeyRequest>,
    ) -> Result<Response<LookupContextByKeyResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        // Parse and validate key
        let key = Uuid::parse_str(&req.key)
            .map_err(|_| Status::invalid_argument("Invalid key format"))?;

        // Get entry by key
        let entry = self
            .datastore
            .get_entry_by_key(key)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let response = LookupContextByKeyResponse {
            index_name: req.index_name,
            context: Some(self.datastore_entry_to_context(&entry)),
        };

        Ok(Response::new(response))
    }

    /// Looks up the single key associated with a context hash, if one exists.
    async fn lookup_key_by_context(
        &self,
        request: Request<LookupKeyByContextRequest>,
    ) -> Result<Response<LookupKeyByContextResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        if req.context_hash.is_empty() {
            return Err(Status::invalid_argument("context_hash cannot be empty"));
        }

        // Get entry by context hash within the named index — returns None when no entry exists
        let entry = self
            .datastore
            .get_entry_by_context(&req.index_name, &req.context_hash)
            .await
            .map_err(|e| self.datastore_error_to_status(e))?;

        let key = entry.map(|e| e.key.to_string());

        let response = LookupKeyByContextResponse { key };
        Ok(Response::new(response))
    }

    /// Performs bulk write operations in a single transaction.
    /// All operations succeed or all fail together.
    async fn bulk_write_entry_operation(
        &self,
        request: Request<BulkWriteEntryOperationRequest>,
    ) -> Result<Response<BulkWriteEntryOperationResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        if req.operations.is_empty() {
            return Err(Status::invalid_argument("operations cannot be empty"));
        }

        // Convert API operations into (datastore_op, context_hash) pairs kept together
        // so the two can never diverge in length — eliminating the zip-truncation risk.
        let mut ops_with_meta: Vec<(EntryWriteOperation, Option<String>)> = Vec::new();

        for op in req.operations {
            match op.operation {
                Some(udex_api::entry::bulk_write_entry_operation::Operation::CreateEntry(
                    create_op,
                )) => {
                    let context_input = create_op
                        .context
                        .ok_or_else(|| Status::invalid_argument("context is required"))?;

                    // Convert context input to context with hash
                    let context =
                        self.context_input_to_context(req.index_name.clone(), context_input)?;

                    // save this for the response before moving the context below
                    let context_hash = context.hash.clone();

                    // Create entry with the specified index name
                    let entry = Entry {
                        key: Uuid::new_v4(),
                        context,
                        index_name: req.index_name.clone(),
                    };

                    ops_with_meta.push((EntryWriteOperation::Create(entry), Some(context_hash)));
                }
                Some(udex_api::entry::bulk_write_entry_operation::Operation::DeleteEntry(
                    delete_op,
                )) => {
                    let key = Uuid::parse_str(&delete_op.key)
                        .map_err(|_| Status::invalid_argument("Invalid key format"))?;

                    ops_with_meta.push((
                        EntryWriteOperation::Delete {
                            index_name: req.index_name.clone(),
                            key,
                        },
                        None,
                    ));
                }
                None => {
                    return Err(Status::invalid_argument("operation is required"));
                }
            }
        }

        let (datastore_operations, context_hashes): (Vec<_>, Vec<_>) =
            ops_with_meta.into_iter().unzip();

        // Execute bulk write — use returned results for actual keys (idempotent creates
        // may return a pre-existing key rather than the candidate key above).
        let write_results = self
            .datastore
            .bulk_entry_write(datastore_operations)
            .await
            .map_err(|e| self.datastore_error_to_status(e.into_source()))?;

        // Validate the datastore upheld the contract of one result per operation.
        if write_results.len() != context_hashes.len() {
            return Err(Status::internal(format!(
                "bulk write result count mismatch: expected {}, got {}",
                context_hashes.len(),
                write_results.len(),
            )));
        }

        let mut response_results = Vec::new();
        for (write_result, context_hash) in write_results.into_iter().zip(context_hashes) {
            match write_result {
                EntryWriteResult::Created(key) => {
                    let context_hash = context_hash.ok_or_else(|| {
                        Status::internal("bulk write Created result missing context_hash")
                    })?;
                    response_results.push(BulkWriteEntryOperationResult {
                        result: Some(
                            udex_api::entry::bulk_write_entry_operation_result::Result::CreateEntry(
                                CreateEntryResponse {
                                    key: key.to_string(),
                                    context_hash,
                                },
                            ),
                        ),
                    });
                }
                EntryWriteResult::Deleted => {
                    response_results.push(BulkWriteEntryOperationResult {
                        result: Some(
                            udex_api::entry::bulk_write_entry_operation_result::Result::DeleteEntry(
                                DeleteEntryResponse {},
                            ),
                        ),
                    });
                }
            }
        }

        let response = BulkWriteEntryOperationResponse {
            results: response_results,
        };

        Ok(Response::new(response))
    }

    /// Performs bulk read operations in a single transaction.
    /// All reads are executed with the same isolation level.
    async fn bulk_read_entry_operation(
        &self,
        request: Request<BulkReadEntryOperationRequest>,
    ) -> Result<Response<BulkReadEntryOperationResponse>, Status> {
        let req = request.into_inner();

        // Validate index_name
        if req.index_name.is_empty() {
            return Err(Status::invalid_argument("index_name is required"));
        }

        if req.operations.is_empty() {
            return Err(Status::invalid_argument("operations cannot be empty"));
        }

        // Convert API operations to datastore operations
        let mut datastore_operations = Vec::new();

        for op in req.operations {
            match op.operation {
                Some(udex_api::entry::bulk_read_entry_operation::Operation::LookupContext(
                    lookup_op,
                )) => {
                    let key = Uuid::parse_str(&lookup_op.key)
                        .map_err(|_| Status::invalid_argument("Invalid key format"))?;

                    datastore_operations.push(EntryReadOperation::GetByKey(key));
                }
                Some(udex_api::entry::bulk_read_entry_operation::Operation::LookupKey(
                    lookup_op,
                )) => {
                    if lookup_op.context_hash.is_empty() {
                        return Err(Status::invalid_argument("context_hash cannot be empty"));
                    }

                    datastore_operations.push(EntryReadOperation::GetByContext {
                        index_name: req.index_name.clone(),
                        context_hash: lookup_op.context_hash,
                    });
                }
                None => {
                    return Err(Status::invalid_argument("operation is required"));
                }
            }
        }

        // Execute bulk read operations
        let results = self
            .datastore
            .bulk_entry_read(datastore_operations)
            .await
            .map_err(|e| self.datastore_error_to_status(e.into_source()))?;

        // Convert results to API format
        let mut response_results = Vec::new();

        for result in results {
            match result {
                EntryReadResult::ByKey(entry) => {
                    let context_response = LookupContextByKeyResponse {
                        index_name: req.index_name.clone(),
                        context: Some(self.datastore_entry_to_context(&entry)),
                    };

                    response_results.push(BulkReadEntryOperationResult {
                        result: Some(udex_api::entry::bulk_read_entry_operation_result::Result::LookupContext(context_response)),
                    });
                }
                EntryReadResult::EntryByContext(opt_entry) => {
                    let key = opt_entry.map(|e| e.key.to_string());
                    let keys_response = LookupKeyByContextResponse { key };

                    response_results.push(BulkReadEntryOperationResult {
                        result: Some(
                            udex_api::entry::bulk_read_entry_operation_result::Result::LookupKey(
                                keys_response,
                            ),
                        ),
                    });
                }
            }
        }

        let response = BulkReadEntryOperationResponse {
            results: response_results,
        };

        Ok(Response::new(response))
    }
}
