// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the server implementation for the Udex Index service.

use std::sync::Arc;
use tonic::{Request, Response, Status};
use udex_api::authz::claims::Claims;
use udex_api::index::{
    index_service_server::IndexService as IndexServiceTrait, CreateIndexRequest,
    CreateIndexResponse, DescribeRequest, DescribeResponse, Index, IndexUpdate, ListIndicesRequest,
    ListIndicesResponse, UpdateIndexRequest, UpdateIndexResponse,
};
use udex_datastore::Datastore;

use crate::{Error, HealthCheck};

/// Server implementation for the Index service.
/// Handles all index-related operations including health checks, CRUD operations.
pub struct IndexService<D> {
    datastore: Arc<D>,
}

impl<D> IndexService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Creates a new IndexService instance.
    pub fn new(datastore: Arc<D>) -> Self {
        Self { datastore }
    }

    /// Creates a new index in the datastore - used internally
    async fn create_index_internal(&self, index: Index) -> Result<(), Error> {
        // Implementation for creating an index in the datastore
        self.datastore
            .create_index(index)
            .await
            .map_err(Error::Datastore)
    }

    async fn update_index_internal(
        &self,
        name: &str,
        update: IndexUpdate,
        updated_by: &str,
    ) -> Result<Index, Error> {
        // Implementation for updating an index in the datastore
        self.datastore
            .update_index(name, update, updated_by)
            .await
            .map_err(Error::Datastore)
    }

    async fn list_indices_internal(&self) -> Result<Vec<Index>, Error> {
        // Implementation for listing all indices in the datastore
        self.datastore
            .list_indices()
            .await
            .map_err(Error::Datastore)
    }

    pub async fn init(&self, init_indexes: Vec<UpdateIndexRequest>) -> Result<(), Error> {
        // first list the existing indices
        let existing_indices = self.list_indices_internal().await?;
        // Initialize the datastore with the provided indices
        for index_request in init_indexes {
            let update = match index_request.update {
                Some(update) => update,
                None => {
                    return Err(Error::ServerError(
                        "Index update request must contain an update".to_string(),
                    ));
                }
            };

            // check all mandatory fields are present
            if update.description.is_none() {
                return Err(Error::ServerError(
                    "Index update must contain a description".to_string(),
                ));
            }
            if update.max_bulk_operations.is_none() {
                return Err(Error::ServerError(
                    "Index update must contain max_bulk_operations".to_string(),
                ));
            }
            if update.max_key_length.is_none() {
                return Err(Error::ServerError(
                    "Index update must contain max_key_length".to_string(),
                ));
            }
            if update.max_value_length.is_none() {
                return Err(Error::ServerError(
                    "Index update must contain max_value_length".to_string(),
                ));
            }
            if update.max_kv_pairs_per_context.is_none() {
                return Err(Error::ServerError(
                    "Index update must contain max_kv_pairs_per_context".to_string(),
                ));
            }
            if update.hash_algorithm.is_none() {
                return Err(Error::ServerError(
                    "Index update must contain hash_algorithm".to_string(),
                ));
            }

            // clone update so we can use it multiple times
            let update_for_index = update.clone();

            // the mandatory fields are already checked above
            // so we can safely create the index
            let index = Index {
                name: index_request.name.clone(),
                description: update_for_index
                    .description
                    .expect("Index update must contain a description"),
                max_bulk_operations: update_for_index
                    .max_bulk_operations
                    .expect("Index update must contain max_bulk_operations"),
                max_key_length: update_for_index
                    .max_key_length
                    .expect("Index update must contain max_key_length"),
                max_value_length: update_for_index
                    .max_value_length
                    .expect("Index update must contain max_value_length"),
                max_kv_pairs_per_context: update_for_index
                    .max_kv_pairs_per_context
                    .expect("Index update must contain max_kv_pairs_per_context"),
                hash_algorithm: update_for_index
                    .hash_algorithm
                    .expect("Index update must contain hash_algorithm"),
                created_at: Some(udex_api::now_timestamp()),
                created_by: "init".to_string(),
                updated_at: None,
                updated_by: None,
            };

            if let Some(existing) = existing_indices
                .iter()
                .find(|i| i.name == index_request.name)
            {
                // check if index requested is different from existing
                if existing.description != index.description
                    || existing.max_bulk_operations != index.max_bulk_operations
                    || existing.max_key_length != index.max_key_length
                    || existing.max_value_length != index.max_value_length
                    || existing.max_kv_pairs_per_context != index.max_kv_pairs_per_context
                    || existing.hash_algorithm != index.hash_algorithm
                {
                    // update the existing index
                    self.update_index_internal(&index_request.name, update.clone(), "init")
                        .await?;
                }
                // else: index already exists and is the same, skip
            } else {
                // create the index
                self.create_index_internal(index).await?;
            }
        }
        Ok(())
    }
}

#[tonic::async_trait]
impl<D> HealthCheck for IndexService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Checks if the server is healthy.
    async fn is_healthy(&self) -> Result<bool, Error> {
        // Check if the datastore is healthy
        self.datastore
            .is_healthy()
            .await
            .map_err(|e| Error::ServerError(format!("Datastore health check failed: {}", e)))
    }
}

#[tonic::async_trait]
impl<D> IndexServiceTrait for IndexService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Returns information about a specific index.
    async fn describe(
        &self,
        request: Request<DescribeRequest>,
    ) -> Result<Response<DescribeResponse>, Status> {
        let req = request.into_inner();

        // Validate input
        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }

        match self.datastore.get_index(&req.name).await {
            Ok(index) => Ok(Response::new(DescribeResponse { index: Some(index) })),
            Err(e) => {
                // Check if it's a "not found" error by looking at the error message
                let error_msg = format!("{}", e);
                if error_msg.contains("no rows returned") || error_msg.contains("RowNotFound") {
                    Err(Status::not_found(format!("Index '{}' not found", req.name)))
                } else {
                    tracing::error!(error = %e, index = %req.name, "Failed to get index");
                    Err(Status::internal("Internal server error"))
                }
            }
        }
    }

    /// Creates a new index.
    async fn create_index(
        &self,
        request: Request<CreateIndexRequest>,
    ) -> Result<Response<CreateIndexResponse>, Status> {
        let sub = request
            .extensions()
            .get::<Claims>()
            .map(|c| c.sub().to_string())
            .ok_or_else(|| {
                tracing::error!("Claims missing from request extensions — auth middleware not applied to create_index");
                Status::internal("Internal server error")
            })?;
        let req = request.into_inner();

        // Validate input
        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }
        if req.max_bulk_operations < 1 {
            return Err(Status::invalid_argument("max_bulk_operations must be >= 1"));
        }
        if req.max_key_length < 1 {
            return Err(Status::invalid_argument("max_key_length must be >= 1"));
        }
        if req.max_value_length < 1 {
            return Err(Status::invalid_argument("max_value_length must be >= 1"));
        }
        if req.max_kv_pairs_per_context < 1 {
            return Err(Status::invalid_argument(
                "max_kv_pairs_per_context must be >= 1",
            ));
        }
        udex_api::index::HashAlgorithm::try_from(req.hash_algorithm).map_err(|_| {
            Status::invalid_argument(format!(
                "unsupported hash_algorithm value: {}",
                req.hash_algorithm
            ))
        })?;

        let index = Index {
            name: req.name,
            description: req.description,
            max_bulk_operations: req.max_bulk_operations,
            max_key_length: req.max_key_length,
            max_value_length: req.max_value_length,
            max_kv_pairs_per_context: req.max_kv_pairs_per_context,
            hash_algorithm: req.hash_algorithm,
            created_at: Some(udex_api::now_timestamp()),
            created_by: sub,
            updated_at: None,
            updated_by: None,
        };

        self.create_index_internal(index.clone())
            .await
            .map_err(|e| {
                tracing::error!(error = %e, "Failed to create index");
                Status::internal("Internal server error")
            })?;

        Ok(Response::new(CreateIndexResponse { index: Some(index) }))
    }

    /// Updates an existing index's mutable fields.
    async fn update_index(
        &self,
        request: Request<UpdateIndexRequest>,
    ) -> Result<Response<UpdateIndexResponse>, Status> {
        let req = request.into_inner();

        // Validate input
        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }

        let update = req
            .update
            .ok_or_else(|| Status::invalid_argument("update fields are required"))?;

        // Validate that at least one field is provided for update
        if update.description.is_none()
            && update.max_bulk_operations.is_none()
            && update.max_key_length.is_none()
            && update.max_value_length.is_none()
            && update.max_kv_pairs_per_context.is_none()
            && update.hash_algorithm.is_none()
        {
            return Err(Status::invalid_argument(
                "at least one field must be provided for update",
            ));
        }

        Err(Status::unimplemented(
            "IndexService::update_index not implemented",
        ))
    }

    /// Returns a list of all indices.
    async fn list_indices(
        &self,
        _request: Request<ListIndicesRequest>,
    ) -> Result<Response<ListIndicesResponse>, Status> {
        match self.list_indices_internal().await {
            Ok(indices) => {
                let response = ListIndicesResponse { indices };
                Ok(Response::new(response))
            }
            Err(e) => {
                tracing::error!(error = %e, "Failed to list indices");
                Err(Status::internal("Internal server error"))
            }
        }
    }
}
