// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the server implementation for the Udex Index service.

use std::sync::Arc;
use tonic::{Request, Response, Status};
use udex_api::authz::claims::Claims;
use udex_api::index::{
    index_service_server::IndexService as IndexServiceTrait, CreateIndexRequest,
    CreateIndexResponse, DeleteIndexRequest, DeleteIndexResponse, DescribeRequest,
    DescribeResponse, Index, IndexUpdate, ListIndicesRequest, ListIndicesResponse,
    UpdateIndexRequest, UpdateIndexResponse,
};
use udex_datastore::Datastore;

use tonic_health::{server::HealthReporter, ServingStatus};

use crate::Error;

/// Returns `Some(invalid_char)` if `name` contains a character outside the allowed set
/// (Unicode letters, Unicode digits, hyphens, underscores), or `None` if the name is valid.
fn invalid_name_char(name: &str) -> Option<char> {
    name.chars()
        .find(|&c| !c.is_alphabetic() && !c.is_numeric() && c != '-' && c != '_')
}

fn format_invalid_name_char(c: char) -> String {
    format!("'{}' (U+{:04X})", c.escape_default(), c as u32)
}

/// Server implementation for the Index service.
/// Handles all index-related operations including CRUD operations.
pub struct IndexService<D> {
    datastore: Arc<D>,
    health_reporter: HealthReporter,
}

impl<D> IndexService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Creates a new IndexService instance.
    pub fn new(datastore: Arc<D>, health_reporter: HealthReporter) -> Self {
        Self {
            datastore,
            health_reporter,
        }
    }

    /// Creates a new index in the datastore - used internally
    async fn create_index_internal(&self, index: Index) -> Result<(), Error> {
        // Implementation for creating an index in the datastore
        self.datastore
            .create_index(index)
            .await
            .map_err(Error::Datastore)
    }

    async fn update_index_internal(
        &self,
        name: &str,
        update: IndexUpdate,
        updated_by: &str,
    ) -> Result<Index, Error> {
        // Implementation for updating an index in the datastore
        self.datastore
            .update_index(name, update, updated_by)
            .await
            .map_err(Error::Datastore)
    }

    async fn list_indices_internal(&self) -> Result<Vec<Index>, Error> {
        // Implementation for listing all indices in the datastore
        self.datastore
            .list_indices()
            .await
            .map_err(Error::Datastore)
    }

    pub async fn init(&self, init_indexes: Vec<CreateIndexRequest>) -> Result<(), Error> {
        let existing_indices = self.list_indices_internal().await?;

        for req in init_indexes {
            if req.name.trim().is_empty() {
                return Err(Error::ServerError(
                    "init index name must be non-empty".to_string(),
                ));
            }
            if let Some(bad) = invalid_name_char(&req.name) {
                return Err(Error::ServerError(format!(
                    "init index name '{}' contains invalid character {}; \
                     allowed: Unicode letters, digits, hyphens, underscores",
                    req.name,
                    format_invalid_name_char(bad)
                )));
            }
            if req.display_name.trim().is_empty() {
                return Err(Error::ServerError(
                    "init index display_name must be non-empty".to_string(),
                ));
            }
            if req.description.trim().is_empty() {
                return Err(Error::ServerError(
                    "init index description must be non-empty".to_string(),
                ));
            }
            if req.max_bulk_operations < 1 {
                return Err(Error::ServerError(
                    "init index max_bulk_operations must be >= 1".to_string(),
                ));
            }
            if req.max_key_length < 1 {
                return Err(Error::ServerError(
                    "init index max_key_length must be >= 1".to_string(),
                ));
            }
            if req.max_value_length < 1 {
                return Err(Error::ServerError(
                    "init index max_value_length must be >= 1".to_string(),
                ));
            }
            if req.max_kv_pairs_per_context < 1 {
                return Err(Error::ServerError(
                    "init index max_kv_pairs_per_context must be >= 1".to_string(),
                ));
            }
            udex_api::index::HashAlgorithm::try_from(req.hash_algorithm).map_err(|_| {
                Error::ServerError(format!(
                    "init index '{}' has unsupported hash_algorithm value: {}",
                    req.name, req.hash_algorithm
                ))
            })?;

            if let Some(existing) = existing_indices.iter().find(|i| i.name == req.name) {
                // hash_algorithm is immutable after creation — error at startup if config disagrees
                if existing.hash_algorithm != req.hash_algorithm {
                    return Err(Error::ServerError(format!(
                        "cannot change hash_algorithm of existing index '{}': \
                         stored={}, configured={}",
                        req.name, existing.hash_algorithm, req.hash_algorithm
                    )));
                }
                // Update mutable fields if anything changed
                if existing.description != req.description
                    || existing.display_name != req.display_name
                    || existing.max_bulk_operations != req.max_bulk_operations
                    || existing.max_key_length != req.max_key_length
                    || existing.max_value_length != req.max_value_length
                    || existing.max_kv_pairs_per_context != req.max_kv_pairs_per_context
                {
                    self.update_index_internal(
                        &req.name,
                        IndexUpdate {
                            description: Some(req.description),
                            display_name: Some(req.display_name),
                            max_bulk_operations: Some(req.max_bulk_operations),
                            max_key_length: Some(req.max_key_length),
                            max_value_length: Some(req.max_value_length),
                            max_kv_pairs_per_context: Some(req.max_kv_pairs_per_context),
                        },
                        "init",
                    )
                    .await?;
                }
            } else {
                self.create_index_internal(Index {
                    name: req.name,
                    display_name: req.display_name,
                    description: req.description,
                    max_bulk_operations: req.max_bulk_operations,
                    max_key_length: req.max_key_length,
                    max_value_length: req.max_value_length,
                    max_kv_pairs_per_context: req.max_kv_pairs_per_context,
                    hash_algorithm: req.hash_algorithm,
                    created_at: Some(udex_api::now_timestamp()),
                    created_by: "init".to_string(),
                    updated_at: None,
                    updated_by: None,
                })
                .await?;
            }
        }

        self.health_reporter
            .set_service_status("udex.index.v1.IndexService", ServingStatus::Serving)
            .await;

        Ok(())
    }
}

#[tonic::async_trait]
impl<D> IndexServiceTrait for IndexService<D>
where
    D: Datastore + Send + Sync + 'static,
{
    /// Returns information about a specific index.
    async fn describe(
        &self,
        request: Request<DescribeRequest>,
    ) -> Result<Response<DescribeResponse>, Status> {
        let req = request.into_inner();

        // Validate input
        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }

        match self.datastore.get_index(&req.name).await {
            Ok(index) => Ok(Response::new(DescribeResponse { index: Some(index) })),
            Err(e) => {
                // Check if it's a "not found" error by looking at the error message
                let error_msg = format!("{}", e);
                if error_msg.contains("no rows returned") || error_msg.contains("RowNotFound") {
                    Err(Status::not_found(format!("Index '{}' not found", req.name)))
                } else {
                    tracing::error!(error = %e, index = %req.name, "Failed to get index");
                    Err(Status::internal("Internal server error"))
                }
            }
        }
    }

    /// Creates a new index.
    async fn create_index(
        &self,
        request: Request<CreateIndexRequest>,
    ) -> Result<Response<CreateIndexResponse>, Status> {
        let sub = request
            .extensions()
            .get::<Claims>()
            .map(|c| c.sub().to_string())
            .ok_or_else(|| {
                tracing::error!("Claims missing from request extensions — auth middleware not applied to create_index");
                Status::internal("Internal server error")
            })?;
        let req = request.into_inner();

        // Validate input
        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }
        if let Some(bad) = invalid_name_char(&req.name) {
            return Err(Status::invalid_argument(format!(
                "index name '{}' contains invalid character {}; allowed: Unicode letters, digits, hyphens, underscores",
                req.name,
                format_invalid_name_char(bad)
            )));
        }
        if req.display_name.trim().is_empty() {
            return Err(Status::invalid_argument("display_name is required"));
        }
        if req.description.trim().is_empty() {
            return Err(Status::invalid_argument("description is required"));
        }
        if req.max_bulk_operations < 1 {
            return Err(Status::invalid_argument("max_bulk_operations must be >= 1"));
        }
        if req.max_key_length < 1 {
            return Err(Status::invalid_argument("max_key_length must be >= 1"));
        }
        if req.max_value_length < 1 {
            return Err(Status::invalid_argument("max_value_length must be >= 1"));
        }
        if req.max_kv_pairs_per_context < 1 {
            return Err(Status::invalid_argument(
                "max_kv_pairs_per_context must be >= 1",
            ));
        }
        udex_api::index::HashAlgorithm::try_from(req.hash_algorithm).map_err(|_| {
            Status::invalid_argument(format!(
                "unsupported hash_algorithm value: {}",
                req.hash_algorithm
            ))
        })?;

        let index = Index {
            name: req.name,
            display_name: req.display_name,
            description: req.description,
            max_bulk_operations: req.max_bulk_operations,
            max_key_length: req.max_key_length,
            max_value_length: req.max_value_length,
            max_kv_pairs_per_context: req.max_kv_pairs_per_context,
            hash_algorithm: req.hash_algorithm,
            created_at: Some(udex_api::now_timestamp()),
            created_by: sub,
            updated_at: None,
            updated_by: None,
        };

        self.create_index_internal(index.clone())
            .await
            .map_err(|e| {
                tracing::error!(error = %e, "Failed to create index");
                Status::internal("Internal server error")
            })?;

        Ok(Response::new(CreateIndexResponse { index: Some(index) }))
    }

    /// Updates an existing index's mutable fields.
    async fn update_index(
        &self,
        request: Request<UpdateIndexRequest>,
    ) -> Result<Response<UpdateIndexResponse>, Status> {
        let req = request.into_inner();

        // Validate input
        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }

        let update = req
            .update
            .ok_or_else(|| Status::invalid_argument("update fields are required"))?;

        // Validate that at least one field is provided for update
        if update.description.is_none()
            && update.display_name.is_none()
            && update.max_bulk_operations.is_none()
            && update.max_key_length.is_none()
            && update.max_value_length.is_none()
            && update.max_kv_pairs_per_context.is_none()
        {
            return Err(Status::invalid_argument(
                "at least one field must be provided for update",
            ));
        }

        Err(Status::unimplemented(
            "IndexService::update_index not implemented",
        ))
    }

    /// Returns a list of all indices.
    async fn list_indices(
        &self,
        _request: Request<ListIndicesRequest>,
    ) -> Result<Response<ListIndicesResponse>, Status> {
        match self.list_indices_internal().await {
            Ok(indices) => {
                let response = ListIndicesResponse { indices };
                Ok(Response::new(response))
            }
            Err(e) => {
                tracing::error!(error = %e, "Failed to list indices");
                Err(Status::internal("Internal server error"))
            }
        }
    }

    async fn delete_index(
        &self,
        request: Request<DeleteIndexRequest>,
    ) -> Result<Response<DeleteIndexResponse>, Status> {
        let _ = request
            .extensions()
            .get::<Claims>()
            .ok_or_else(|| {
                tracing::error!("Claims missing from request extensions — auth middleware not applied to delete_index");
                Status::internal("Internal server error")
            })?;
        let req = request.into_inner();

        if req.name.is_empty() {
            return Err(Status::invalid_argument("index name is required"));
        }

        match self.datastore.delete_index(&req.name).await {
            Ok(()) => Ok(Response::new(DeleteIndexResponse {})),
            Err(udex_datastore::Error::IndexNotEmpty(msg)) => {
                tracing::error!(error = %msg, index = %req.name, "Attempt to delete non-empty index");
                Err(Status::failed_precondition("index is not empty"))
            }
            Err(udex_datastore::Error::InvalidIndex(_)) => {
                Err(Status::not_found(format!("index '{}' not found", req.name)))
            }
            Err(e) => {
                tracing::error!(error = %e, index = %req.name, "Failed to delete index");
                Err(Status::internal("Internal server error"))
            }
        }
    }
}
