// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the main library exports for the Udex core server.

//! Udex Core Server
//!
//! This crate contains the core server implementation for Udex, including
//! the gRPC service implementations for Entry and Index services.

mod authn;
pub mod config;
pub mod entry;
pub mod healthz;
pub mod index;
pub mod logging;
pub mod server;

pub use entry::EntryService;
pub use healthz::HealthzService;
pub use index::IndexService;

use thiserror::Error;

#[derive(Debug, Error)]
pub enum Error {
    #[error("Datastore error: {0}")]
    Datastore(#[from] udex_datastore::Error),

    #[error("Server error: {0}")]
    ServerError(String),

    /// Validation error
    #[error("Config validation failed: {0}")]
    ConfigValidation(String),
}

#[tonic::async_trait]
pub trait HealthCheck {
    /// Checks the server is healthy
    async fn is_healthy(&self) -> Result<bool, Error>;
}
