// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// It contains the main library exports for the Udex core server.

//! Udex Core Server
//!
//! This crate contains the core server implementation for Udex, including
//! the gRPC service implementations for Entry and Index services.

pub mod config;
pub mod entry;
pub mod index;
pub mod healthz;
pub mod server;
mod authn;

pub use entry::EntryService;
pub use index::IndexService;
pub use healthz::HealthzService;

use thiserror::Error;

#[derive(Debug, Error)]
pub enum Error {
    #[error("Datastore error: {0}")]
    Datastore(#[from] udex_datastore::Error),

    #[error("Server error: {0}")]
    ServerError(String),
    /// Type of error that occurs when a requested operation is not implemented
    #[error("Not implemented: {0}")]
    NotImplemented(String),

    /// Validation error
    #[error("Config validation failed: {0}")]
    ConfigValidation(String),

    #[error("Authentication error: {0}")]
    Authentication(String),
    // #[error("Authorization error: {0}")]
    // Authorization(String),
}

#[tonic::async_trait]
pub trait HealthCheck {
    /// Checks the servier is healthy
    async fn is_healthy(&self) -> Result<bool, Error>;
}