// This file was initially generated by Claude Code using the Claude Sonnet 4.6 LLM model.
use tracing_subscriber::{fmt, EnvFilter};

// Production tracing/telemetry initialisation (JSON stdout floor + optional OTLP)
// is owned by the `udex-telemetry` crate; `serve()` calls `udex_telemetry::init`.
// Only the test-only subscriber lives here.

/// Initializes a human-readable tracing subscriber for use in tests.
///
/// Output is routed through `with_test_writer()`, so it is captured per-test
/// and only visible when running with `--nocapture`:
///
/// ```bash
/// RUST_LOG=debug cargo test -- --nocapture
/// ```
///
/// Safe to call multiple times — subsequent calls are no-ops.
pub fn init_test_tracing() {
    let env_filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info"));

    let _ = fmt()
        .with_env_filter(env_filter)
        .with_test_writer()
        .try_init();
}
