#!/bin/bash
# Generates .env at the workspace root with fresh secret values.
# Public/config items use well-known dev defaults.
#
# Usage:
#   scripts/gen-env.sh           # prompts if .env already exists
#   scripts/gen-env.sh --force   # overwrites without prompting
#
# Run once when first cloning the repo. Re-run with --force to rotate secrets.
# The devcontainer post-create script calls this automatically.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${WORKSPACE_DIR}/.env"

FORCE=false
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

if [[ -f "${ENV_FILE}" && "${FORCE}" == false ]]; then
  read -r -p ".env already exists. Overwrite and rotate all secrets? [y/N] " reply
  if [[ ! "${reply}" =~ ^[Yy]$ ]]; then
    echo "Aborted. Existing .env unchanged."
    exit 0
  fi
fi

echo "Generating secrets..."

# Generate secret values
POSTGRES_PASSWORD_SECRET_VAL=$(openssl rand -hex 24)
HYDRA_DB_PASSWORD_SECRET_VAL=$(openssl rand -hex 24)
HYDRA_SECRETS_SYSTEM_SECRET_VAL=$(openssl rand -hex 32)

cat > "${ENV_FILE}" <<EOF
# ============================================================
# Udex development environment — DO NOT COMMIT
# Generated by scripts/gen-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run with --force to rotate all secrets.
# ============================================================

# ------------------------------------------------------------
# PostgreSQL
# ------------------------------------------------------------
# Public config
POSTGRES_USER=postgres
POSTGRES_DB=postgres

# Secrets — injected into docker-compose and the devcontainer
POSTGRES_PASSWORD_SECRET=${POSTGRES_PASSWORD_SECRET_VAL}

# Derived — full connection URL for cargo test and the CLI
DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD_SECRET_VAL}@localhost:5432/postgres

# ------------------------------------------------------------
# Hydra (OAuth2 server)
# ------------------------------------------------------------
# Public config
HYDRA_PUBLIC_URL=http://localhost:4444
HYDRA_ADMIN_URL=http://localhost:4445
HYDRA_ISSUER=http://localhost:4444/

# Secrets
HYDRA_DB_PASSWORD_SECRET=${HYDRA_DB_PASSWORD_SECRET_VAL}
HYDRA_SECRETS_SYSTEM_SECRET=${HYDRA_SECRETS_SYSTEM_SECRET_VAL}
EOF

chmod 600 "${ENV_FILE}"

echo ".env written to ${ENV_FILE}"
echo ""
echo "Next step: run scripts/gen-keys-and-certs.sh to generate TLS and JWT key material."
