#!/bin/bash
# Generates the dev env file with fresh secret values.
# Public/config items use well-known dev defaults.
#
# The real file lives at the workspace root .env and .devcontainer/.env is a
# relative symlink to it. This keeps a single source of truth (Highlander):
# tools that look for ./.env and tools that mount .devcontainer/.env both
# resolve to the same file.
#
# Usage:
#   scripts/gen-env.sh           # prompts if an env file already exists
#   scripts/gen-env.sh --force   # overwrites without prompting
#
# Run once when first cloning the repo. Re-run with --force to rotate secrets.
# Re-running is idempotent: it converges to the same file + symlink layout
# regardless of the starting state. The devcontainer post-create script calls
# this automatically.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEVCONTAINER_DIR="${WORKSPACE_DIR}/.devcontainer"
ENV_FILE="${WORKSPACE_DIR}/.env"      # the real file (mode 600)
ENV_LINK="${DEVCONTAINER_DIR}/.env"   # relative symlink -> ../.env

FORCE=false
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

# Prompt if either the real root file or the devcontainer link already resolves
# to content. -e follows symlinks, so this catches a stale layout (root .env is
# itself a symlink) as well as the normal one.
if [[ ( -e "${ENV_FILE}" || -e "${ENV_LINK}" ) && "${FORCE}" == false ]]; then
  read -r -p ".env already exists. Overwrite and rotate all secrets? [y/N] " reply
  if [[ ! "${reply}" =~ ^[Yy]$ ]]; then
    echo "Aborted. Existing .env unchanged."
    exit 0
  fi
fi

echo "Generating secrets..."

# Generate secret values. All three use `openssl rand -hex`, which produces
# [0-9a-f] only — no $, ', ", or whitespace. This matters because the values
# are expanded inside an unquoted heredoc below; a character outside that
# alphabet could cause silent shell expansion or broken output. If you ever
# change the generator (e.g. to base64 or a passphrase), quote the heredoc
# delimiter (<<'EOF') and emit the values via printf/envsubst instead.
POSTGRES_PASSWORD_SECRET_VAL=$(openssl rand -hex 24)
HYDRA_DB_PASSWORD_SECRET_VAL=$(openssl rand -hex 24)
HYDRA_SECRETS_SYSTEM_SECRET_VAL=$(openssl rand -hex 32)

# Guard: if openssl is missing or fails, command substitution returns an empty
# string. set -e won't catch that (it only catches non-zero exits at the
# statement level). Fail fast here rather than writing a .env full of blanks.
if [[ -z "${POSTGRES_PASSWORD_SECRET_VAL}" || \
      -z "${HYDRA_DB_PASSWORD_SECRET_VAL}" || \
      -z "${HYDRA_SECRETS_SYSTEM_SECRET_VAL}" ]]; then
  echo "ERROR: secret generation produced an empty value — is openssl installed?" >&2
  exit 1
fi

# Hydra URLs: callers may export these before invoking this script to override
# the defaults. The devcontainer post-create does this so that the .env it
# generates uses the Docker service name rather than localhost.
HYDRA_PUBLIC_URL="${HYDRA_PUBLIC_URL:-http://localhost:4444}"
HYDRA_ADMIN_URL="${HYDRA_ADMIN_URL:-http://localhost:4445}"

# Ensure the devcontainer dir exists (for the link) and clear any stale entry at
# ENV_FILE. The clear matters: if root .env is currently a symlink (e.g. it was
# flipped to point at .devcontainer/.env), an unguarded `cat >` would write
# *through* the link instead of replacing it with the real file. rm -f is a
# no-op when absent.
mkdir -p "${DEVCONTAINER_DIR}"
rm -f "${ENV_FILE}"

cat > "${ENV_FILE}" <<EOF
# ============================================================
# Udex development environment — DO NOT COMMIT
# Generated by scripts/gen-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run with --force to rotate all secrets.
# ============================================================

# ------------------------------------------------------------
# PostgreSQL
# ------------------------------------------------------------
# Public config
POSTGRES_USER=postgres
POSTGRES_DB=postgres

# Secrets — injected into docker-compose and the devcontainer
POSTGRES_PASSWORD_SECRET=${POSTGRES_PASSWORD_SECRET_VAL}

# Derived — full connection URL for cargo test and the CLI
DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD_SECRET_VAL}@localhost:5432/postgres

# ------------------------------------------------------------
# Hydra (OAuth2 server)
# ------------------------------------------------------------
# Public config — override before calling gen-env.sh to change these values.
HYDRA_PUBLIC_URL=${HYDRA_PUBLIC_URL}
HYDRA_ADMIN_URL=${HYDRA_ADMIN_URL}
HYDRA_ISSUER=http://localhost:4444/

# Secrets
HYDRA_DB_PASSWORD_SECRET=${HYDRA_DB_PASSWORD_SECRET_VAL}
HYDRA_SECRETS_SYSTEM_SECRET=${HYDRA_SECRETS_SYSTEM_SECRET_VAL}

# ------------------------------------------------------------
# Observability (ST0027)
# ------------------------------------------------------------
# The ClickHouse-backed obs fixture (collector + ClickHouse + Vector + HyperDX)
# is part of the base projects/compose stack and needs no .env secrets: the
# collector is keyless and the HyperDX dev UI registers its own local user.
EOF

chmod 600 "${ENV_FILE}"

# Expose the real root file inside .devcontainer via a relative symlink. -f
# replaces whatever is there (an old real .env or a prior symlink); -n avoids
# following an existing symlinked dir. The target is relative so the link is
# path-portable.
ln -sfn "../.env" "${ENV_LINK}"

echo ".env written to ${ENV_FILE}"
echo "  and symlinked at ${ENV_LINK} -> ../.env"
echo ""
echo "Next step: run scripts/gen-keys-and-certs.sh to generate TLS and JWT key material."
