// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// Integration tests for PostgreSQL datastore implementation.
use rstest::*;
use uuid::Uuid;
use udex_datastore::{
    Datastore, Entry, EntryReadOperation, EntryReadResult, EntryWriteOperation, Migrator, 
};
use udex_datastore::integration_test::{
    data, 
};
use udex_api::index::IndexUpdate;
use udex_api::index::Index;
use udex_api::entry::{
    Context as UdexContext, // Aliased to avoid clash with rstest Context - aliasing rstest Context causes issues with the `#[rstest]` attribute.
    KeyValuePair,
    Value
};

const ID_PREFIX: &str = "postgres_integration_test_";

// Generates a name for a test index based on the test context.
fn index_name(ctx: &Context) -> String {
    format!("{}_{}", ID_PREFIX, ctx.name)
}

/// Test helper to create a sample index
fn create_sample_index(name: &str) -> Index {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap();
    
    Index {
        name: name.to_string(),
        description: "Test index".to_string(),
        max_bulk_operations: 100,
        max_key_length: 256,
        max_value_length: 1024,
        max_kv_pairs_per_context: 50,
        hash_algorithm: udex_api::index::HashAlgorithm::Sha1 as i32, // Use the enum value directly
        created_at: Some(udex_api::protobuf::Timestamp {
            seconds: now.as_secs() as i64,
            nanos: now.subsec_nanos() as i32,
        }),
        created_by: "test_user".to_string(),
        updated_at: None,
        updated_by: None,
    }
}

/// Test helper to create a sample context
fn create_sample_context(hash: &str) -> UdexContext {
    UdexContext {
        hash: hash.to_string(),
        pairs: vec![
            KeyValuePair {
                key: "name".to_string(),
                value: Some(Value {
                    value: Some(udex_api::entry::value::Value::StringValue("test_value".to_string())),
                }),
                kek_id: None,
            },
            KeyValuePair {
                key: "count".to_string(),
                value: Some(Value {
                    value: Some(udex_api::entry::value::Value::IntValue(42)),
                }),
                kek_id: None,
            },
        ],
        dek: None,
        kek_id: None,
    }
}

/// Tests that the datastore can be initialized successfully.
#[rstest]
#[tokio_shared_rt::test] //We use tokio shared runtime to ensure the static variables are still valid between tests -https://docs.rs/tokio-shared-rt/latest/tokio_shared_rt/
async fn test_datastore_init() {
    let data = data(false).await;
    let datastore = &data.0;
    let pool = &data.1;
    let res = sqlx::query("SELECT 1").execute(&**pool).await;
    assert!(res.is_ok(), "Database connection should succeed");
    // check migrations
    datastore
        .check_migration_version()
        .await
        .expect("Migration version check failed");
    // test health check
    let is_healthy = datastore.is_healthy().await.expect("Health check failed");
    assert!(is_healthy, "Datastore should be healthy");
}

// Tests creating an index and then retrieving it.
// Verifies that all index properties are correctly stored and retrieved,
// including name, description, limits, and hash algorithm.
#[rstest]
#[tokio_shared_rt::test]
async fn test_create_and_get_index(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);

    // Test creating an index
    let create_result = datastore.create_index(index.clone()).await;
    assert!(create_result.is_ok(), "{}", format!("Index creation should succeed: {}", create_result.unwrap_err()));

    // Test getting the index
    let retrieved_index = datastore
        .get_index(&idx_name)
        .await
        .expect("Failed to get index");
    assert_eq!(retrieved_index.name, index.name);
    assert_eq!(retrieved_index.description, index.description);
    assert_eq!(
        retrieved_index.max_bulk_operations,
        index.max_bulk_operations
    );
    assert_eq!(retrieved_index.max_key_length, index.max_key_length);
    assert_eq!(retrieved_index.max_value_length, index.max_value_length);
    assert_eq!(
        retrieved_index.max_kv_pairs_per_context,
        index.max_kv_pairs_per_context
    );
    assert_eq!(retrieved_index.hash_algorithm, index.hash_algorithm);
    assert!(retrieved_index.created_at.is_some());
    assert_eq!(retrieved_index.created_by, index.created_by);
    assert_eq!(retrieved_index.updated_at, index.updated_at);
    assert_eq!(retrieved_index.updated_by, index.updated_by);

    // Test that creating an index with the same name fails with invalid index error.
    let duplicate_result = datastore.create_index(index.clone()).await;
    assert!(duplicate_result.is_err(), "Creating index with duplicate name should fail");
}

/// Tests creating an entry between a unique key and a context.
/// Verifies that entries can be created successfully when prerequisite
/// index and context data exist in the database.
#[rstest]
#[tokio_shared_rt::test]
async fn test_create_entry(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let _pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_1");
    let key = Uuid::new_v4();

    // Create prerequisite index and context
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    let entry = Entry {
        key,
        context: context.clone(),
        index_name: idx_name.clone(),
    };

    // Test creating an entry
    let result = datastore.create_entry(entry.clone()).await;
    assert!(result.is_ok(), "{}", format!("Entry creation should succeed: {}", result.unwrap_err()));

    // Verify the entry was created correctly by retrieving it
    let retrieved_entry = datastore
        .get_entry_by_key(key)
        .await
        .expect("Failed to retrieve created entry");
    
    assert_eq!(retrieved_entry.key, key);
    assert_eq!(retrieved_entry.context.hash, context.hash);
    assert_eq!(retrieved_entry.context.pairs.len(), context.pairs.len());
    assert_eq!(retrieved_entry.context.pairs[0].key, "name");
    assert_eq!(retrieved_entry.context.pairs[1].key, "count");
    assert_eq!(retrieved_entry.index_name, idx_name);
    
    // Verify the context values are correct
    if let Some(ref name_value) = retrieved_entry.context.pairs[0].value {
        if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
            assert_eq!(s, "test_value");
        } else {
            panic!("Expected string value for name");
        }
    } else {
        panic!("Expected value for name");
    }
    
    if let Some(ref count_value) = retrieved_entry.context.pairs[1].value {
        if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
            assert_eq!(i, 42);
        } else {
            panic!("Expected int value for count");
        }
    } else {
        panic!("Expected value for count");
    }
    
    // Test that creating another entry with the same context hash fails with DuplicateContext.
    let duplicate_entry = Entry {
        key,
        context: create_sample_context("test_hash_2"),
        index_name: idx_name.clone(),
    };
    
    let duplicate_result = datastore.create_entry(duplicate_entry).await;
    assert!(duplicate_result.is_err(), "Creating entry with duplicate key should fail");
    
    if let Err(error) = duplicate_result {
        match error {
            udex_datastore::Error::DuplicateKey(_) => {
                // This is expected
            }
            _ => panic!("Expected DuplicateKey error, got: {:?}", error),
        }
    }

    // Test that an entry with a duplicate context but different key can be created
    let new_key = Uuid::new_v4();
    let entry_with_same_context = Entry {
        key: new_key,
        context: context.clone(), // same context as before
        index_name: idx_name.clone(),
    };

    let result = datastore.create_entry(entry_with_same_context).await;
    assert!(
        result.is_ok(),
        "Creating entry with duplicate context but different key should succeed: {:?}",
        result.err()
    );
}

/// Tests retrieving an entry by its associated unique key.
/// Verifies that the correct entry with full context data
/// is returned when querying by a key.
#[rstest]
#[tokio_shared_rt::test]
async fn test_get_entry_by_key(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let _pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_2");
    let key = Uuid::new_v4();

    // Create prerequisite data
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create entry using the datastore method
    let entry = Entry {
        key,
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    
    datastore
        .create_entry(entry)
        .await
        .expect("Failed to create entry");

    // Test getting entry by key
    let retrieved_entry = datastore
        .get_entry_by_key(key)
        .await
        .expect("Failed to get entry");
    assert_eq!(retrieved_entry.key, key);
    assert_eq!(retrieved_entry.context.hash, context.hash);
    assert_eq!(retrieved_entry.context.pairs.len(), context.pairs.len());
    assert_eq!(retrieved_entry.context.pairs[0].key, "name");
    assert_eq!(retrieved_entry.context.pairs[1].key, "count");
    assert_eq!(retrieved_entry.index_name, idx_name);
    
    // Verify the context values are correct
    if let Some(ref name_value) = retrieved_entry.context.pairs[0].value {
        if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
            assert_eq!(s, "test_value");
        } else {
            panic!("Expected string value for name");
        }
    } else {
        panic!("Expected value for name");
    }
    
    if let Some(ref count_value) = retrieved_entry.context.pairs[1].value {
        if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
            assert_eq!(i, 42);
        } else {
            panic!("Expected int value for count");
        }
    } else {
        panic!("Expected value for count");
    }
}

/// Tests retrieving all entries associated with a specific context.
/// Verifies that multiple entries can have the same context
/// and that all entries are returned when querying by context hash.
#[rstest]
#[tokio_shared_rt::test]
async fn test_get_entries_by_context(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let _pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_3");

    let key1 = Uuid::new_v4();
    let key2 = Uuid::new_v4();

    // Create prerequisite data
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create entries using the datastore method
    let entry1 = Entry {
        key: key1,
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    
    let entry2 = Entry {
        key: key2,
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    
    datastore
        .create_entry(entry1)
        .await
        .expect("Failed to create entry 1");
        
    datastore
        .create_entry(entry2)
        .await
        .expect("Failed to create entry 2");

    // Test getting entries by context
    let entries = datastore
        .get_entries_by_context(&context.hash)
        .await
        .expect("Failed to get entries");
    assert_eq!(entries.len(), 2, "Expected 2 entries for context");
    
    let keys: Vec<Uuid> = entries.iter().map(|e| e.key).collect();
    assert!(keys.contains(&key1));
    assert!(keys.contains(&key2));
    
    // Verify all entries have the correct context and index
    for entry in entries {
        assert_eq!(entry.context.hash, context.hash);
        assert_eq!(entry.index_name, idx_name);
        assert_eq!(entry.context.pairs.len(), context.pairs.len());
        
        // Verify the context values are correct
        assert_eq!(entry.context.pairs[0].key, "name");
        assert_eq!(entry.context.pairs[1].key, "count");
        
        if let Some(ref name_value) = entry.context.pairs[0].value {
            if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
                assert_eq!(s, "test_value");
            } else {
                panic!("Expected string value for name");
            }
        } else {
            panic!("Expected value for name");
        }
        
        if let Some(ref count_value) = entry.context.pairs[1].value {
            if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
                assert_eq!(i, 42);
            } else {
                panic!("Expected int value for count");
            }
        } else {
            panic!("Expected value for count");
        }
    }
}

/// Tests deleting an entry between a key and context.
/// Verifies that entries can be successfully removed and that
/// the context no longer has any associated keys after deletion.
#[rstest]
#[tokio_shared_rt::test]
async fn test_delete_entry(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_5");
    let key = Uuid::new_v4();

    // Create prerequisite data
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create entry using datastore method
    let entry = Entry {
        key,
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    
    datastore
        .create_entry(entry)
        .await
        .expect("Failed to create entry");

    // Verify entry exists before deletion
    let retrieved_entry = datastore
        .get_entry_by_key(key)
        .await
        .expect("Failed to get entry before deletion");
    assert_eq!(retrieved_entry.key, key);
    assert_eq!(retrieved_entry.context.hash, context.hash);

    // Test deleting entry
    let result = datastore.delete_entry(key).await;
    assert!(result.is_ok(), "Deleting entry should succeed");

    // Verify the entry was deleted
    let entries = datastore
        .get_entries_by_context(&context.hash)
        .await
        .expect("Failed to get entries");
    assert_eq!(entries.len(), 0);

    // Create two entries for the same context with different keys.
    let key2 = Uuid::new_v4();
    let entry2 = Entry {
        key: key2,
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    datastore
        .create_entry(entry2)
        .await
        .expect("Failed to create second entry");
    let key3 = Uuid::new_v4();
    let entry3 = Entry {
        key: key3,
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    datastore
        .create_entry(entry3)
        .await
        .expect("Failed to create third entry");

    // Verify that if we delete the entry for key2 the entry for key still exists.
    let result = datastore.delete_entry(key2).await;
    assert!(result.is_ok(), "Deleting entry should succeed"); 
    let entries = datastore
        .get_entries_by_context(&context.hash)
        .await
        .expect("Failed to get entries after deletion");
    assert_eq!(entries.len(), 1, "Expected 1 entry remaining for context after deletion");
    assert_eq!(entries[0].key, key3, "Remaining entry should be the one with key3");
    assert_eq!(entries[0].context.hash, context.hash, "Remaining entry should have the same context hash");

    // Verify that if we now delete the last entry for the context it is also deleted.
    let result = datastore.delete_entry(key3).await;
    assert!(result.is_ok(), "Deleting last entry should succeed");
    let entries = datastore
        .get_entries_by_context(&context.hash)
        .await
        .expect("Failed to get entries after deleting last entry");
    assert_eq!(entries.len(), 0, "Expected no entries remaining for context after deleting last entry"); 

    // Verify the context has also been deleted by using a direct sqlx query.
    let context_exists: bool = sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM context WHERE hash = $1)")
        .bind(&context.hash)
        .fetch_one(&**pool)
        .await
        .expect("Failed to check if context exists");
    assert!(!context_exists, "Context should be deleted after last entry is removed");
}

/// Tests error handling for various failure scenarios.
/// Verifies that appropriate errors are returned for non-existent resources
/// and that empty results are handled correctly.
#[rstest]
#[tokio_shared_rt::test]
async fn test_error_handling() {
    let data = data(false).await;
    let datastore = &data.0;

    // Test getting non-existent index
    let result = datastore.get_index("non_existent_index").await;
    assert!(result.is_err(), "Getting non-existent index should fail");

    // Test getting entry by non-existent key
    let non_existent_key = Uuid::new_v4();
    let result = datastore.get_entry_by_key(non_existent_key).await;
    assert!(
        result.is_err(),
        "Getting entry by non-existent key should fail"
    );

    // Test getting entries by non-existent context
    let result = datastore.get_entries_by_context("non_existent_context").await;
    assert!(
        result.is_ok(),
        "Getting entries by non-existent context should return empty vec"
    );
    assert_eq!(result.unwrap().len(), 0);
}

/// Tests updating an index's mutable fields.
/// Verifies that index descriptions can be updated and that
/// the updated values are correctly persisted and retrieved.
#[rstest]
#[tokio_shared_rt::test]
async fn test_update_index(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);

    // Create index
    datastore
        .create_index(index.clone())
        .await
        .expect("Failed to create index");

    // Update the index description
    let new_description = Some("Updated test index description".to_string());
    let new_description_value = new_description.clone().unwrap_or_default();
    let update = IndexUpdate {
        description: new_description.clone(),
        max_bulk_operations: None,
        max_key_length: None,
        max_value_length: None,
        max_kv_pairs_per_context: None,
        hash_algorithm: None,
    };
    let updated_index = datastore
        .update_index(&idx_name, update, "test_update_index")
        .await
        .expect("Failed to update index");

    // Verify the update
    assert_eq!(updated_index.name, index.name);
    assert_eq!(updated_index.description, new_description_value);
    assert_eq!(updated_index.max_bulk_operations, index.max_bulk_operations);
    assert_eq!(updated_index.hash_algorithm, index.hash_algorithm);
    assert_eq!(updated_index.created_by, index.created_by);
    assert!(updated_index.created_at.is_some());

    // Verify by getting the index again
    let retrieved_index = datastore
        .get_index(&idx_name)
        .await
        .expect("Failed to get updated index");
    assert_eq!(retrieved_index.description, new_description_value);

    // Test updating to empty description
    let empty_description_update = IndexUpdate {
        description: Some("".to_string()),
        max_bulk_operations: None,
        max_key_length: None,
        max_value_length: None,
        max_kv_pairs_per_context: None,
        hash_algorithm: None,
    };
    let updated_to_empty = datastore
        .update_index(&idx_name, empty_description_update, "test_update_index")
        .await
        .expect("Failed to update index to empty description");
    assert_eq!(updated_to_empty.description, "");

    // Test all mutable fields can be updated
    let full_update = IndexUpdate {
        description: Some("Full update test index".to_string()),
        max_bulk_operations: Some(200),
        max_key_length: Some(512),
        max_value_length: Some(2048),
        max_kv_pairs_per_context: Some(100),
        hash_algorithm: Some(udex_api::index::HashAlgorithm::Sha1 as i32),
    };
    let updated_full_index = datastore
        .update_index(&idx_name, full_update, "test_full_update_index")
        .await
        .expect("Failed to fully update index");
    assert_eq!(updated_full_index.name, index.name);
    assert_eq!(updated_full_index.description, "Full update test index");
    assert_eq!(updated_full_index.max_bulk_operations, 200);
    assert_eq!(updated_full_index.max_key_length, 512);
    assert_eq!(updated_full_index.max_value_length, 2048);
    assert_eq!(updated_full_index.max_kv_pairs_per_context, 100);
    assert_eq!(updated_full_index.hash_algorithm, udex_api::index::HashAlgorithm::Sha1 as i32);

    // Test updating no fields throws an error
    let no_update = IndexUpdate {
        description: None,
        max_bulk_operations: None,
        max_key_length: None,
        max_value_length: None,
        max_kv_pairs_per_context: None,  
        hash_algorithm: None,
    };
    let no_update_result = datastore.update_index(&idx_name, no_update, "test_update_index").await;
    assert!(no_update_result.is_err(), "Updating index with no changes should fail");
    if let Err(error) = no_update_result {
        match error {
            udex_datastore::Error::InvalidIndexUpdate(_) => {
                // This is expected
            }
            _ => panic!("Expected InvalidIndexUpdate error, got: {:?}", error),
        }
    }
}

/// Tests listing all indices.
/// Verifies that all created indices are returned in the list
/// and that the list is properly ordered by name.
#[rstest]
#[tokio_shared_rt::test]
async fn test_list_indices(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    // Create multiple indices
    let index1 = create_sample_index(&format!("{}_list_1", idx_name));
    let index2 = create_sample_index(&format!("{}_list_2", idx_name));
    let index3 = create_sample_index(&format!("{}_list_3", idx_name));

    datastore.create_index(index1.clone()).await.expect("Failed to create index 1");
    datastore.create_index(index2.clone()).await.expect("Failed to create index 2");
    datastore.create_index(index3.clone()).await.expect("Failed to create index 3");

    // List all indices
    let indices = datastore
        .list_indices()
        .await
        .expect("Failed to list indices");

    // Find our test indices in the list
    let our_indices: Vec<_> = indices
        .iter()
        .filter(|idx| idx.name.contains(&format!("{}_list_", idx_name)))
        .collect();

    assert_eq!(our_indices.len(), 3);
    assert!(our_indices.iter().any(|idx| idx.name == index1.name));
    assert!(our_indices.iter().any(|idx| idx.name == index2.name));
    assert!(our_indices.iter().any(|idx| idx.name == index3.name));

    // Verify ordering (should be sorted by name)
    for i in 1..our_indices.len() {
        assert!(our_indices[i-1].name <= our_indices[i].name);
    }
}


/// Tests concurrent operations on the datastore.
/// Verifies that multiple simultaneous operations (context creation,
/// entry creation, and retrieval) can be performed safely without
/// data corruption or race conditions.
#[rstest]
#[tokio_shared_rt::test]
async fn test_concurrent_operations(
    #[context] ctx: Context,
) {
    let fixtures = data(false).await;
    let datastore = &fixtures.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create multiple concurrent operations
    let mut handles = vec![];
    // Let datastore = Arc::new(datastore);
    // Let pool = Arc::new(pool);
    let idx_name_clone = idx_name.clone();

    for i in 0..10 {
        
        // Let datastore_clone = Arc::clone(&datastore);
        // Let pool_clone = Arc::clone(&pool);
        let idx_name_for_task = idx_name_clone.clone();

        let handle = tokio::spawn(async move {
            // Due to maybe_once these will be the same datastore and pool.
            let loop_fixtures = data(false).await;
            let loop_datastore = &loop_fixtures.0;
            let _loop_pool = &loop_fixtures.1;

            let context = create_sample_context(&format!("concurrent_hash_{}", i));
            let key = Uuid::new_v4();

            // Create entry using datastore method
            let entry = Entry {
                key,
                context: context.clone(),
                index_name: idx_name_for_task,
            };

            loop_datastore
                .create_entry(entry)
                .await
                .expect("Failed to create entry");

            // Get entry back and verify values
            let retrieved_entry = loop_datastore
                .get_entry_by_key(key)
                .await
                .expect("Failed to get entry");
            assert_eq!(retrieved_entry.context.hash, context.hash);
            assert_eq!(retrieved_entry.key, key);
            assert_eq!(retrieved_entry.context.pairs.len(), context.pairs.len());
            
            // Verify the context values are correct
            if let Some(ref name_value) = retrieved_entry.context.pairs[0].value {
                if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
                    assert_eq!(s, "test_value");
                }
            }
            
            if let Some(ref count_value) = retrieved_entry.context.pairs[1].value {
                if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
                    assert_eq!(i, 42);
                }
            }
        });

        handles.push(handle);
    }

    // Wait for all operations to complete
    for handle in handles {
        handle.await.expect("Concurrent operation failed");
    }
}

/// Tests bulk write operations (create and delete) in a single transaction.
/// Verifies that multiple operations are executed atomically.
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_entry_write(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create test entries
    let context1 = create_sample_context("test_bulk_write_1");
    let context2 = create_sample_context("test_bulk_write_2");
    let key1 = Uuid::new_v4();
    let key2 = Uuid::new_v4();
    let key3 = Uuid::new_v4();

    let entry1 = Entry {
        key: key1,
        context: context1.clone(),
        index_name: idx_name.clone(),
    };

    let entry2 = Entry {
        key: key2,
        context: context2.clone(),
        index_name: idx_name.clone(),
    };

    let entry3 = Entry {
        key: key3,
        context: context1.clone(),
        index_name: idx_name.clone(),
    };

    // Create first entry individually to test deletion
    datastore
        .create_entry(entry3.clone())
        .await
        .expect("Failed to create entry for deletion test");

    // Test bulk write operations: create two entries and delete one
    let operations = vec![
        EntryWriteOperation::Create(entry1.clone()),
        EntryWriteOperation::Create(entry2.clone()),
        EntryWriteOperation::Delete(key3),
    ];

    let result = datastore.bulk_entry_write(operations).await;
    assert!(result.is_ok(), "Bulk write operations should succeed");

    // Verify the entries were created
    let retrieved_entry1 = datastore
        .get_entry_by_key(key1)
        .await
        .expect("Failed to retrieve first created entry");
    assert_eq!(retrieved_entry1.key, key1);
    assert_eq!(retrieved_entry1.context.hash, context1.hash);

    let retrieved_entry2 = datastore
        .get_entry_by_key(key2)
        .await
        .expect("Failed to retrieve second created entry");
    assert_eq!(retrieved_entry2.key, key2);
    assert_eq!(retrieved_entry2.context.hash, context2.hash);

    // Verify the entry was deleted
    let delete_result = datastore.get_entry_by_key(key3).await;
    assert!(delete_result.is_err(), "Deleted entry should not be found");
}

/// Tests bulk read operations in a single transaction.
/// Verifies that multiple read operations are executed with consistent isolation.
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_entry_read(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create test entries
    let context1 = create_sample_context("test_bulk_read_1");
    let context2 = create_sample_context("test_bulk_read_2");
    let key1 = Uuid::new_v4();
    let key2 = Uuid::new_v4();
    let key3 = Uuid::new_v4();

    let entry1 = Entry {
        key: key1,
        context: context1.clone(),
        index_name: idx_name.clone(),
    };

    let entry2 = Entry {
        key: key2,
        context: context2.clone(),
        index_name: idx_name.clone(),
    };

    let entry3 = Entry {
        key: key3,
        context: context1.clone(), // Same context as entry1
        index_name: idx_name.clone(),
    };

    // Create entries
    datastore
        .create_entry(entry1)
        .await
        .expect("Failed to create entry1");
    datastore
        .create_entry(entry2)
        .await
        .expect("Failed to create entry2");
    datastore
        .create_entry(entry3)
        .await
        .expect("Failed to create entry3");

    // Test bulk read operations
    let operations = vec![
        EntryReadOperation::GetByKey(key1),
        EntryReadOperation::GetByKey(key2),
        EntryReadOperation::GetByContext(context1.hash.clone()),
    ];

    let result = datastore.bulk_entry_read(operations).await;
    assert!(result.is_ok(), "Bulk read operations should succeed: {:?}", result.err());
    
    let results = result.unwrap();
    assert_eq!(results.len(), 3, "Should have 3 results");
    
    // Check first result - GetByKey(key1)
    match &results[0] {
        EntryReadResult::Entry(entry) => {
            assert_eq!(entry.key, key1);
            assert_eq!(entry.context.hash, context1.hash);
            assert_eq!(entry.index_name, idx_name);
            // Verify context values
            assert_eq!(entry.context.pairs.len(), 2);
            assert_eq!(entry.context.pairs[0].key, "name");
            assert_eq!(entry.context.pairs[1].key, "count");
        }
        _ => panic!("Expected Entry result for GetByKey operation"),
    }
    
    // Check second result - GetByKey(key2)
    match &results[1] {
        EntryReadResult::Entry(entry) => {
            assert_eq!(entry.key, key2);
            assert_eq!(entry.context.hash, context2.hash);
            assert_eq!(entry.index_name, idx_name);
            // Verify context values
            assert_eq!(entry.context.pairs.len(), 2);
            assert_eq!(entry.context.pairs[0].key, "name");
            assert_eq!(entry.context.pairs[1].key, "count");
        }
        _ => panic!("Expected Entry result for GetByKey operation"),
    }
    
    // Check third result - GetByContext(context1.hash)
    match &results[2] {
        EntryReadResult::Entries(entries) => {
            assert_eq!(entries.len(), 2, "Should have 2 entries for context1 (key1 and key3)");
            
            // Sort entries by key for consistent testing
            let mut sorted_entries = entries.clone();
            sorted_entries.sort_by_key(|e| e.key);
            
            // Check both entries have the same context
            for entry in &sorted_entries {
                assert_eq!(entry.context.hash, context1.hash);
                assert_eq!(entry.index_name, idx_name);
                assert_eq!(entry.context.pairs.len(), 2);
                assert_eq!(entry.context.pairs[0].key, "name");
                assert_eq!(entry.context.pairs[1].key, "count");
            }
            
            // Check that we have the expected keys
            let keys: Vec<Uuid> = sorted_entries.iter().map(|e| e.key).collect();
            assert!(keys.contains(&key1), "Should contain key1");
            assert!(keys.contains(&key3), "Should contain key3");
        }
        _ => panic!("Expected Entries result for GetByContext operation"),
    }
}

/// Tests bulk write operations with transaction rollback on failure.
/// Verifies that if any operation fails, all operations are rolled back.
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_entry_write_rollback(
    #[context] ctx: Context,
) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Create test entries
    let context1 = create_sample_context("test_bulk_rollback_1");
    let key1 = Uuid::new_v4();
    let key2 = Uuid::new_v4();

    let entry1 = Entry {
        key: key1,
        context: context1.clone(),
        index_name: idx_name.clone(),
    };

    let entry2 = Entry {
        key: key2,
        context: context1.clone(),
        index_name: idx_name.clone(),
    };

    // Create first entry individually
    datastore
        .create_entry(entry1.clone())
        .await
        .expect("Failed to create entry for rollback test");

    // Test bulk write operations that should fail due to duplicate key
    let operations = vec![
        EntryWriteOperation::Create(entry2.clone()),
        EntryWriteOperation::Create(entry1.clone()), // This should fail - duplicate key
    ];

    let result = datastore.bulk_entry_write(operations).await;
    assert!(result.is_err(), "Bulk write operations should fail due to duplicate key");

    // Verify that entry2 was not created (transaction rolled back)
    let entry2_result = datastore.get_entry_by_key(key2).await;
    assert!(entry2_result.is_err(), "Entry2 should not exist due to rollback");

    // Verify that entry1 still exists (it was created before the bulk operation)
    let entry1_result = datastore.get_entry_by_key(key1).await;
    assert!(entry1_result.is_ok(), "Entry1 should still exist");
}