// This file was initially generated by Cursor using the Claude 3 Opus LLM model.
// Integration tests for PostgreSQL datastore implementation.
// Updated for ST0009: 1:1 entry-context semantics.
use rstest::*;
use udex_api::entry::{
    Context as UdexContext, // Aliased to avoid clash with rstest Context - aliasing rstest Context causes issues with the `#[rstest]` attribute.
    KeyValuePair,
    Value,
};
use udex_api::index::Index;
use udex_api::index::IndexUpdate;
use udex_datastore::integration_test::data;
use udex_datastore::{
    Datastore, Entry, EntryReadOperation, EntryReadResult, EntryWriteOperation, Migrator,
};
use uuid::Uuid;

const ID_PREFIX: &str = "postgres_integration_test_";

// Generates a name for a test index based on the test context.
fn index_name(ctx: &Context) -> String {
    format!("{}_{}", ID_PREFIX, ctx.name)
}

/// Test helper to create a sample index
fn create_sample_index(name: &str) -> Index {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap();

    Index {
        name: name.to_string(),
        description: "Test index".to_string(),
        max_bulk_operations: 100,
        max_key_length: 256,
        max_value_length: 1024,
        max_kv_pairs_per_context: 50,
        hash_algorithm: udex_api::index::HashAlgorithm::Xxh3 as i32,
        created_at: Some(udex_api::protobuf::Timestamp {
            seconds: now.as_secs() as i64,
            nanos: now.subsec_nanos() as i32,
        }),
        created_by: "test_user".to_string(),
        updated_at: None,
        updated_by: None,
    }
}

/// Test helper to create a sample context
fn create_sample_context(hash: &str) -> UdexContext {
    UdexContext {
        hash: hash.to_string(),
        pairs: vec![
            KeyValuePair {
                key: "name".to_string(),
                value: Some(Value {
                    value: Some(udex_api::entry::value::Value::StringValue(
                        "test_value".to_string(),
                    )),
                }),
                kek_id: None,
                dek: None,
            },
            KeyValuePair {
                key: "count".to_string(),
                value: Some(Value {
                    value: Some(udex_api::entry::value::Value::IntValue(42)),
                }),
                kek_id: None,
                dek: None,
            },
        ],
    }
}

/// Tests that the datastore can be initialized successfully.
#[rstest]
#[tokio_shared_rt::test]
async fn test_datastore_init() {
    let data = data(false).await;
    let datastore = &data.0;
    let pool = &data.1;
    let res = sqlx::query("SELECT 1").execute(&**pool).await;
    assert!(res.is_ok(), "Database connection should succeed");
    // check migrations
    datastore
        .check_migration_version()
        .await
        .expect("Migration version check failed");
    // test health check
    let is_healthy = datastore.is_healthy().await.expect("Health check failed");
    assert!(is_healthy, "Datastore should be healthy");
}

// Tests creating an index and then retrieving it.
// Verifies that all index properties are correctly stored and retrieved,
// including name, description, limits, and hash algorithm.
#[rstest]
#[tokio_shared_rt::test]
async fn test_create_and_get_index(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);

    // Test creating an index
    let create_result = datastore.create_index(index.clone()).await;
    assert!(
        create_result.is_ok(),
        "{}",
        format!(
            "Index creation should succeed: {}",
            create_result.unwrap_err()
        )
    );

    // Test getting the index
    let retrieved_index = datastore
        .get_index(&idx_name)
        .await
        .expect("Failed to get index");
    assert_eq!(retrieved_index.name, index.name);
    assert_eq!(retrieved_index.description, index.description);
    assert_eq!(
        retrieved_index.max_bulk_operations,
        index.max_bulk_operations
    );
    assert_eq!(retrieved_index.max_key_length, index.max_key_length);
    assert_eq!(retrieved_index.max_value_length, index.max_value_length);
    assert_eq!(
        retrieved_index.max_kv_pairs_per_context,
        index.max_kv_pairs_per_context
    );
    assert_eq!(retrieved_index.hash_algorithm, index.hash_algorithm);
    assert!(retrieved_index.created_at.is_some());
    assert_eq!(retrieved_index.created_by, index.created_by);
    assert_eq!(retrieved_index.updated_at, index.updated_at);
    assert_eq!(retrieved_index.updated_by, index.updated_by);

    // Test that creating an index with the same name fails with invalid index error.
    let duplicate_result = datastore.create_index(index.clone()).await;
    assert!(
        duplicate_result.is_err(),
        "Creating index with duplicate name should fail"
    );
}

/// Tests creating an entry between a unique key and a context.
/// Under 1:1 semantics create_entry is idempotent: a second call with the same
/// context returns the pre-existing key rather than inserting a new row.
#[rstest]
#[tokio_shared_rt::test]
async fn test_create_entry(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let _pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_1");
    let candidate_key = Uuid::new_v4();

    // Create prerequisite index
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    let entry = Entry {
        key: candidate_key,
        context: context.clone(),
        index_name: idx_name.clone(),
    };

    // Test creating an entry — returns the stored key.
    let stored_key = datastore
        .create_entry(entry)
        .await
        .expect("Entry creation should succeed");
    assert_eq!(
        stored_key, candidate_key,
        "First create should use the candidate key"
    );

    // Verify the entry was created correctly by retrieving it.
    let retrieved_entry = datastore
        .get_entry_by_key(stored_key)
        .await
        .expect("Failed to retrieve created entry");

    assert_eq!(retrieved_entry.key, stored_key);
    assert_eq!(retrieved_entry.context.hash, context.hash);
    assert_eq!(retrieved_entry.context.pairs.len(), context.pairs.len());
    assert_eq!(retrieved_entry.context.pairs[0].key, "name");
    assert_eq!(retrieved_entry.context.pairs[1].key, "count");
    assert_eq!(retrieved_entry.index_name, idx_name);

    // Verify the context values are correct
    if let Some(ref name_value) = retrieved_entry.context.pairs[0].value {
        if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
            assert_eq!(s, "test_value");
        } else {
            panic!("Expected string value for name");
        }
    } else {
        panic!("Expected value for name");
    }

    if let Some(ref count_value) = retrieved_entry.context.pairs[1].value {
        if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
            assert_eq!(i, 42);
        } else {
            panic!("Expected int value for count");
        }
    } else {
        panic!("Expected value for count");
    }

    // Idempotent: a second create with the same context returns the existing key.
    let duplicate_entry = Entry {
        key: Uuid::new_v4(), // different candidate key — should be ignored
        context: context.clone(),
        index_name: idx_name.clone(),
    };
    let idempotent_key = datastore
        .create_entry(duplicate_entry)
        .await
        .expect("Idempotent create should succeed");
    assert_eq!(
        idempotent_key, stored_key,
        "Duplicate context should return the pre-existing key"
    );
}

/// Tests retrieving an entry by its associated unique key.
/// Verifies that the correct entry with full context data
/// is returned when querying by a key.
#[rstest]
#[tokio_shared_rt::test]
async fn test_get_entry_by_key(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let _pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_2");
    let candidate_key = Uuid::new_v4();

    // Create prerequisite data
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    let entry = Entry {
        key: candidate_key,
        context: context.clone(),
        index_name: idx_name.clone(),
    };

    let stored_key = datastore
        .create_entry(entry)
        .await
        .expect("Failed to create entry");

    // Test getting entry by key
    let retrieved_entry = datastore
        .get_entry_by_key(stored_key)
        .await
        .expect("Failed to get entry");
    assert_eq!(retrieved_entry.key, stored_key);
    assert_eq!(retrieved_entry.context.hash, context.hash);
    assert_eq!(retrieved_entry.context.pairs.len(), context.pairs.len());
    assert_eq!(retrieved_entry.context.pairs[0].key, "name");
    assert_eq!(retrieved_entry.context.pairs[1].key, "count");
    assert_eq!(retrieved_entry.index_name, idx_name);

    // Verify the context values are correct
    if let Some(ref name_value) = retrieved_entry.context.pairs[0].value {
        if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
            assert_eq!(s, "test_value");
        } else {
            panic!("Expected string value for name");
        }
    } else {
        panic!("Expected value for name");
    }

    if let Some(ref count_value) = retrieved_entry.context.pairs[1].value {
        if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
            assert_eq!(i, 42);
        } else {
            panic!("Expected int value for count");
        }
    } else {
        panic!("Expected value for count");
    }
}

/// Tests retrieving the single entry for a context hash.
/// Under 1:1 semantics a context maps to at most one entry.
/// Returns None when no entry exists, Some(entry) when one does.
#[rstest]
#[tokio_shared_rt::test]
async fn test_get_entry_by_context(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let _pool = &data.1;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_3");

    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // No entry yet — expect None.
    let result = datastore
        .get_entry_by_context(&idx_name, &context.hash)
        .await
        .expect("query should succeed");
    assert!(
        result.is_none(),
        "Expected None before any entry is created"
    );

    let key = Uuid::new_v4();
    let stored_key = datastore
        .create_entry(Entry {
            key,
            context: context.clone(),
            index_name: idx_name.clone(),
        })
        .await
        .expect("Failed to create entry");

    // Exactly one entry — expect Some.
    let result = datastore
        .get_entry_by_context(&idx_name, &context.hash)
        .await
        .expect("Failed to get entry by context");
    let entry = result.expect("Expected Some after creating entry");
    assert_eq!(entry.key, stored_key);
    assert_eq!(entry.context.hash, context.hash);
    assert_eq!(entry.index_name, idx_name);

    // Verify the context values are correct
    if let Some(ref name_value) = entry.context.pairs[0].value {
        if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
            assert_eq!(s, "test_value");
        } else {
            panic!("Expected string value for name");
        }
    } else {
        panic!("Expected value for name");
    }
}

/// Tests deleting an entry by key.
/// Verifies that the entry is removed and the context slot is freed so
/// a subsequent create with the same context produces a fresh key.
#[rstest]
#[tokio_shared_rt::test]
async fn test_delete_entry(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    let context = create_sample_context("test_hash_5");
    let key = Uuid::new_v4();

    // Create prerequisite data
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    let stored_key = datastore
        .create_entry(Entry {
            key,
            context: context.clone(),
            index_name: idx_name.clone(),
        })
        .await
        .expect("Failed to create entry");

    // Verify entry exists before deletion
    let retrieved = datastore
        .get_entry_by_key(stored_key)
        .await
        .expect("Failed to get entry before deletion");
    assert_eq!(retrieved.key, stored_key);
    assert_eq!(retrieved.context.hash, context.hash);

    // Delete the entry
    datastore
        .delete_entry(&idx_name, stored_key)
        .await
        .expect("Deleting entry should succeed");

    // Verify the entry is gone by key
    let not_found = datastore.get_entry_by_key(stored_key).await;
    assert!(
        not_found.is_err(),
        "Deleted entry should not be found by key"
    );

    // Verify the entry is gone by context
    let by_ctx = datastore
        .get_entry_by_context(&idx_name, &context.hash)
        .await
        .expect("query failed");
    assert!(
        by_ctx.is_none(),
        "Deleted entry should not be found by context"
    );

    // Re-creating with the same context after deletion produces a fresh key.
    let new_key = Uuid::new_v4();
    let re_stored = datastore
        .create_entry(Entry {
            key: new_key,
            context: context.clone(),
            index_name: idx_name.clone(),
        })
        .await
        .expect("Re-create after delete should succeed");
    assert_eq!(
        re_stored, new_key,
        "Re-created entry should use the new candidate key"
    );
    assert_ne!(
        re_stored, stored_key,
        "Re-created key should differ from the deleted key"
    );
}

/// Tests error handling for various failure scenarios.
/// Verifies that appropriate errors are returned for non-existent resources
/// and that absent results are handled correctly.
#[rstest]
#[tokio_shared_rt::test]
async fn test_error_handling() {
    let data = data(false).await;
    let datastore = &data.0;

    // Test getting non-existent index
    let result = datastore.get_index("non_existent_index").await;
    assert!(result.is_err(), "Getting non-existent index should fail");

    // Test getting entry by non-existent key
    let non_existent_key = Uuid::new_v4();
    let result = datastore.get_entry_by_key(non_existent_key).await;
    assert!(
        result.is_err(),
        "Getting entry by non-existent key should fail"
    );

    // Test getting entry by non-existent context returns None, not an error.
    let result = datastore
        .get_entry_by_context("non_existent_index", "non_existent_context")
        .await;
    assert!(
        result.is_ok(),
        "Getting entry by non-existent context should succeed"
    );
    assert!(
        result.unwrap().is_none(),
        "Non-existent context should return None"
    );
}

/// Tests updating an index's mutable fields.
/// Verifies that index descriptions can be updated and that
/// the updated values are correctly persisted and retrieved.
#[rstest]
#[tokio_shared_rt::test]
async fn test_update_index(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);

    // Create index
    datastore
        .create_index(index.clone())
        .await
        .expect("Failed to create index");

    // Update the index description
    let new_description = Some("Updated test index description".to_string());
    let new_description_value = new_description.clone().unwrap_or_default();
    let update = IndexUpdate {
        description: new_description.clone(),
        max_bulk_operations: None,
        max_key_length: None,
        max_value_length: None,
        max_kv_pairs_per_context: None,
        hash_algorithm: None,
    };
    let updated_index = datastore
        .update_index(&idx_name, update, "test_update_index")
        .await
        .expect("Failed to update index");

    // Verify the update
    assert_eq!(updated_index.name, index.name);
    assert_eq!(updated_index.description, new_description_value);
    assert_eq!(updated_index.max_bulk_operations, index.max_bulk_operations);
    assert_eq!(updated_index.hash_algorithm, index.hash_algorithm);
    assert_eq!(updated_index.created_by, index.created_by);
    assert!(updated_index.created_at.is_some());

    // Verify by getting the index again
    let retrieved_index = datastore
        .get_index(&idx_name)
        .await
        .expect("Failed to get updated index");
    assert_eq!(retrieved_index.description, new_description_value);

    // Test updating to empty description
    let empty_description_update = IndexUpdate {
        description: Some("".to_string()),
        max_bulk_operations: None,
        max_key_length: None,
        max_value_length: None,
        max_kv_pairs_per_context: None,
        hash_algorithm: None,
    };
    let updated_to_empty = datastore
        .update_index(&idx_name, empty_description_update, "test_update_index")
        .await
        .expect("Failed to update index to empty description");
    assert_eq!(updated_to_empty.description, "");

    // Test all mutable fields can be updated
    let full_update = IndexUpdate {
        description: Some("Full update test index".to_string()),
        max_bulk_operations: Some(200),
        max_key_length: Some(512),
        max_value_length: Some(2048),
        max_kv_pairs_per_context: Some(100),
        hash_algorithm: Some(udex_api::index::HashAlgorithm::Xxh3 as i32),
    };
    let updated_full_index = datastore
        .update_index(&idx_name, full_update, "test_full_update_index")
        .await
        .expect("Failed to fully update index");
    assert_eq!(updated_full_index.name, index.name);
    assert_eq!(updated_full_index.description, "Full update test index");
    assert_eq!(updated_full_index.max_bulk_operations, 200);
    assert_eq!(updated_full_index.max_key_length, 512);
    assert_eq!(updated_full_index.max_value_length, 2048);
    assert_eq!(updated_full_index.max_kv_pairs_per_context, 100);
    assert_eq!(
        updated_full_index.hash_algorithm,
        udex_api::index::HashAlgorithm::Xxh3 as i32
    );

    // Test updating no fields throws an error
    let no_update = IndexUpdate {
        description: None,
        max_bulk_operations: None,
        max_key_length: None,
        max_value_length: None,
        max_kv_pairs_per_context: None,
        hash_algorithm: None,
    };
    let no_update_result = datastore
        .update_index(&idx_name, no_update, "test_update_index")
        .await;
    assert!(
        no_update_result.is_err(),
        "Updating index with no changes should fail"
    );
    if let Err(error) = no_update_result {
        match error {
            udex_datastore::Error::InvalidIndexUpdate(_) => {
                // This is expected
            }
            _ => panic!("Expected InvalidIndexUpdate error, got: {:?}", error),
        }
    }
}

/// Tests listing all indices.
/// Verifies that all created indices are returned in the list
/// and that the list is properly ordered by name.
#[rstest]
#[tokio_shared_rt::test]
async fn test_list_indices(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    // Create multiple indices
    let index1 = create_sample_index(&format!("{}_list_1", idx_name));
    let index2 = create_sample_index(&format!("{}_list_2", idx_name));
    let index3 = create_sample_index(&format!("{}_list_3", idx_name));

    datastore
        .create_index(index1.clone())
        .await
        .expect("Failed to create index 1");
    datastore
        .create_index(index2.clone())
        .await
        .expect("Failed to create index 2");
    datastore
        .create_index(index3.clone())
        .await
        .expect("Failed to create index 3");

    // List all indices
    let indices = datastore
        .list_indices()
        .await
        .expect("Failed to list indices");

    // Find our test indices in the list
    let our_indices: Vec<_> = indices
        .iter()
        .filter(|idx| idx.name.contains(&format!("{}_list_", idx_name)))
        .collect();

    assert_eq!(our_indices.len(), 3);
    assert!(our_indices.iter().any(|idx| idx.name == index1.name));
    assert!(our_indices.iter().any(|idx| idx.name == index2.name));
    assert!(our_indices.iter().any(|idx| idx.name == index3.name));

    // Verify ordering (should be sorted by name)
    for i in 1..our_indices.len() {
        assert!(our_indices[i - 1].name <= our_indices[i].name);
    }
}

/// Tests concurrent operations on the datastore.
/// Verifies that multiple simultaneous operations can be performed safely
/// without data corruption or race conditions.
#[rstest]
#[tokio_shared_rt::test]
async fn test_concurrent_operations(#[context] ctx: Context) {
    let fixtures = data(false).await;
    let datastore = &fixtures.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    let mut handles = vec![];
    let idx_name_clone = idx_name.clone();

    for i in 0..10 {
        // Each task uses a unique context hash so there are no idempotency collisions.
        let idx_name_for_task = idx_name_clone.clone();

        let handle = tokio::spawn(async move {
            // Due to maybe_once these will be the same datastore and pool.
            let loop_fixtures = data(false).await;
            let loop_datastore = &loop_fixtures.0;

            let context = create_sample_context(&format!("concurrent_hash_{}", i));
            let candidate_key = Uuid::new_v4();

            let stored_key = loop_datastore
                .create_entry(Entry {
                    key: candidate_key,
                    context: context.clone(),
                    index_name: idx_name_for_task,
                })
                .await
                .expect("Failed to create entry");

            assert_eq!(stored_key, candidate_key);

            // Get entry back and verify values
            let retrieved_entry = loop_datastore
                .get_entry_by_key(stored_key)
                .await
                .expect("Failed to get entry");
            assert_eq!(retrieved_entry.context.hash, context.hash);
            assert_eq!(retrieved_entry.key, stored_key);
            assert_eq!(retrieved_entry.context.pairs.len(), context.pairs.len());

            // Verify the context values are correct
            if let Some(ref name_value) = retrieved_entry.context.pairs[0].value {
                if let Some(udex_api::entry::value::Value::StringValue(ref s)) = name_value.value {
                    assert_eq!(s, "test_value");
                }
            }

            if let Some(ref count_value) = retrieved_entry.context.pairs[1].value {
                if let Some(udex_api::entry::value::Value::IntValue(i)) = count_value.value {
                    assert_eq!(i, 42);
                }
            }
        });

        handles.push(handle);
    }

    // Wait for all operations to complete
    for handle in handles {
        handle.await.expect("Concurrent operation failed");
    }
}

/// Tests bulk write operations (create and delete) in a single transaction.
/// Verifies that multiple operations are executed atomically and that the
/// actual key is returned for each create (new or pre-existing).
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_entry_write(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Use distinct contexts for each entry so creates are independent.
    let context1 = create_sample_context("test_bulk_write_1");
    let context2 = create_sample_context("test_bulk_write_2");
    let context3 = create_sample_context("test_bulk_write_3");
    let key1 = Uuid::new_v4();
    let key2 = Uuid::new_v4();
    let key3 = Uuid::new_v4();

    let entry1 = Entry {
        key: key1,
        context: context1.clone(),
        index_name: idx_name.clone(),
    };
    let entry2 = Entry {
        key: key2,
        context: context2.clone(),
        index_name: idx_name.clone(),
    };
    let entry3 = Entry {
        key: key3,
        context: context3.clone(),
        index_name: idx_name.clone(),
    };

    // Pre-create entry3 individually to test deletion within the bulk write.
    let stored_key3 = datastore
        .create_entry(entry3)
        .await
        .expect("Failed to create entry for deletion test");

    // Bulk write: create two new entries and delete entry3.
    let operations = vec![
        EntryWriteOperation::Create(entry1.clone()),
        EntryWriteOperation::Create(entry2.clone()),
        EntryWriteOperation::Delete {
            index_name: idx_name.clone(),
            key: stored_key3,
        },
    ];

    let results = datastore
        .bulk_entry_write(operations)
        .await
        .expect("Bulk write should succeed");
    assert_eq!(results.len(), 3);

    let stored_key1 = match &results[0] {
        udex_datastore::EntryWriteResult::Created(k) => *k,
        _ => panic!("Expected Created result for entry1"),
    };
    let stored_key2 = match &results[1] {
        udex_datastore::EntryWriteResult::Created(k) => *k,
        _ => panic!("Expected Created result for entry2"),
    };
    assert!(
        matches!(&results[2], udex_datastore::EntryWriteResult::Deleted),
        "Expected Deleted result for entry3"
    );

    assert_eq!(stored_key1, key1);
    assert_eq!(stored_key2, key2);

    // Verify the entries were created
    let retrieved_entry1 = datastore
        .get_entry_by_key(stored_key1)
        .await
        .expect("Failed to retrieve first created entry");
    assert_eq!(retrieved_entry1.key, stored_key1);
    assert_eq!(retrieved_entry1.context.hash, context1.hash);

    let retrieved_entry2 = datastore
        .get_entry_by_key(stored_key2)
        .await
        .expect("Failed to retrieve second created entry");
    assert_eq!(retrieved_entry2.key, stored_key2);
    assert_eq!(retrieved_entry2.context.hash, context2.hash);

    // Verify the entry was deleted
    let delete_result = datastore.get_entry_by_key(stored_key3).await;
    assert!(delete_result.is_err(), "Deleted entry should not be found");
}

/// Tests bulk read operations in a single transaction.
/// Verifies that GetByKey returns Entry and GetByContext returns EntryByContext
/// with Some or None depending on whether an entry exists.
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_entry_read(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    let context1 = create_sample_context("test_bulk_read_1");
    let context2 = create_sample_context("test_bulk_read_2");
    let key1 = Uuid::new_v4();
    let key2 = Uuid::new_v4();

    // Create entries — each with a distinct context.
    let stored_key1 = datastore
        .create_entry(Entry {
            key: key1,
            context: context1.clone(),
            index_name: idx_name.clone(),
        })
        .await
        .expect("Failed to create entry1");

    let stored_key2 = datastore
        .create_entry(Entry {
            key: key2,
            context: context2.clone(),
            index_name: idx_name.clone(),
        })
        .await
        .expect("Failed to create entry2");

    // Test bulk read operations including a non-existent context.
    let operations = vec![
        EntryReadOperation::GetByKey(stored_key1),
        EntryReadOperation::GetByKey(stored_key2),
        EntryReadOperation::GetByContext {
            index_name: idx_name.clone(),
            context_hash: context1.hash.clone(),
        },
        EntryReadOperation::GetByContext {
            index_name: idx_name.clone(),
            context_hash: "nonexistent_hash".to_string(),
        },
    ];

    let result = datastore.bulk_entry_read(operations).await;
    assert!(
        result.is_ok(),
        "Bulk read operations should succeed: {:?}",
        result.err()
    );

    let results = result.unwrap();
    assert_eq!(results.len(), 4, "Should have 4 results");

    // Check first result - GetByKey(stored_key1)
    match &results[0] {
        EntryReadResult::ByKey(entry) => {
            assert_eq!(entry.key, stored_key1);
            assert_eq!(entry.context.hash, context1.hash);
            assert_eq!(entry.index_name, idx_name);
            assert_eq!(entry.context.pairs.len(), 2);
        }
        _ => panic!("Expected Entry result for GetByKey operation"),
    }

    // Check second result - GetByKey(stored_key2)
    match &results[1] {
        EntryReadResult::ByKey(entry) => {
            assert_eq!(entry.key, stored_key2);
            assert_eq!(entry.context.hash, context2.hash);
            assert_eq!(entry.index_name, idx_name);
            assert_eq!(entry.context.pairs.len(), 2);
        }
        _ => panic!("Expected Entry result for GetByKey operation"),
    }

    // Check third result - GetByContext(context1.hash) — exactly one entry.
    match &results[2] {
        EntryReadResult::EntryByContext(Some(entry)) => {
            assert_eq!(entry.key, stored_key1);
            assert_eq!(entry.context.hash, context1.hash);
            assert_eq!(entry.index_name, idx_name);
        }
        EntryReadResult::EntryByContext(None) => {
            panic!("Expected Some for existing context")
        }
        _ => panic!("Expected EntryByContext result for GetByContext operation"),
    }

    // Check fourth result - GetByContext("nonexistent_hash") — no entry.
    match &results[3] {
        EntryReadResult::EntryByContext(None) => {}
        EntryReadResult::EntryByContext(Some(_)) => {
            panic!("Expected None for non-existent context")
        }
        _ => panic!("Expected EntryByContext result for GetByContext operation"),
    }
}

/// Tests bulk write operations with transaction rollback on failure.
/// Verifies that if any operation fails, all operations are rolled back.
/// The rollback is triggered by attempting to delete a non-existent key.
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_entry_write_rollback(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_name = index_name(&ctx);

    let index = create_sample_index(&idx_name);
    datastore
        .create_index(index)
        .await
        .expect("Failed to create index");

    // Pre-create an entry so we can verify it is unaffected by rollback.
    let context1 = create_sample_context("test_bulk_rollback_1");
    let key1 = Uuid::new_v4();
    let stored_key1 = datastore
        .create_entry(Entry {
            key: key1,
            context: context1.clone(),
            index_name: idx_name.clone(),
        })
        .await
        .expect("Failed to create entry for rollback test");

    let context2 = create_sample_context("test_bulk_rollback_2");
    let key2 = Uuid::new_v4();
    let entry2 = Entry {
        key: key2,
        context: context2.clone(),
        index_name: idx_name.clone(),
    };

    // Bulk: create entry2 then delete a non-existent key — the delete triggers rollback.
    let non_existent_key = Uuid::new_v4();
    let operations = vec![
        EntryWriteOperation::Create(entry2),
        EntryWriteOperation::Delete {
            index_name: idx_name.clone(),
            key: non_existent_key,
        },
    ];

    let result = datastore.bulk_entry_write(operations).await;
    assert!(
        result.is_err(),
        "Bulk write operations should fail due to missing delete target"
    );

    // Verify that entry2 was not created (transaction rolled back)
    let entry2_result = datastore.get_entry_by_key(key2).await;
    assert!(
        entry2_result.is_err(),
        "entry2 should not exist due to rollback"
    );

    // Verify that entry1 still exists (it was created before the bulk operation)
    let entry1_result = datastore.get_entry_by_key(stored_key1).await;
    assert!(entry1_result.is_ok(), "entry1 should still exist");
}

/// Tests that the 1:1 constraint is per-index, not global.
///
/// The same context hash must be allowed to appear in two different indexes, each
/// producing an independent entry key. A `UNIQUE(context_hash)` global constraint
/// would reject the second insert — this test would then fail, proving the bug.
#[rstest]
#[tokio_shared_rt::test]
async fn test_same_context_different_indexes_get_independent_keys(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_a = format!("{}_multi_idx_a", index_name(&ctx));
    let idx_b = format!("{}_multi_idx_b", index_name(&ctx));

    datastore
        .create_index(create_sample_index(&idx_a))
        .await
        .expect("create index A");
    datastore
        .create_index(create_sample_index(&idx_b))
        .await
        .expect("create index B");

    // The same context pairs → same hash — used in both indexes.
    let context = create_sample_context("shared_context_hash_multi_index");

    let key_a = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_a.clone(),
        })
        .await
        .expect("create entry in index A");

    // Must not fail — per-index uniqueness allows the same hash in a different index.
    let key_b = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_b.clone(),
        })
        .await
        .expect("create entry in index B must succeed (per-index uniqueness)");

    assert_ne!(key_a, key_b, "each index must produce an independent key");

    // Lookup by context is scoped to the index — each returns its own entry.
    let found_a = datastore
        .get_entry_by_context(&idx_a, &context.hash)
        .await
        .expect("lookup in index A")
        .expect("should be Some");
    assert_eq!(found_a.key, key_a);
    assert_eq!(found_a.index_name, idx_a);

    let found_b = datastore
        .get_entry_by_context(&idx_b, &context.hash)
        .await
        .expect("lookup in index B")
        .expect("should be Some");
    assert_eq!(found_b.key, key_b);
    assert_eq!(found_b.index_name, idx_b);
}

/// Tests that idempotent create remains per-index under the new constraint.
///
/// Creating the same context twice in index A returns the same key both times.
/// Creating the same context in index B is independent and gets its own key.
/// This verifies the full per-index idempotency contract.
#[rstest]
#[tokio_shared_rt::test]
async fn test_idempotent_create_is_per_index(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_a = format!("{}_idem_idx_a", index_name(&ctx));
    let idx_b = format!("{}_idem_idx_b", index_name(&ctx));

    datastore
        .create_index(create_sample_index(&idx_a))
        .await
        .expect("create index A");
    datastore
        .create_index(create_sample_index(&idx_b))
        .await
        .expect("create index B");

    let context = create_sample_context("idempotent_multi_index_hash");

    // First create in A.
    let key_a1 = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_a.clone(),
        })
        .await
        .expect("first create in A");

    // Second create in A with the same context — idempotent, must return key_a1.
    let key_a2 = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_a.clone(),
        })
        .await
        .expect("second create in A");
    assert_eq!(
        key_a1, key_a2,
        "idempotent create in same index must return same key"
    );

    // First create in B — independent of A, must get a new key.
    let key_b = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_b.clone(),
        })
        .await
        .expect("first create in B");
    assert_ne!(
        key_a1, key_b,
        "different indexes must produce independent keys"
    );
}

/// Tests bulk read across two indexes with the same context hash.
///
/// GetByContext operations are scoped to an index — the same hash in two
/// indexes returns two distinct entries, one per index.
#[rstest]
#[tokio_shared_rt::test]
async fn test_bulk_read_get_by_context_is_index_scoped(#[context] ctx: Context) {
    let data = data(false).await;
    let datastore = &data.0;
    let idx_a = format!("{}_bulk_ctx_idx_a", index_name(&ctx));
    let idx_b = format!("{}_bulk_ctx_idx_b", index_name(&ctx));

    datastore
        .create_index(create_sample_index(&idx_a))
        .await
        .expect("create index A");
    datastore
        .create_index(create_sample_index(&idx_b))
        .await
        .expect("create index B");

    let context = create_sample_context("bulk_read_multi_index_hash");

    let key_a = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_a.clone(),
        })
        .await
        .expect("create in A");
    let key_b = datastore
        .create_entry(Entry {
            key: Uuid::new_v4(),
            context: context.clone(),
            index_name: idx_b.clone(),
        })
        .await
        .expect("create in B");

    let results = datastore
        .bulk_entry_read(vec![
            EntryReadOperation::GetByContext {
                index_name: idx_a.clone(),
                context_hash: context.hash.clone(),
            },
            EntryReadOperation::GetByContext {
                index_name: idx_b.clone(),
                context_hash: context.hash.clone(),
            },
            // Same hash, wrong index — must return None.
            EntryReadOperation::GetByContext {
                index_name: idx_a.clone(),
                context_hash: "hash_that_does_not_exist".to_string(),
            },
        ])
        .await
        .expect("bulk read");

    assert_eq!(results.len(), 3);

    match &results[0] {
        EntryReadResult::EntryByContext(Some(e)) => {
            assert_eq!(e.key, key_a);
            assert_eq!(e.index_name, idx_a);
        }
        other => panic!("expected Some entry for index A, got {:?}", other),
    }

    match &results[1] {
        EntryReadResult::EntryByContext(Some(e)) => {
            assert_eq!(e.key, key_b);
            assert_eq!(e.index_name, idx_b);
        }
        other => panic!("expected Some entry for index B, got {:?}", other),
    }

    match &results[2] {
        EntryReadResult::EntryByContext(None) => {}
        other => panic!("expected None for missing hash, got {:?}", other),
    }
}
